<a href="https://colab.research.google.com/github/shintaroudlotulhanafia/DRLforMultipleStocksTradingUsingFinRL/blob/main/FractionsTest3/3_18_fraksi4_TugasAkhirS1_Shinta_DRLforMultipleStocksTradingUsingFinRL.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Notebook ini dijalankan menggunakan email dreamerteen18@gmail.com

# Deep Reinforcement Learning untuk Jual-Beli Saham (Dari Awal): Jual-beli Banyak Saham 

* **Pytorch Version**

# Daftar Isi:

* [1. Pendeskrisian Tugas](#0)
* [2. Instalasi Paket Python](#1)
    * [2.1. Instalasi Paket](#1.1)    
    * [2.2. Daftar Paket Python](#1.2)
    * [2.3. Impot Paket](#1.3)
    * [2.4. Membuat Folder](#1.4)
* [3. Mengunduh Data](#2)
* [4. Memproses Data](#3)        
    * [4.1. IndiKator Teknikal](#3.1)
    * [4.2. Melakukan *Feature Engineering*](#3.2)
* [5. Membangun Lingkungan Jual-Beli Saham dengan OpenAI Gym-style](#4)  
    * [5.1. Pemisahan Data](#4.1)  
    * [5.2. Lingkungan untuk Pelatihan *(Training)*](#4.2)    
* [6. Melatih Agen DRL](#5)
    * [6.1. Agen 1: A2C](#5.1)
    * [6.2. Agen 2: PPO](#5.2)
    * [6.3. Agen 3: TD3](#5.3)
    * [6.4. Agen 4: SAC](#5.4)
    * [6.5. Agen 5: DDPG](#5.5)
* [7. Melakukan Jual-Beli](#6)
    * [7.1. Performa di Dalam Sampel](#6.1)
    * [7.2. Performa di Luar Sampel](#6.2)
    * [7.3. Hasil Jual-Beli Untuk Setiap Agen Berupa Rangkuman Aksi](#6.3)
      * [7.3.1. Agen 1: A2C](#6.3.1)
      * [7.3.2. Agen 2: PPO](#6.3.2)
      * [7.3.3. Agen 3: TD3](#6.3.3)
      * [7.3.4. Agen 4: SAC](#6.3.4)
      * [7.3.5. Agen 5: DDPG](#6.3.5)
* [8. Performa Backtesting](#7)  
    * [8.1. Status BackTesting](#7.1)
    * [8.2. Gambaran BackTesting](#7.2)

<a id='0'></a>
# Bagian 1. Pendeskrisian Tugas

Agen DRL dilatih untuk melakukan jual-beli saham. Tugas tersebut dimodelkan sebagai Markov Decision Process (MDP), dengan fungsi dan tujuannya adalah memaksimalkan pengembalian pengembalian kumulatif *(cummulative return)* yang diharapkan.

Definisi state-action-reward pada algoritam DRL kasus kali ini adalah sebagai berikut:

* **State s**: Kondisi atau *state* mewakili persepsi agen tentang lingkungan pasar. Sama seperti *trader* manusia yang menganalisis berbagai informasi, agen juga secara pasif mengamati banyak fitur dan belajar dengan cara berinteraksi dengan lingkungan pasar (biasanya dengan menjalankan ulang data historis).

* **Tindakan atau *action* a**: Ruang aksi mencakup aksi atau tindakan yang dapat dilakukan agen di setiap status atau kondisi. Misalnya, a {−1, 0, 1}, -1 berarti menjual, 0 berarti menahan, dan 1 berarti membeli. Ketika suatu aksi mengoperasikan beberapa saham, maka, a {−k, ..., 1, 0, 1, ..., k}. Misalnya, "Beli
10 saham TLKM" atau "Jual 10 saham TLKM" maka masing-masing nilai a adalah 10 atau -10.

* **Fungsi *reward* atau imbalan r(s, a, s′)**: *Reward* adalah insentif bagi agen untuk mempelajari kebijakan yang lebih baik. Misalnya *reward* dapat berupa perubahan nilai portofolio saat mengambil a pada keadaan s dan tiba pada keadaan baru s', yaitu, r(s, a, s′) = v′-v, v′ mewakili nilai portofolio pada keadaan s′ dan v mewakili nilai portofolio pada keadaan s.

* **Environment atau lingkungan jual-beli**: saham penyusun indeks JII dengan tanggal sesuai periode pengujian yang diatur.


Data untuk studi kasus ini diperoleh dari Yahoo Finance API. Data berisi harga *Open-High-Low-Close* dan *Volume*.

<a id='1'></a>
# Bagian 2. Instalasi Paket Python

<a id='1.1'></a>
## 2.1. Instalasi Paket

In [1]:
# install finrl library
!pip install git+https://github.com/shintaroudlotulhanafia/FinRL.git

Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/
Collecting git+https://github.com/shintaroudlotulhanafia/FinRL.git
  Cloning https://github.com/shintaroudlotulhanafia/FinRL.git to /tmp/pip-req-build-l_42xj_f
  Running command git clone -q https://github.com/shintaroudlotulhanafia/FinRL.git /tmp/pip-req-build-l_42xj_f
Collecting pyfolio@ git+https://github.com/quantopian/pyfolio.git#egg=pyfolio-0.9.2
  Cloning https://github.com/quantopian/pyfolio.git to /tmp/pip-install-6es30s3n/pyfolio_59c50348f4a84153b5830cb49bcabdd1
  Running command git clone -q https://github.com/quantopian/pyfolio.git /tmp/pip-install-6es30s3n/pyfolio_59c50348f4a84153b5830cb49bcabdd1
Collecting elegantrl@ git+https://github.com/AI4Finance-Foundation/ElegantRL.git#egg=elegantrl
  Cloning https://github.com/AI4Finance-Foundation/ElegantRL.git to /tmp/pip-install-6es30s3n/elegantrl_5a51e42bca524685bc1ab9157b12e945
  Running command git clone -q https://github.com/AI4Finance-Foundation/ElegantRL.git /tmp/pip-install-6es30s3n/elegantrl_5a51e42bca524685bc1ab9157b12e945
Collecting alpaca_trade_api>=2.1.0
  Downloading alpaca_trade_api-2.3.0-py3-none-any.whl (33 kB)
Collecting ccxt==1.66.32
  Downloading ccxt-1.66.32-py2.py3-none-any.whl (2.3 MB)
     |████████████████████████████████| 2.3 MB 45.8 MB/s
Collecting elegantrl
  Downloading elegantrl-0.3.3-py3-none-any.whl (234 kB)
     |████████████████████████████████| 234 kB 68.5 MB/s
Collecting exchange_calendars
  Downloading exchange_calendars-3.6.3.tar.gz (152 kB)
     |████████████████████████████████| 152 kB 67.8 MB/s
Collecting gputil
  Downloading GPUtil-1.4.0.tar.gz (5.5 kB)
Requirement already satisfied: gym>=0.17 in /usr/local/lib/python3.7/dist-packages (from finrl==0.3.5) (0.25.2)
Collecting jqdatasdk
  Downloading jqdatasdk-1.8.10-py3-none-any.whl (153 kB)
     |████████████████████████████████| 153 kB 68.1 MB/s
Collecting lz4
  Downloading lz4-4.0.2-cp37-cp37m-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (1.2 MB)
     |████████████████████████████████| 1.2 MB 56.7 MB/s
Requirement already satisfied: matplotlib in /usr/local/lib/python3.7/dist-packages (from finrl==0.3.5) (3.2.2)
Requirement already satisfied: numpy>=1.17.3 in /usr/local/lib/python3.7/dist-packages (from finrl==0.3.5) (1.21.6)
Requirement already satisfied: pandas>=1.1.5 in /usr/local/lib/python3.7/dist-packages (from finrl==0.3.5) (1.3.5)
Collecting pre-commit
  Downloading pre_commit-2.20.0-py2.py3-none-any.whl (199 kB)
     |████████████████████████████████| 199 kB 59.3 MB/s
Requirement already satisfied: pytest in /usr/local/lib/python3.7/dist-packages (from finrl==0.3.5) (3.6.4)
Collecting ray[default]
  Downloading ray-2.0.0-cp37-cp37m-manylinux2014_x86_64.whl (59.4 MB)
     |████████████████████████████████| 59.4 MB 1.3 MB/s
Requirement already satisfied: scikit-learn>=0.21.0 in /usr/local/lib/python3.7/dist-packages (from finrl==0.3.5) (1.0.2)
Collecting setuptools==59.5.0
  Downloading setuptools-59.5.0-py3-none-any.whl (952 kB)
     |████████████████████████████████| 952 kB 56.1 MB/s
Collecting stable-baselines3[extra]
  Downloading stable_baselines3-1.6.0-py3-none-any.whl (177 kB)
     |████████████████████████████████| 177 kB 72.2 MB/s
Collecting stockstats>=0.4.0
  Downloading stockstats-0.4.1-py2.py3-none-any.whl (19 kB)
Collecting tensorboardX
  Downloading tensorboardX-2.5.1-py2.py3-none-any.whl (125 kB)
     |████████████████████████████████| 125 kB 67.7 MB/s
Requirement already satisfied: wheel>=0.33.6 in /usr/local/lib/python3.7/dist-packages (from finrl==0.3.5) (0.37.1)
Collecting wrds
  Downloading wrds-3.1.2-py3-none-any.whl (13 kB)
Collecting yfinance
  Downloading yfinance-0.1.74-py2.py3-none-any.whl (27 kB)
Collecting pybullet
  Downloading pybullet-3.2.5-cp37-cp37m-manylinux_2_5_x86_64.manylinux1_x86_64.whl (91.7 MB)
     |████████████████████████████████| 91.7 MB 45 kB/s
Requirement already satisfied: torch in /usr/local/lib/python3.7/dist-packages (from elegantrl@ git+https://github.com/AI4Finance-Foundation/ElegantRL.git#egg=elegantrl->finrl==0.3.5) (1.12.1+cu113)
Requirement already satisfied: opencv-python in /usr/local/lib/python3.7/dist-packages (from elegantrl@ git+https://github.com/AI4Finance-Foundation/ElegantRL.git#egg=elegantrl->finrl==0.3.5) (4.6.0.66)
Collecting box2d-py
  Downloading box2d_py-2.3.8-cp37-cp37m-manylinux1_x86_64.whl (448 kB)
     |████████████████████████████████| 448 kB 73.5 MB/s
Requirement already satisfied: ipython>=3.2.3 in /usr/local/lib/python3.7/dist-packages (from pyfolio@ git+https://github.com/quantopian/pyfolio.git#egg=pyfolio-0.9.2->finrl==0.3.5) (7.9.0)
Requirement already satisfied: pytz>=2014.10 in /usr/local/lib/python3.7/dist-packages (from pyfolio@ git+https://github.com/quantopian/pyfolio.git#egg=pyfolio-0.9.2->finrl==0.3.5) (2022.2.1)
Requirement already satisfied: scipy>=0.14.0 in /usr/local/lib/python3.7/dist-packages (from pyfolio@ git+https://github.com/quantopian/pyfolio.git#egg=pyfolio-0.9.2->finrl==0.3.5) (1.7.3)
Requirement already satisfied: seaborn>=0.7.1 in /usr/local/lib/python3.7/dist-packages (from pyfolio@ git+https://github.com/quantopian/pyfolio.git#egg=pyfolio-0.9.2->finrl==0.3.5) (0.11.2)
Collecting empyrical>=0.5.0
  Downloading empyrical-0.5.5.tar.gz (52 kB)
     |████████████████████████████████| 52 kB 1.7 MB/s
Collecting aiodns>=1.1.1
  Downloading aiodns-3.0.0-py3-none-any.whl (5.0 kB)
Collecting yarl==1.7.2
  Downloading yarl-1.7.2-cp37-cp37m-manylinux_2_5_x86_64.manylinux1_x86_64.manylinux_2_12_x86_64.manylinux2010_x86_64.whl (271 kB)
     |████████████████████████████████| 271 kB 75.3 MB/s
Requirement already satisfied: requests>=2.18.4 in /usr/local/lib/python3.7/dist-packages (from ccxt==1.66.32->finrl==0.3.5) (2.23.0)
Collecting cryptography>=2.6.1
  Downloading cryptography-37.0.4-cp36-abi3-manylinux_2_24_x86_64.whl (4.1 MB)
     |████████████████████████████████| 4.1 MB 51.7 MB/s
Requirement already satisfied: certifi>=2018.1.18 in /usr/local/lib/python3.7/dist-packages (from ccxt==1.66.32->finrl==0.3.5) (2022.6.15)
Requirement already satisfied: aiohttp>=3.8 in /usr/local/lib/python3.7/dist-packages (from ccxt==1.66.32->finrl==0.3.5) (3.8.1)
Requirement already satisfied: multidict>=4.0 in /usr/local/lib/python3.7/dist-packages (from yarl==1.7.2->ccxt==1.66.32->finrl==0.3.5) (6.0.2)
Requirement already satisfied: typing-extensions>=3.7.4 in /usr/local/lib/python3.7/dist-packages (from yarl==1.7.2->ccxt==1.66.32->finrl==0.3.5) (4.1.1)
Requirement already satisfied: idna>=2.0 in /usr/local/lib/python3.7/dist-packages (from yarl==1.7.2->ccxt==1.66.32->finrl==0.3.5) (2.10)
Collecting pycares>=4.0.0
  Downloading pycares-4.2.2-cp37-cp37m-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (288 kB)
     |████████████████████████████████| 288 kB 75.0 MB/s
Requirement already satisfied: attrs>=17.3.0 in /usr/local/lib/python3.7/dist-packages (from aiohttp>=3.8->ccxt==1.66.32->finrl==0.3.5) (22.1.0)
Requirement already satisfied: asynctest==0.13.0 in /usr/local/lib/python3.7/dist-packages (from aiohttp>=3.8->ccxt==1.66.32->finrl==0.3.5) (0.13.0)
Requirement already satisfied: aiosignal>=1.1.2 in /usr/local/lib/python3.7/dist-packages (from aiohttp>=3.8->ccxt==1.66.32->finrl==0.3.5) (1.2.0)
Requirement already satisfied: charset-normalizer<3.0,>=2.0 in /usr/local/lib/python3.7/dist-packages (from aiohttp>=3.8->ccxt==1.66.32->finrl==0.3.5) (2.1.1)
Requirement already satisfied: async-timeout<5.0,>=4.0.0a3 in /usr/local/lib/python3.7/dist-packages (from aiohttp>=3.8->ccxt==1.66.32->finrl==0.3.5) (4.0.2)
Requirement already satisfied: frozenlist>=1.1.1 in /usr/local/lib/python3.7/dist-packages (from aiohttp>=3.8->ccxt==1.66.32->finrl==0.3.5) (1.3.1)
Collecting websocket-client<2,>=0.56.0
  Downloading websocket_client-1.4.1-py3-none-any.whl (55 kB)
     |████████████████████████████████| 55 kB 4.2 MB/s
Requirement already satisfied: PyYAML==6.0 in /usr/local/lib/python3.7/dist-packages (from alpaca_trade_api>=2.1.0->finrl==0.3.5) (6.0)
Collecting msgpack==1.0.3
  Downloading msgpack-1.0.3-cp37-cp37m-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (299 kB)
     |████████████████████████████████| 299 kB 66.2 MB/s
Requirement already satisfied: urllib3<2,>1.24 in /usr/local/lib/python3.7/dist-packages (from alpaca_trade_api>=2.1.0->finrl==0.3.5) (1.24.3)
Collecting deprecation==2.1.0
  Downloading deprecation-2.1.0-py2.py3-none-any.whl (11 kB)
Collecting websockets<11,>=9.0
  Downloading websockets-10.3-cp37-cp37m-manylinux_2_5_x86_64.manylinux1_x86_64.manylinux_2_12_x86_64.manylinux2010_x86_64.whl (112 kB)
     |████████████████████████████████| 112 kB 72.6 MB/s
Requirement already satisfied: packaging in /usr/local/lib/python3.7/dist-packages (from deprecation==2.1.0->alpaca_trade_api>=2.1.0->finrl==0.3.5) (21.3)
Requirement already satisfied: cffi>=1.12 in /usr/local/lib/python3.7/dist-packages (from cryptography>=2.6.1->ccxt==1.66.32->finrl==0.3.5) (1.15.1)
Requirement already satisfied: pycparser in /usr/local/lib/python3.7/dist-packages (from cffi>=1.12->cryptography>=2.6.1->ccxt==1.66.32->finrl==0.3.5) (2.21)
Requirement already satisfied: pandas-datareader>=0.2 in /usr/local/lib/python3.7/dist-packages (from empyrical>=0.5.0->pyfolio@ git+https://github.com/quantopian/pyfolio.git#egg=pyfolio-0.9.2->finrl==0.3.5) (0.9.0)
Requirement already satisfied: cloudpickle>=1.2.0 in /usr/local/lib/python3.7/dist-packages (from gym>=0.17->finrl==0.3.5) (1.5.0)
Requirement already satisfied: importlib-metadata>=4.8.0 in /usr/local/lib/python3.7/dist-packages (from gym>=0.17->finrl==0.3.5) (4.12.0)
Requirement already satisfied: gym-notices>=0.0.4 in /usr/local/lib/python3.7/dist-packages (from gym>=0.17->finrl==0.3.5) (0.0.8)
Requirement already satisfied: zipp>=0.5 in /usr/local/lib/python3.7/dist-packages (from importlib-metadata>=4.8.0->gym>=0.17->finrl==0.3.5) (3.8.1)
Requirement already satisfied: traitlets>=4.2 in /usr/local/lib/python3.7/dist-packages (from ipython>=3.2.3->pyfolio@ git+https://github.com/quantopian/pyfolio.git#egg=pyfolio-0.9.2->finrl==0.3.5) (5.1.1)
Requirement already satisfied: backcall in /usr/local/lib/python3.7/dist-packages (from ipython>=3.2.3->pyfolio@ git+https://github.com/quantopian/pyfolio.git#egg=pyfolio-0.9.2->finrl==0.3.5) (0.2.0)
Requirement already satisfied: pygments in /usr/local/lib/python3.7/dist-packages (from ipython>=3.2.3->pyfolio@ git+https://github.com/quantopian/pyfolio.git#egg=pyfolio-0.9.2->finrl==0.3.5) (2.6.1)
Requirement already satisfied: pexpect in /usr/local/lib/python3.7/dist-packages (from ipython>=3.2.3->pyfolio@ git+https://github.com/quantopian/pyfolio.git#egg=pyfolio-0.9.2->finrl==0.3.5) (4.8.0)
Collecting jedi>=0.10
  Downloading jedi-0.18.1-py2.py3-none-any.whl (1.6 MB)
     |████████████████████████████████| 1.6 MB 63.8 MB/s
Requirement already satisfied: pickleshare in /usr/local/lib/python3.7/dist-packages (from ipython>=3.2.3->pyfolio@ git+https://github.com/quantopian/pyfolio.git#egg=pyfolio-0.9.2->finrl==0.3.5) (0.7.5)
Requirement already satisfied: decorator in /usr/local/lib/python3.7/dist-packages (from ipython>=3.2.3->pyfolio@ git+https://github.com/quantopian/pyfolio.git#egg=pyfolio-0.9.2->finrl==0.3.5) (4.4.2)
Requirement already satisfied: prompt-toolkit<2.1.0,>=2.0.0 in /usr/local/lib/python3.7/dist-packages (from ipython>=3.2.3->pyfolio@ git+https://github.com/quantopian/pyfolio.git#egg=pyfolio-0.9.2->finrl==0.3.5) (2.0.10)
Requirement already satisfied: parso<0.9.0,>=0.8.0 in /usr/local/lib/python3.7/dist-packages (from jedi>=0.10->ipython>=3.2.3->pyfolio@ git+https://github.com/quantopian/pyfolio.git#egg=pyfolio-0.9.2->finrl==0.3.5) (0.8.3)
Requirement already satisfied: pyparsing!=2.0.4,!=2.1.2,!=2.1.6,>=2.0.1 in /usr/local/lib/python3.7/dist-packages (from matplotlib->finrl==0.3.5) (3.0.9)
Requirement already satisfied: kiwisolver>=1.0.1 in /usr/local/lib/python3.7/dist-packages (from matplotlib->finrl==0.3.5) (1.4.4)
Requirement already satisfied: cycler>=0.10 in /usr/local/lib/python3.7/dist-packages (from matplotlib->finrl==0.3.5) (0.11.0)
Requirement already satisfied: python-dateutil>=2.1 in /usr/local/lib/python3.7/dist-packages (from matplotlib->finrl==0.3.5) (2.8.2)
Requirement already satisfied: lxml in /usr/local/lib/python3.7/dist-packages (from pandas-datareader>=0.2->empyrical>=0.5.0->pyfolio@ git+https://github.com/quantopian/pyfolio.git#egg=pyfolio-0.9.2->finrl==0.3.5) (4.9.1)
Requirement already satisfied: six>=1.9.0 in /usr/local/lib/python3.7/dist-packages (from prompt-toolkit<2.1.0,>=2.0.0->ipython>=3.2.3->pyfolio@ git+https://github.com/quantopian/pyfolio.git#egg=pyfolio-0.9.2->finrl==0.3.5) (1.15.0)
Requirement already satisfied: wcwidth in /usr/local/lib/python3.7/dist-packages (from prompt-toolkit<2.1.0,>=2.0.0->ipython>=3.2.3->pyfolio@ git+https://github.com/quantopian/pyfolio.git#egg=pyfolio-0.9.2->finrl==0.3.5) (0.2.5)
Requirement already satisfied: chardet<4,>=3.0.2 in /usr/local/lib/python3.7/dist-packages (from requests>=2.18.4->ccxt==1.66.32->finrl==0.3.5) (3.0.4)
Requirement already satisfied: joblib>=0.11 in /usr/local/lib/python3.7/dist-packages (from scikit-learn>=0.21.0->finrl==0.3.5) (1.1.0)
Requirement already satisfied: threadpoolctl>=2.0.0 in /usr/local/lib/python3.7/dist-packages (from scikit-learn>=0.21.0->finrl==0.3.5) (3.1.0)
Collecting pyluach
  Downloading pyluach-2.0.1-py3-none-any.whl (22 kB)
Requirement already satisfied: toolz in /usr/local/lib/python3.7/dist-packages (from exchange_calendars->finrl==0.3.5) (0.12.0)
Requirement already satisfied: korean_lunar_calendar in /usr/local/lib/python3.7/dist-packages (from exchange_calendars->finrl==0.3.5) (0.2.1)
Collecting thriftpy2>=0.3.9
  Downloading thriftpy2-0.4.14.tar.gz (361 kB)
     |████████████████████████████████| 361 kB 71.8 MB/s
Collecting pymysql>=0.7.6
  Downloading PyMySQL-1.0.2-py3-none-any.whl (43 kB)
     |████████████████████████████████| 43 kB 2.8 MB/s
Requirement already satisfied: SQLAlchemy>=1.2.8 in /usr/local/lib/python3.7/dist-packages (from jqdatasdk->finrl==0.3.5) (1.4.40)
Requirement already satisfied: greenlet!=0.4.17 in /usr/local/lib/python3.7/dist-packages (from SQLAlchemy>=1.2.8->jqdatasdk->finrl==0.3.5) (1.1.3)
Collecting ply<4.0,>=3.4
  Downloading ply-3.11-py2.py3-none-any.whl (49 kB)
     |████████████████████████████████| 49 kB 7.6 MB/s
Requirement already satisfied: ptyprocess>=0.5 in /usr/local/lib/python3.7/dist-packages (from pexpect->ipython>=3.2.3->pyfolio@ git+https://github.com/quantopian/pyfolio.git#egg=pyfolio-0.9.2->finrl==0.3.5) (0.7.0)
Collecting identify>=1.0.0
  Downloading identify-2.5.4-py2.py3-none-any.whl (98 kB)
     |████████████████████████████████| 98 kB 9.0 MB/s
Collecting cfgv>=2.0.0
  Downloading cfgv-3.3.1-py2.py3-none-any.whl (7.3 kB)
Collecting virtualenv>=20.0.8
  Downloading virtualenv-20.16.4-py3-none-any.whl (8.8 MB)
     |████████████████████████████████| 8.8 MB 59.6 MB/s
Requirement already satisfied: toml in /usr/local/lib/python3.7/dist-packages (from pre-commit->finrl==0.3.5) (0.10.2)
Collecting nodeenv>=0.11.1
  Downloading nodeenv-1.7.0-py2.py3-none-any.whl (21 kB)
Collecting platformdirs<3,>=2.4
  Downloading platformdirs-2.5.2-py3-none-any.whl (14 kB)
Collecting distlib<1,>=0.3.5
  Downloading distlib-0.3.6-py2.py3-none-any.whl (468 kB)
     |████████████████████████████████| 468 kB 74.2 MB/s
Requirement already satisfied: filelock<4,>=3.4.1 in /usr/local/lib/python3.7/dist-packages (from virtualenv>=20.0.8->pre-commit->finrl==0.3.5) (3.8.0)
Requirement already satisfied: atomicwrites>=1.0 in /usr/local/lib/python3.7/dist-packages (from pytest->finrl==0.3.5) (1.4.1)
Requirement already satisfied: pluggy<0.8,>=0.5 in /usr/local/lib/python3.7/dist-packages (from pytest->finrl==0.3.5) (0.7.1)
Requirement already satisfied: more-itertools>=4.0.0 in /usr/local/lib/python3.7/dist-packages (from pytest->finrl==0.3.5) (8.14.0)
Requirement already satisfied: py>=1.5.0 in /usr/local/lib/python3.7/dist-packages (from pytest->finrl==0.3.5) (1.11.0)
Requirement already satisfied: click<=8.0.4,>=7.0 in /usr/local/lib/python3.7/dist-packages (from ray[default]->finrl==0.3.5) (7.1.2)
Requirement already satisfied: protobuf<4.0.0,>=3.15.3 in /usr/local/lib/python3.7/dist-packages (from ray[default]->finrl==0.3.5) (3.17.3)
Collecting grpcio<=1.43.0,>=1.28.1
  Downloading grpcio-1.43.0-cp37-cp37m-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (4.1 MB)
     |████████████████████████████████| 4.1 MB 57.3 MB/s
Requirement already satisfied: jsonschema in /usr/local/lib/python3.7/dist-packages (from ray[default]->finrl==0.3.5) (4.3.3)
Requirement already satisfied: pydantic in /usr/local/lib/python3.7/dist-packages (from ray[default]->finrl==0.3.5) (1.9.2)
Collecting gpustat>=1.0.0b1
  Downloading gpustat-1.0.0.tar.gz (90 kB)
     |████████████████████████████████| 90 kB 12.2 MB/s
Collecting py-spy>=0.2.0
  Downloading py_spy-0.3.12-py2.py3-none-manylinux_2_5_x86_64.manylinux1_x86_64.whl (3.1 MB)
     |████████████████████████████████| 3.1 MB 58.4 MB/s
Collecting opencensus
  Downloading opencensus-0.11.0-py2.py3-none-any.whl (128 kB)
     |████████████████████████████████| 128 kB 75.8 MB/s
Requirement already satisfied: smart-open in /usr/local/lib/python3.7/dist-packages (from ray[default]->finrl==0.3.5) (5.2.1)
Collecting colorful
  Downloading colorful-0.5.4-py2.py3-none-any.whl (201 kB)
     |████████████████████████████████| 201 kB 78.0 MB/s
Collecting aiohttp-cors
  Downloading aiohttp_cors-0.7.0-py3-none-any.whl (27 kB)
Collecting prometheus-client<0.14.0,>=0.7.1
  Downloading prometheus_client-0.13.1-py3-none-any.whl (57 kB)
     |████████████████████████████████| 57 kB 5.8 MB/s
Collecting nvidia-ml-py<=11.495.46,>=11.450.129
  Downloading nvidia_ml_py-11.495.46-py3-none-any.whl (25 kB)
Collecting psutil>=5.6.0
  Downloading psutil-5.9.2-cp37-cp37m-manylinux_2_12_x86_64.manylinux2010_x86_64.manylinux_2_17_x86_64.manylinux2014_x86_64.whl (281 kB)
     |████████████████████████████████| 281 kB 73.1 MB/s
Collecting blessed>=1.17.1
  Downloading blessed-1.19.1-py2.py3-none-any.whl (58 kB)
     |████████████████████████████████| 58 kB 7.0 MB/s
Requirement already satisfied: pyrsistent!=0.17.0,!=0.17.1,!=0.17.2,>=0.14.0 in /usr/local/lib/python3.7/dist-packages (from jsonschema->ray[default]->finrl==0.3.5) (0.18.1)
Requirement already satisfied: importlib-resources>=1.4.0 in /usr/local/lib/python3.7/dist-packages (from jsonschema->ray[default]->finrl==0.3.5) (5.9.0)
Requirement already satisfied: google-api-core<3.0.0,>=1.0.0 in /usr/local/lib/python3.7/dist-packages (from opencensus->ray[default]->finrl==0.3.5) (1.31.6)
Collecting opencensus-context>=0.1.3
  Downloading opencensus_context-0.1.3-py2.py3-none-any.whl (5.1 kB)
Requirement already satisfied: googleapis-common-protos<2.0dev,>=1.6.0 in /usr/local/lib/python3.7/dist-packages (from google-api-core<3.0.0,>=1.0.0->opencensus->ray[default]->finrl==0.3.5) (1.56.4)
Requirement already satisfied: google-auth<2.0dev,>=1.25.0 in /usr/local/lib/python3.7/dist-packages (from google-api-core<3.0.0,>=1.0.0->opencensus->ray[default]->finrl==0.3.5) (1.35.0)
Requirement already satisfied: pyasn1-modules>=0.2.1 in /usr/local/lib/python3.7/dist-packages (from google-auth<2.0dev,>=1.25.0->google-api-core<3.0.0,>=1.0.0->opencensus->ray[default]->finrl==0.3.5) (0.2.8)
Requirement already satisfied: rsa<5,>=3.1.4 in /usr/local/lib/python3.7/dist-packages (from google-auth<2.0dev,>=1.25.0->google-api-core<3.0.0,>=1.0.0->opencensus->ray[default]->finrl==0.3.5) (4.9)
Requirement already satisfied: cachetools<5.0,>=2.0.0 in /usr/local/lib/python3.7/dist-packages (from google-auth<2.0dev,>=1.25.0->google-api-core<3.0.0,>=1.0.0->opencensus->ray[default]->finrl==0.3.5) (4.2.4)
Requirement already satisfied: pyasn1<0.5.0,>=0.4.6 in /usr/local/lib/python3.7/dist-packages (from pyasn1-modules>=0.2.1->google-auth<2.0dev,>=1.25.0->google-api-core<3.0.0,>=1.0.0->opencensus->ray[default]->finrl==0.3.5) (0.4.8)

<a id='1.2'></a>
## 2.2. Daftar Paket Python
* Yahoo Finance API
* pandas
* numpy
* matplotlib
* stockstats
* OpenAI gym
* stable-baselines
* tensorflow
* pyfolio

<a id='1.3'></a>
## 2.3. Impot Paket

* Modul Python **pandas** digunakan untuk menganalisis dan memanipulasi data.
* Modul Python **numpy** digunakan untuk memproses larik atau array.
* Modul Python **matplotlib** digunakan membuat visualisasi data dalam dua dimensi.
* Modul Python **matplotlib.pyplot** adalah kumpulan fungsi yang membuat matplotlib berfungsi seperti MATLAB.
* Modul Python **Datetime** menyediakan sejumlah fungsi untuk menangani tanggal, waktu, dan interval waktu. Date dan datetime adalah objek dalam Python, bukan string atau timestamps.
* **YahooDownloader** menyediakan metode untuk mengambil data saham harian dari API Keuangan Yahoo!
* **FeatureEngineer** menyediakan metode untuk preprocessing data harga saham
* **data_split** membagi dataset menjadi data pelatihan dan data pengujian berdasarkan tanggal
* **StockTradingEnv** Lingkungan perdagangan saham untuk OpenAI gym
* **DRLAgent** menyediakan implementasi untuk algoritma DRL
* **DataProcessor** memproses data menggunakan prosesor data terpadu
* **backtest_stats** menghitung statistik *backtesting*
* **backtest_plot** membuat dan menampilkan plot ringkasan laporan *backtesting*.
* **get_daily_return** 
* **get_baseline** mengunduh data berdasarkan suatu indeks pada periode waktu tertentu.
* Metode **sys.path.append()** digunakan untuk menambahkan jalur sementara. Dengan demikian, jalur tersebut akan valid untuk sebuah sesi, misalnya.
* Python **itertool** adalah modul yang menyediakan berbagai fungsi yang bekerja pada iterator untuk menghasilkan iterator yang kompleks. Modul ini berfungsi sebagai alat yang cepat dan hemat memori.

In [2]:
import pandas as pd
import numpy as np
import matplotlib
import matplotlib.pyplot as plt
# matplotlib.use('Agg')
import datetime

%matplotlib inline
from finrl.meta.preprocessor.yahoodownloader import YahooDownloader
from finrl.meta.preprocessor.preprocessors import FeatureEngineer, data_split
from finrl.meta.env_stock_trading.env_stocktrading import StockTradingEnv
from finrl.agents.stablebaselines3.models import DRLAgent
from finrl.meta.data_processor import DataProcessor

from finrl.plot import backtest_stats, backtest_plot, get_daily_return, get_baseline
from pprint import pprint

import sys
sys.path.append("../FinRL")

import itertools

/usr/local/lib/python3.7/dist-packages/pyfolio/pos.py:27: UserWarning: Module "zipline.assets" not found; multipliers will not be applied to position notionals.
  'Module "zipline.assets" not found; multipliers will not be applied'

<a id='1.4'></a>
## 2.4. Membuat Folder

In [3]:
from finrl import config
from finrl import config_tickers
import os
from finrl.main import check_and_make_directories
from finrl.config import (
    DATA_SAVE_DIR,
    TRAINED_MODEL_DIR,
    TENSORBOARD_LOG_DIR,
    RESULTS_DIR,
    INDICATORS,
    TRAIN_START_DATE,
    TRAIN_END_DATE,
    TEST_START_DATE,
    TEST_END_DATE,
    TRADE_START_DATE,
    TRADE_END_DATE,
)
check_and_make_directories([DATA_SAVE_DIR, TRAINED_MODEL_DIR, TENSORBOARD_LOG_DIR, RESULTS_DIR])

<a id='2'></a>
# Part 3. Mengunduh Data

Yahoo Finance menyediakan data saham, berita keuangan, laporan keuangan, dll, secara gratis.
* FinRL *Library* menggunakan kelas **YahooDownloader** di FinRL-Meta untuk mengambil data melalui Yahoo Finance API
* Batas Pemanggilan: Menggunakan API Publik (tanpa autentikasi), Pengguna dibatasi hingga 2.000 permintaan per jam per IP (atau hingga total 48.000 permintaan per hari).

In [4]:
TRAIN_START_DATE = '2009-01-01'
TRAIN_END_DATE = '2017-12-31'
TRADE_START_DATE = '2018-01-01'
TRADE_END_DATE = '2019-12-20'

In [5]:
#Data diperoleh dari idx.co.id diakses pada tanggal 27/08/2022
#Fraksi 1: x<Rp200,00
fraksi1 = ['KIJA.JK', 'LCGP.JK', 'LMPI.JK', 'LPKR.JK']

#Fraksi 2: Rp200,00<= x <Rp500,00
fraksi2 = ['BMTR.JK','BTON.JK','FORU.JK','GEMA.JK']

#Fraksi 3: Rp500,00<= x <Rp2.000,00
fraksi3 = ['AKRA.JK','BRPT.JK','KLBF.JK','MEDC.JK']

#Fraksi 4: Rp2000,00<= x <Rp5000,00
fraksi4 = ['JECC.JK', 'TMAS.JK', 'TPIA.JK', 'UNVR.JK']

#Fraksi 5: >=Rp5000,00
fraksi5 =['INCO.JK','INDF.JK','INTP.JK','UNTR.JK']

In [57]:
df = YahooDownloader(start_date = TRAIN_START_DATE,
                     end_date = TRADE_END_DATE,
                     ticker_list = fraksi4).fetch_data()

[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
Shape of DataFrame:  (10916, 8)

In [58]:
df.nunique()

date      2729
open      2064
high      2070
low       2104
close     3387
volume    5390
tic          4
day          5
dtype: int64

In [59]:
print(df['tic'].unique())

['JECC.JK' 'TMAS.JK' 'TPIA.JK' 'UNVR.JK']

* **sort_values()** berfungsi mengurutkan bingkai data dalam urutan Ascending atau Descending dari kolom yang dilewati.
* **ignore_index** berfungsi untuk menentukan untuk mereset indeks mulai dari nol. Secara default disetel *false*.
* **head()** digunakan untuk mendapatkan n baris pertama.

In [60]:
df.sort_values(['date','tic'],ignore_index=True).head()

,date,open,high,low,close,volume,tic,day
0,2009-01-05,295.000000,295.000000,295.000000,198.915344,3,JECC.JK,0
1,2009-01-05,46.000000,47.000000,44.000000,34.214245,775000,TMAS.JK,0
2,2009-01-05,82.948853,82.948853,82.948853,66.105316,0,TPIA.JK,0
3,2009-01-05,1620.000000,1620.000000,1560.000000,1149.686523,20,UNVR.JK,0
4,2009-01-06,295.000000,295.000000,295.000000,198.915344,0,JECC.JK,1

<a id='3'></a>
# Bagian 4: Memproses Data

Periksa data yang hilang dan melakukan *feature engineering* untuk mengubah data menjadi *state*.
* **Menambahkan indikator teknis**

  Dalam praktik jual-beli, berbagai informasi perlu diperhitungkan, seperti harga historis, kepemilikan saham saat ini, indikator teknis, dll. Indikator teknis yang dapat digunakan antara lain, MACD, RSI, CCI, ADX, Bollinger Bands, dll. 
* **Menambahkan indeks turbulensi**

  Risk-aversion mencerminkan seberapa berani investor melakukan jual-beli saham dengan risiko yang tinggi. Hal ini mempengaruhi strategi trading investor ketika menghadapi tingkat volatilitas pasar yang berbeda. Untuk mengendalikan risiko dalam skenario terburuk, seperti krisis keuangan tahun 1998, FinRL menggunakan indeks turbulensi yang mengukur fluktuasi harga aset yang ekstrem.

In [61]:
INDICATORS = [
    "macd",
    "rsi_30",
    "cci_30"
]

Membersihkan data mentah dari nilai-nilai yang hilang. Sehingga saham dengan data yang hilang dihapus dari daftar.

In [62]:
fe = FeatureEngineer(
                    use_technical_indicator=True,
                    tech_indicator_list = INDICATORS,
                    use_vix=True,
                    use_turbulence=True,
                    user_defined_feature = False)

processed = fe.preprocess_data(df)

Successfully added technical indicators
[*********************100%***********************]  1 of 1 completed
Shape of DataFrame:  (2759, 8)
Successfully added vix
Successfully added turbulence index

In [63]:
processed.nunique()

date           2652
open           2044
high           2054
low            2085
close          3333
volume         5270
tic               4
day               5
macd          10592
rsi_30         7226
cci_30        10168
vix            1441
turbulence     2399
dtype: int64

In [64]:
list_ticker = processed["tic"].unique().tolist()
list_ticker

['JECC.JK', 'TMAS.JK', 'TPIA.JK', 'UNVR.JK']

In [65]:
list_date = list(pd.date_range(processed['date'].min(),processed['date'].max()).astype(str))
list_date

['2009-01-05',
 '2009-01-06',
 '2009-01-07',
 '2009-01-08',
 '2009-01-09',
 '2009-01-10',
 '2009-01-11',
 '2009-01-12',
 '2009-01-13',
 '2009-01-14',
 '2009-01-15',
 '2009-01-16',
 '2009-01-17',
 '2009-01-18',
 '2009-01-19',
 '2009-01-20',
 '2009-01-21',
 '2009-01-22',
 '2009-01-23',
 '2009-01-24',
 '2009-01-25',
 '2009-01-26',
 '2009-01-27',
 '2009-01-28',
 '2009-01-29',
 '2009-01-30',
 '2009-01-31',
 '2009-02-01',
 '2009-02-02',
 '2009-02-03',
 '2009-02-04',
 '2009-02-05',
 '2009-02-06',
 '2009-02-07',
 '2009-02-08',
 '2009-02-09',
 '2009-02-10',
 '2009-02-11',
 '2009-02-12',
 '2009-02-13',
 '2009-02-14',
 '2009-02-15',
 '2009-02-16',
 '2009-02-17',
 '2009-02-18',
 '2009-02-19',
 '2009-02-20',
 '2009-02-21',
 '2009-02-22',
 '2009-02-23',
 '2009-02-24',
 '2009-02-25',
 '2009-02-26',
 '2009-02-27',
 '2009-02-28',
 '2009-03-01',
 '2009-03-02',
 '2009-03-03',
 '2009-03-04',
 '2009-03-05',
 '2009-03-06',
 '2009-03-07',
 '2009-03-08',
 '2009-03-09',
 '2009-03-10',
 '2009-03-11',
 '2009-03-12',
 '2009-03-13',
 '2009-03-14',
 '2009-03-15',
 '2009-03-16',
 '2009-03-17',
 '2009-03-18',
 '2009-03-19',
 '2009-03-20',
 '2009-03-21',
 '2009-03-22',
 '2009-03-23',
 '2009-03-24',
 '2009-03-25',
 '2009-03-26',
 '2009-03-27',
 '2009-03-28',
 '2009-03-29',
 '2009-03-30',
 '2009-03-31',
 '2009-04-01',
 '2009-04-02',
 '2009-04-03',
 '2009-04-04',
 '2009-04-05',
 '2009-04-06',
 '2009-04-07',
 '2009-04-08',
 '2009-04-09',
 '2009-04-10',
 '2009-04-11',
 '2009-04-12',
 '2009-04-13',
 '2009-04-14',
 '2009-04-15',
 '2009-04-16',
 '2009-04-17',
 '2009-04-18',
 '2009-04-19',
 '2009-04-20',
 '2009-04-21',
 '2009-04-22',
 '2009-04-23',
 '2009-04-24',
 '2009-04-25',
 '2009-04-26',
 '2009-04-27',
 '2009-04-28',
 '2009-04-29',
 '2009-04-30',
 '2009-05-01',
 '2009-05-02',
 '2009-05-03',
 '2009-05-04',
 '2009-05-05',
 '2009-05-06',
 '2009-05-07',
 '2009-05-08',
 '2009-05-09',
 '2009-05-10',
 '2009-05-11',
 '2009-05-12',
 '2009-05-13',
 '2009-05-14',
 '2009-05-15',
 '2009-05-16',
 '2009-05-17',
 '2009-05-18',
 '2009-05-19',
 '2009-05-20',
 '2009-05-21',
 '2009-05-22',
 '2009-05-23',
 '2009-05-24',
 '2009-05-25',
 '2009-05-26',
 '2009-05-27',
 '2009-05-28',
 '2009-05-29',
 '2009-05-30',
 '2009-05-31',
 '2009-06-01',
 '2009-06-02',
 '2009-06-03',
 '2009-06-04',
 '2009-06-05',
 '2009-06-06',
 '2009-06-07',
 '2009-06-08',
 '2009-06-09',
 '2009-06-10',
 '2009-06-11',
 '2009-06-12',
 '2009-06-13',
 '2009-06-14',
 '2009-06-15',
 '2009-06-16',
 '2009-06-17',
 '2009-06-18',
 '2009-06-19',
 '2009-06-20',
 '2009-06-21',
 '2009-06-22',
 '2009-06-23',
 '2009-06-24',
 '2009-06-25',
 '2009-06-26',
 '2009-06-27',
 '2009-06-28',
 '2009-06-29',
 '2009-06-30',
 '2009-07-01',
 '2009-07-02',
 '2009-07-03',
 '2009-07-04',
 '2009-07-05',
 '2009-07-06',
 '2009-07-07',
 '2009-07-08',
 '2009-07-09',
 '2009-07-10',
 '2009-07-11',
 '2009-07-12',
 '2009-07-13',
 '2009-07-14',
 '2009-07-15',
 '2009-07-16',
 '2009-07-17',
 '2009-07-18',
 '2009-07-19',
 '2009-07-20',
 '2009-07-21',
 '2009-07-22',
 '2009-07-23',
 '2009-07-24',
 '2009-07-25',
 '2009-07-26',
 '2009-07-27',
 '2009-07-28',
 '2009-07-29',
 '2009-07-30',
 '2009-07-31',
 '2009-08-01',
 '2009-08-02',
 '2009-08-03',
 '2009-08-04',
 '2009-08-05',
 '2009-08-06',
 '2009-08-07',
 '2009-08-08',
 '2009-08-09',
 '2009-08-10',
 '2009-08-11',
 '2009-08-12',
 '2009-08-13',
 '2009-08-14',
 '2009-08-15',
 '2009-08-16',
 '2009-08-17',
 '2009-08-18',
 '2009-08-19',
 '2009-08-20',
 '2009-08-21',
 '2009-08-22',
 '2009-08-23',
 '2009-08-24',
 '2009-08-25',
 '2009-08-26',
 '2009-08-27',
 '2009-08-28',
 '2009-08-29',
 '2009-08-30',
 '2009-08-31',
 '2009-09-01',
 '2009-09-02',
 '2009-09-03',
 '2009-09-04',
 '2009-09-05',
 '2009-09-06',
 '2009-09-07',
 '2009-09-08',
 '2009-09-09',
 '2009-09-10',
 '2009-09-11',
 '2009-09-12',
 '2009-09-13',
 '2009-09-14',
 '2009-09-15',
 '2009-09-16',
 '2009-09-17',
 '2009-09-18',
 '2009-09-19',
 '2009-09-20',
 '2009-09-21',
 '2009-09-22',
 '2009-09-23',
 '2009-09-24',
 '2009-09-25',
 '2009-09-26',
 '2009-09-27',
 '2009-09-28',
 '2009-09-29',
 '2009-09-30',
 '2009-10-01',
 '2009-10-02',
 '2009-10-03',
 '2009-10-04',
 '2009-10-05',
 '2009-10-06',
 '2009-10-07',
 '2009-10-08',
 '2009-10-09',
 '2009-10-10',
 '2009-10-11',
 '2009-10-12',
 '2009-10-13',
 '2009-10-14',
 '2009-10-15',
 '2009-10-16',
 '2009-10-17',
 '2009-10-18',
 '2009-10-19',
 '2009-10-20',
 '2009-10-21',
 '2009-10-22',
 '2009-10-23',
 '2009-10-24',
 '2009-10-25',
 '2009-10-26',
 '2009-10-27',
 '2009-10-28',
 '2009-10-29',
 '2009-10-30',
 '2009-10-31',
 '2009-11-01',
 '2009-11-02',
 '2009-11-03',
 '2009-11-04',
 '2009-11-05',
 '2009-11-06',
 '2009-11-07',
 '2009-11-08',
 '2009-11-09',
 '2009-11-10',
 '2009-11-11',
 '2009-11-12',
 '2009-11-13',
 '2009-11-14',
 '2009-11-15',
 '2009-11-16',
 '2009-11-17',
 '2009-11-18',
 '2009-11-19',
 '2009-11-20',
 '2009-11-21',
 '2009-11-22',
 '2009-11-23',
 '2009-11-24',
 '2009-11-25',
 '2009-11-26',
 '2009-11-27',
 '2009-11-28',
 '2009-11-29',
 '2009-11-30',
 '2009-12-01',
 '2009-12-02',
 '2009-12-03',
 '2009-12-04',
 '2009-12-05',
 '2009-12-06',
 '2009-12-07',
 '2009-12-08',
 '2009-12-09',
 '2009-12-10',
 '2009-12-11',
 '2009-12-12',
 '2009-12-13',
 '2009-12-14',
 '2009-12-15',
 '2009-12-16',
 '2009-12-17',
 '2009-12-18',
 '2009-12-19',
 '2009-12-20',
 '2009-12-21',
 '2009-12-22',
 '2009-12-23',
 '2009-12-24',
 '2009-12-25',
 '2009-12-26',
 '2009-12-27',
 '2009-12-28',
 '2009-12-29',
 '2009-12-30',
 '2009-12-31',
 '2010-01-01',
 '2010-01-02',
 '2010-01-03',
 '2010-01-04',
 '2010-01-05',
 '2010-01-06',
 '2010-01-07',
 '2010-01-08',
 '2010-01-09',
 '2010-01-10',
 '2010-01-11',
 '2010-01-12',
 '2010-01-13',
 '2010-01-14',
 '2010-01-15',
 '2010-01-16',
 '2010-01-17',
 '2010-01-18',
 '2010-01-19',
 '2010-01-20',
 '2010-01-21',
 '2010-01-22',
 '2010-01-23',
 '2010-01-24',
 '2010-01-25',
 '2010-01-26',
 '2010-01-27',
 '2010-01-28',
 '2010-01-29',
 '2010-01-30',
 '2010-01-31',
 '2010-02-01',
 '2010-02-02',
 '2010-02-03',
 '2010-02-04',
 '2010-02-05',
 '2010-02-06',
 '2010-02-07',
 '2010-02-08',
 '2010-02-09',
 '2010-02-10',
 '2010-02-11',
 '2010-02-12',
 '2010-02-13',
 '2010-02-14',
 '2010-02-15',
 '2010-02-16',
 '2010-02-17',
 '2010-02-18',
 '2010-02-19',
 '2010-02-20',
 '2010-02-21',
 '2010-02-22',
 '2010-02-23',
 '2010-02-24',
 '2010-02-25',
 '2010-02-26',
 '2010-02-27',
 '2010-02-28',
 '2010-03-01',
 '2010-03-02',
 '2010-03-03',
 '2010-03-04',
 '2010-03-05',
 '2010-03-06',
 '2010-03-07',
 '2010-03-08',
 '2010-03-09',
 '2010-03-10',
 '2010-03-11',
 '2010-03-12',
 '2010-03-13',
 '2010-03-14',
 '2010-03-15',
 '2010-03-16',
 '2010-03-17',
 '2010-03-18',
 '2010-03-19',
 '2010-03-20',
 '2010-03-21',
 '2010-03-22',
 '2010-03-23',
 '2010-03-24',
 '2010-03-25',
 '2010-03-26',
 '2010-03-27',
 '2010-03-28',
 '2010-03-29',
 '2010-03-30',
 '2010-03-31',
 '2010-04-01',
 '2010-04-02',
 '2010-04-03',
 '2010-04-04',
 '2010-04-05',
 '2010-04-06',
 '2010-04-07',
 '2010-04-08',
 '2010-04-09',
 '2010-04-10',
 '2010-04-11',
 '2010-04-12',
 '2010-04-13',
 '2010-04-14',
 '2010-04-15',
 '2010-04-16',
 '2010-04-17',
 '2010-04-18',
 '2010-04-19',
 '2010-04-20',
 '2010-04-21',
 '2010-04-22',
 '2010-04-23',
 '2010-04-24',
 '2010-04-25',
 '2010-04-26',
 '2010-04-27',
 '2010-04-28',
 '2010-04-29',
 '2010-04-30',
 '2010-05-01',
 '2010-05-02',
 '2010-05-03',
 '2010-05-04',
 '2010-05-05',
 '2010-05-06',
 '2010-05-07',
 '2010-05-08',
 '2010-05-09',
 '2010-05-10',
 '2010-05-11',
 '2010-05-12',
 '2010-05-13',
 '2010-05-14',
 '2010-05-15',
 '2010-05-16',
 '2010-05-17',
 '2010-05-18',
 '2010-05-19',
 '2010-05-20',
 '2010-05-21',
 '2010-05-22',
 '2010-05-23',
 '2010-05-24',
 '2010-05-25',
 '2010-05-26',
 '2010-05-27',
 '2010-05-28',
 '2010-05-29',
 '2010-05-30',
 '2010-05-31',
 '2010-06-01',
 '2010-06-02',
 '2010-06-03',
 '2010-06-04',
 '2010-06-05',
 '2010-06-06',
 '2010-06-07',
 '2010-06-08',
 '2010-06-09',
 '2010-06-10',
 '2010-06-11',
 '2010-06-12',
 '2010-06-13',
 '2010-06-14',
 '2010-06-15',
 '2010-06-16',
 '2010-06-17',
 '2010-06-18',
 '2010-06-19',
 '2010-06-20',
 '2010-06-21',
 '2010-06-22',
 '2010-06-23',
 '2010-06-24',
 '2010-06-25',
 '2010-06-26',
 '2010-06-27',
 '2010-06-28',
 '2010-06-29',
 '2010-06-30',
 '2010-07-01',
 '2010-07-02',
 '2010-07-03',
 '2010-07-04',
 '2010-07-05',
 '2010-07-06',
 '2010-07-07',
 '2010-07-08',
 '2010-07-09',
 '2010-07-10',
 '2010-07-11',
 '2010-07-12',
 '2010-07-13',
 '2010-07-14',
 '2010-07-15',
 '2010-07-16',
 '2010-07-17',
 '2010-07-18',
 '2010-07-19',
 '2010-07-20',
 '2010-07-21',
 '2010-07-22',
 '2010-07-23',
 '2010-07-24',
 '2010-07-25',
 '2010-07-26',
 '2010-07-27',
 '2010-07-28',
 '2010-07-29',
 '2010-07-30',
 '2010-07-31',
 '2010-08-01',
 '2010-08-02',
 '2010-08-03',
 '2010-08-04',
 '2010-08-05',
 '2010-08-06',
 '2010-08-07',
 '2010-08-08',
 '2010-08-09',
 '2010-08-10',
 '2010-08-11',
 '2010-08-12',
 '2010-08-13',
 '2010-08-14',
 '2010-08-15',
 '2010-08-16',
 '2010-08-17',
 '2010-08-18',
 '2010-08-19',
 '2010-08-20',
 '2010-08-21',
 '2010-08-22',
 '2010-08-23',
 '2010-08-24',
 '2010-08-25',
 '2010-08-26',
 '2010-08-27',
 '2010-08-28',
 '2010-08-29',
 '2010-08-30',
 '2010-08-31',
 '2010-09-01',
 '2010-09-02',
 '2010-09-03',
 '2010-09-04',
 '2010-09-05',
 '2010-09-06',
 '2010-09-07',
 '2010-09-08',
 '2010-09-09',
 '2010-09-10',
 '2010-09-11',
 '2010-09-12',
 '2010-09-13',
 '2010-09-14',
 '2010-09-15',
 '2010-09-16',
 '2010-09-17',
 '2010-09-18',
 '2010-09-19',
 '2010-09-20',
 '2010-09-21',
 '2010-09-22',
 '2010-09-23',
 '2010-09-24',
 '2010-09-25',
 '2010-09-26',
 '2010-09-27',
 '2010-09-28',
 '2010-09-29',
 '2010-09-30',
 '2010-10-01',
 '2010-10-02',
 '2010-10-03',
 '2010-10-04',
 '2010-10-05',
 '2010-10-06',
 '2010-10-07',
 '2010-10-08',
 '2010-10-09',
 '2010-10-10',
 '2010-10-11',
 '2010-10-12',
 '2010-10-13',
 '2010-10-14',
 '2010-10-15',
 '2010-10-16',
 '2010-10-17',
 '2010-10-18',
 '2010-10-19',
 '2010-10-20',
 '2010-10-21',
 '2010-10-22',
 '2010-10-23',
 '2010-10-24',
 '2010-10-25',
 '2010-10-26',
 '2010-10-27',
 '2010-10-28',
 '2010-10-29',
 '2010-10-30',
 '2010-10-31',
 '2010-11-01',
 '2010-11-02',
 '2010-11-03',
 '2010-11-04',
 '2010-11-05',
 '2010-11-06',
 '2010-11-07',
 '2010-11-08',
 '2010-11-09',
 '2010-11-10',
 '2010-11-11',
 '2010-11-12',
 '2010-11-13',
 '2010-11-14',
 '2010-11-15',
 '2010-11-16',
 '2010-11-17',
 '2010-11-18',
 '2010-11-19',
 '2010-11-20',
 '2010-11-21',
 '2010-11-22',
 '2010-11-23',
 '2010-11-24',
 '2010-11-25',
 '2010-11-26',
 '2010-11-27',
 '2010-11-28',
 '2010-11-29',
 '2010-11-30',
 '2010-12-01',
 '2010-12-02',
 '2010-12-03',
 '2010-12-04',
 '2010-12-05',
 '2010-12-06',
 '2010-12-07',
 '2010-12-08',
 '2010-12-09',
 '2010-12-10',
 '2010-12-11',
 '2010-12-12',
 '2010-12-13',
 '2010-12-14',
 '2010-12-15',
 '2010-12-16',
 '2010-12-17',
 '2010-12-18',
 '2010-12-19',
 '2010-12-20',
 '2010-12-21',
 '2010-12-22',
 '2010-12-23',
 '2010-12-24',
 '2010-12-25',
 '2010-12-26',
 '2010-12-27',
 '2010-12-28',
 '2010-12-29',
 '2010-12-30',
 '2010-12-31',
 '2011-01-01',
 '2011-01-02',
 '2011-01-03',
 '2011-01-04',
 '2011-01-05',
 '2011-01-06',
 '2011-01-07',
 '2011-01-08',
 '2011-01-09',
 '2011-01-10',
 '2011-01-11',
 '2011-01-12',
 '2011-01-13',
 '2011-01-14',
 '2011-01-15',
 '2011-01-16',
 '2011-01-17',
 '2011-01-18',
 '2011-01-19',
 '2011-01-20',
 '2011-01-21',
 '2011-01-22',
 '2011-01-23',
 '2011-01-24',
 '2011-01-25',
 '2011-01-26',
 '2011-01-27',
 '2011-01-28',
 '2011-01-29',
 '2011-01-30',
 '2011-01-31',
 '2011-02-01',
 '2011-02-02',
 '2011-02-03',
 '2011-02-04',
 '2011-02-05',
 '2011-02-06',
 '2011-02-07',
 '2011-02-08',
 '2011-02-09',
 '2011-02-10',
 '2011-02-11',
 '2011-02-12',
 '2011-02-13',
 '2011-02-14',
 '2011-02-15',
 '2011-02-16',
 '2011-02-17',
 '2011-02-18',
 '2011-02-19',
 '2011-02-20',
 '2011-02-21',
 '2011-02-22',
 '2011-02-23',
 '2011-02-24',
 '2011-02-25',
 '2011-02-26',
 '2011-02-27',
 '2011-02-28',
 '2011-03-01',
 '2011-03-02',
 '2011-03-03',
 '2011-03-04',
 '2011-03-05',
 '2011-03-06',
 '2011-03-07',
 '2011-03-08',
 '2011-03-09',
 '2011-03-10',
 '2011-03-11',
 '2011-03-12',
 '2011-03-13',
 '2011-03-14',
 '2011-03-15',
 '2011-03-16',
 '2011-03-17',
 '2011-03-18',
 '2011-03-19',
 '2011-03-20',
 '2011-03-21',
 '2011-03-22',
 '2011-03-23',
 '2011-03-24',
 '2011-03-25',
 '2011-03-26',
 '2011-03-27',
 '2011-03-28',
 '2011-03-29',
 '2011-03-30',
 '2011-03-31',
 '2011-04-01',
 '2011-04-02',
 '2011-04-03',
 '2011-04-04',
 '2011-04-05',
 '2011-04-06',
 '2011-04-07',
 '2011-04-08',
 '2011-04-09',
 '2011-04-10',
 '2011-04-11',
 '2011-04-12',
 '2011-04-13',
 '2011-04-14',
 '2011-04-15',
 '2011-04-16',
 '2011-04-17',
 '2011-04-18',
 '2011-04-19',
 '2011-04-20',
 '2011-04-21',
 '2011-04-22',
 '2011-04-23',
 '2011-04-24',
 '2011-04-25',
 '2011-04-26',
 '2011-04-27',
 '2011-04-28',
 '2011-04-29',
 '2011-04-30',
 '2011-05-01',
 '2011-05-02',
 '2011-05-03',
 '2011-05-04',
 '2011-05-05',
 '2011-05-06',
 '2011-05-07',
 '2011-05-08',
 '2011-05-09',
 '2011-05-10',
 '2011-05-11',
 '2011-05-12',
 '2011-05-13',
 '2011-05-14',
 '2011-05-15',
 '2011-05-16',
 '2011-05-17',
 '2011-05-18',
 '2011-05-19',
 '2011-05-20',
 '2011-05-21',
 '2011-05-22',
 '2011-05-23',
 '2011-05-24',
 '2011-05-25',
 '2011-05-26',
 '2011-05-27',
 '2011-05-28',
 '2011-05-29',
 '2011-05-30',
 '2011-05-31',
 '2011-06-01',
 '2011-06-02',
 '2011-06-03',
 '2011-06-04',
 '2011-06-05',
 '2011-06-06',
 '2011-06-07',
 '2011-06-08',
 '2011-06-09',
 '2011-06-10',
 '2011-06-11',
 '2011-06-12',
 '2011-06-13',
 '2011-06-14',
 '2011-06-15',
 '2011-06-16',
 '2011-06-17',
 '2011-06-18',
 '2011-06-19',
 '2011-06-20',
 '2011-06-21',
 '2011-06-22',
 '2011-06-23',
 '2011-06-24',
 '2011-06-25',
 '2011-06-26',
 '2011-06-27',
 '2011-06-28',
 '2011-06-29',
 '2011-06-30',
 '2011-07-01',
 '2011-07-02',
 '2011-07-03',
 '2011-07-04',
 '2011-07-05',
 '2011-07-06',
 '2011-07-07',
 '2011-07-08',
 '2011-07-09',
 '2011-07-10',
 '2011-07-11',
 '2011-07-12',
 '2011-07-13',
 '2011-07-14',
 '2011-07-15',
 '2011-07-16',
 '2011-07-17',
 '2011-07-18',
 '2011-07-19',
 '2011-07-20',
 '2011-07-21',
 '2011-07-22',
 '2011-07-23',
 '2011-07-24',
 '2011-07-25',
 '2011-07-26',
 '2011-07-27',
 '2011-07-28',
 '2011-07-29',
 '2011-07-30',
 '2011-07-31',
 '2011-08-01',
 '2011-08-02',
 '2011-08-03',
 '2011-08-04',
 '2011-08-05',
 '2011-08-06',
 '2011-08-07',
 '2011-08-08',
 '2011-08-09',
 '2011-08-10',
 '2011-08-11',
 '2011-08-12',
 '2011-08-13',
 '2011-08-14',
 '2011-08-15',
 '2011-08-16',
 '2011-08-17',
 '2011-08-18',
 '2011-08-19',
 '2011-08-20',
 '2011-08-21',
 '2011-08-22',
 '2011-08-23',
 '2011-08-24',
 '2011-08-25',
 '2011-08-26',
 '2011-08-27',
 '2011-08-28',
 '2011-08-29',
 '2011-08-30',
 '2011-08-31',
 '2011-09-01',
 '2011-09-02',
 '2011-09-03',
 '2011-09-04',
 '2011-09-05',
 '2011-09-06',
 '2011-09-07',
 '2011-09-08',
 '2011-09-09',
 '2011-09-10',
 '2011-09-11',
 '2011-09-12',
 '2011-09-13',
 '2011-09-14',
 '2011-09-15',
 '2011-09-16',
 '2011-09-17',
 '2011-09-18',
 '2011-09-19',
 '2011-09-20',
 '2011-09-21',
 '2011-09-22',
 '2011-09-23',
 '2011-09-24',
 '2011-09-25',
 '2011-09-26',
 '2011-09-27',
 '2011-09-28',
 '2011-09-29',
 '2011-09-30',
 '2011-10-01',
 ...]

In [66]:
combination = list(itertools.product(list_date,list_ticker))
combination

[('2009-01-05', 'JECC.JK'),
 ('2009-01-05', 'TMAS.JK'),
 ('2009-01-05', 'TPIA.JK'),
 ('2009-01-05', 'UNVR.JK'),
 ('2009-01-06', 'JECC.JK'),
 ('2009-01-06', 'TMAS.JK'),
 ('2009-01-06', 'TPIA.JK'),
 ('2009-01-06', 'UNVR.JK'),
 ('2009-01-07', 'JECC.JK'),
 ('2009-01-07', 'TMAS.JK'),
 ('2009-01-07', 'TPIA.JK'),
 ('2009-01-07', 'UNVR.JK'),
 ('2009-01-08', 'JECC.JK'),
 ('2009-01-08', 'TMAS.JK'),
 ('2009-01-08', 'TPIA.JK'),
 ('2009-01-08', 'UNVR.JK'),
 ('2009-01-09', 'JECC.JK'),
 ('2009-01-09', 'TMAS.JK'),
 ('2009-01-09', 'TPIA.JK'),
 ('2009-01-09', 'UNVR.JK'),
 ('2009-01-10', 'JECC.JK'),
 ('2009-01-10', 'TMAS.JK'),
 ('2009-01-10', 'TPIA.JK'),
 ('2009-01-10', 'UNVR.JK'),
 ('2009-01-11', 'JECC.JK'),
 ('2009-01-11', 'TMAS.JK'),
 ('2009-01-11', 'TPIA.JK'),
 ('2009-01-11', 'UNVR.JK'),
 ('2009-01-12', 'JECC.JK'),
 ('2009-01-12', 'TMAS.JK'),
 ('2009-01-12', 'TPIA.JK'),
 ('2009-01-12', 'UNVR.JK'),
 ('2009-01-13', 'JECC.JK'),
 ('2009-01-13', 'TMAS.JK'),
 ('2009-01-13', 'TPIA.JK'),
 ('2009-01-13', 'UNVR.JK'),
 ('2009-01-14', 'JECC.JK'),
 ('2009-01-14', 'TMAS.JK'),
 ('2009-01-14', 'TPIA.JK'),
 ('2009-01-14', 'UNVR.JK'),
 ('2009-01-15', 'JECC.JK'),
 ('2009-01-15', 'TMAS.JK'),
 ('2009-01-15', 'TPIA.JK'),
 ('2009-01-15', 'UNVR.JK'),
 ('2009-01-16', 'JECC.JK'),
 ('2009-01-16', 'TMAS.JK'),
 ('2009-01-16', 'TPIA.JK'),
 ('2009-01-16', 'UNVR.JK'),
 ('2009-01-17', 'JECC.JK'),
 ('2009-01-17', 'TMAS.JK'),
 ('2009-01-17', 'TPIA.JK'),
 ('2009-01-17', 'UNVR.JK'),
 ('2009-01-18', 'JECC.JK'),
 ('2009-01-18', 'TMAS.JK'),
 ('2009-01-18', 'TPIA.JK'),
 ('2009-01-18', 'UNVR.JK'),
 ('2009-01-19', 'JECC.JK'),
 ('2009-01-19', 'TMAS.JK'),
 ('2009-01-19', 'TPIA.JK'),
 ('2009-01-19', 'UNVR.JK'),
 ('2009-01-20', 'JECC.JK'),
 ('2009-01-20', 'TMAS.JK'),
 ('2009-01-20', 'TPIA.JK'),
 ('2009-01-20', 'UNVR.JK'),
 ('2009-01-21', 'JECC.JK'),
 ('2009-01-21', 'TMAS.JK'),
 ('2009-01-21', 'TPIA.JK'),
 ('2009-01-21', 'UNVR.JK'),
 ('2009-01-22', 'JECC.JK'),
 ('2009-01-22', 'TMAS.JK'),
 ('2009-01-22', 'TPIA.JK'),
 ('2009-01-22', 'UNVR.JK'),
 ('2009-01-23', 'JECC.JK'),
 ('2009-01-23', 'TMAS.JK'),
 ('2009-01-23', 'TPIA.JK'),
 ('2009-01-23', 'UNVR.JK'),
 ('2009-01-24', 'JECC.JK'),
 ('2009-01-24', 'TMAS.JK'),
 ('2009-01-24', 'TPIA.JK'),
 ('2009-01-24', 'UNVR.JK'),
 ('2009-01-25', 'JECC.JK'),
 ('2009-01-25', 'TMAS.JK'),
 ('2009-01-25', 'TPIA.JK'),
 ('2009-01-25', 'UNVR.JK'),
 ('2009-01-26', 'JECC.JK'),
 ('2009-01-26', 'TMAS.JK'),
 ('2009-01-26', 'TPIA.JK'),
 ('2009-01-26', 'UNVR.JK'),
 ('2009-01-27', 'JECC.JK'),
 ('2009-01-27', 'TMAS.JK'),
 ('2009-01-27', 'TPIA.JK'),
 ('2009-01-27', 'UNVR.JK'),
 ('2009-01-28', 'JECC.JK'),
 ('2009-01-28', 'TMAS.JK'),
 ('2009-01-28', 'TPIA.JK'),
 ('2009-01-28', 'UNVR.JK'),
 ('2009-01-29', 'JECC.JK'),
 ('2009-01-29', 'TMAS.JK'),
 ('2009-01-29', 'TPIA.JK'),
 ('2009-01-29', 'UNVR.JK'),
 ('2009-01-30', 'JECC.JK'),
 ('2009-01-30', 'TMAS.JK'),
 ('2009-01-30', 'TPIA.JK'),
 ('2009-01-30', 'UNVR.JK'),
 ('2009-01-31', 'JECC.JK'),
 ('2009-01-31', 'TMAS.JK'),
 ('2009-01-31', 'TPIA.JK'),
 ('2009-01-31', 'UNVR.JK'),
 ('2009-02-01', 'JECC.JK'),
 ('2009-02-01', 'TMAS.JK'),
 ('2009-02-01', 'TPIA.JK'),
 ('2009-02-01', 'UNVR.JK'),
 ('2009-02-02', 'JECC.JK'),
 ('2009-02-02', 'TMAS.JK'),
 ('2009-02-02', 'TPIA.JK'),
 ('2009-02-02', 'UNVR.JK'),
 ('2009-02-03', 'JECC.JK'),
 ('2009-02-03', 'TMAS.JK'),
 ('2009-02-03', 'TPIA.JK'),
 ('2009-02-03', 'UNVR.JK'),
 ('2009-02-04', 'JECC.JK'),
 ('2009-02-04', 'TMAS.JK'),
 ('2009-02-04', 'TPIA.JK'),
 ('2009-02-04', 'UNVR.JK'),
 ('2009-02-05', 'JECC.JK'),
 ('2009-02-05', 'TMAS.JK'),
 ('2009-02-05', 'TPIA.JK'),
 ('2009-02-05', 'UNVR.JK'),
 ('2009-02-06', 'JECC.JK'),
 ('2009-02-06', 'TMAS.JK'),
 ('2009-02-06', 'TPIA.JK'),
 ('2009-02-06', 'UNVR.JK'),
 ('2009-02-07', 'JECC.JK'),
 ('2009-02-07', 'TMAS.JK'),
 ('2009-02-07', 'TPIA.JK'),
 ('2009-02-07', 'UNVR.JK'),
 ('2009-02-08', 'JECC.JK'),
 ('2009-02-08', 'TMAS.JK'),
 ('2009-02-08', 'TPIA.JK'),
 ('2009-02-08', 'UNVR.JK'),
 ('2009-02-09', 'JECC.JK'),
 ('2009-02-09', 'TMAS.JK'),
 ('2009-02-09', 'TPIA.JK'),
 ('2009-02-09', 'UNVR.JK'),
 ('2009-02-10', 'JECC.JK'),
 ('2009-02-10', 'TMAS.JK'),
 ('2009-02-10', 'TPIA.JK'),
 ('2009-02-10', 'UNVR.JK'),
 ('2009-02-11', 'JECC.JK'),
 ('2009-02-11', 'TMAS.JK'),
 ('2009-02-11', 'TPIA.JK'),
 ('2009-02-11', 'UNVR.JK'),
 ('2009-02-12', 'JECC.JK'),
 ('2009-02-12', 'TMAS.JK'),
 ('2009-02-12', 'TPIA.JK'),
 ('2009-02-12', 'UNVR.JK'),
 ('2009-02-13', 'JECC.JK'),
 ('2009-02-13', 'TMAS.JK'),
 ('2009-02-13', 'TPIA.JK'),
 ('2009-02-13', 'UNVR.JK'),
 ('2009-02-14', 'JECC.JK'),
 ('2009-02-14', 'TMAS.JK'),
 ('2009-02-14', 'TPIA.JK'),
 ('2009-02-14', 'UNVR.JK'),
 ('2009-02-15', 'JECC.JK'),
 ('2009-02-15', 'TMAS.JK'),
 ('2009-02-15', 'TPIA.JK'),
 ('2009-02-15', 'UNVR.JK'),
 ('2009-02-16', 'JECC.JK'),
 ('2009-02-16', 'TMAS.JK'),
 ('2009-02-16', 'TPIA.JK'),
 ('2009-02-16', 'UNVR.JK'),
 ('2009-02-17', 'JECC.JK'),
 ('2009-02-17', 'TMAS.JK'),
 ('2009-02-17', 'TPIA.JK'),
 ('2009-02-17', 'UNVR.JK'),
 ('2009-02-18', 'JECC.JK'),
 ('2009-02-18', 'TMAS.JK'),
 ('2009-02-18', 'TPIA.JK'),
 ('2009-02-18', 'UNVR.JK'),
 ('2009-02-19', 'JECC.JK'),
 ('2009-02-19', 'TMAS.JK'),
 ('2009-02-19', 'TPIA.JK'),
 ('2009-02-19', 'UNVR.JK'),
 ('2009-02-20', 'JECC.JK'),
 ('2009-02-20', 'TMAS.JK'),
 ('2009-02-20', 'TPIA.JK'),
 ('2009-02-20', 'UNVR.JK'),
 ('2009-02-21', 'JECC.JK'),
 ('2009-02-21', 'TMAS.JK'),
 ('2009-02-21', 'TPIA.JK'),
 ('2009-02-21', 'UNVR.JK'),
 ('2009-02-22', 'JECC.JK'),
 ('2009-02-22', 'TMAS.JK'),
 ('2009-02-22', 'TPIA.JK'),
 ('2009-02-22', 'UNVR.JK'),
 ('2009-02-23', 'JECC.JK'),
 ('2009-02-23', 'TMAS.JK'),
 ('2009-02-23', 'TPIA.JK'),
 ('2009-02-23', 'UNVR.JK'),
 ('2009-02-24', 'JECC.JK'),
 ('2009-02-24', 'TMAS.JK'),
 ('2009-02-24', 'TPIA.JK'),
 ('2009-02-24', 'UNVR.JK'),
 ('2009-02-25', 'JECC.JK'),
 ('2009-02-25', 'TMAS.JK'),
 ('2009-02-25', 'TPIA.JK'),
 ('2009-02-25', 'UNVR.JK'),
 ('2009-02-26', 'JECC.JK'),
 ('2009-02-26', 'TMAS.JK'),
 ('2009-02-26', 'TPIA.JK'),
 ('2009-02-26', 'UNVR.JK'),
 ('2009-02-27', 'JECC.JK'),
 ('2009-02-27', 'TMAS.JK'),
 ('2009-02-27', 'TPIA.JK'),
 ('2009-02-27', 'UNVR.JK'),
 ('2009-02-28', 'JECC.JK'),
 ('2009-02-28', 'TMAS.JK'),
 ('2009-02-28', 'TPIA.JK'),
 ('2009-02-28', 'UNVR.JK'),
 ('2009-03-01', 'JECC.JK'),
 ('2009-03-01', 'TMAS.JK'),
 ('2009-03-01', 'TPIA.JK'),
 ('2009-03-01', 'UNVR.JK'),
 ('2009-03-02', 'JECC.JK'),
 ('2009-03-02', 'TMAS.JK'),
 ('2009-03-02', 'TPIA.JK'),
 ('2009-03-02', 'UNVR.JK'),
 ('2009-03-03', 'JECC.JK'),
 ('2009-03-03', 'TMAS.JK'),
 ('2009-03-03', 'TPIA.JK'),
 ('2009-03-03', 'UNVR.JK'),
 ('2009-03-04', 'JECC.JK'),
 ('2009-03-04', 'TMAS.JK'),
 ('2009-03-04', 'TPIA.JK'),
 ('2009-03-04', 'UNVR.JK'),
 ('2009-03-05', 'JECC.JK'),
 ('2009-03-05', 'TMAS.JK'),
 ('2009-03-05', 'TPIA.JK'),
 ('2009-03-05', 'UNVR.JK'),
 ('2009-03-06', 'JECC.JK'),
 ('2009-03-06', 'TMAS.JK'),
 ('2009-03-06', 'TPIA.JK'),
 ('2009-03-06', 'UNVR.JK'),
 ('2009-03-07', 'JECC.JK'),
 ('2009-03-07', 'TMAS.JK'),
 ('2009-03-07', 'TPIA.JK'),
 ('2009-03-07', 'UNVR.JK'),
 ('2009-03-08', 'JECC.JK'),
 ('2009-03-08', 'TMAS.JK'),
 ('2009-03-08', 'TPIA.JK'),
 ('2009-03-08', 'UNVR.JK'),
 ('2009-03-09', 'JECC.JK'),
 ('2009-03-09', 'TMAS.JK'),
 ('2009-03-09', 'TPIA.JK'),
 ('2009-03-09', 'UNVR.JK'),
 ('2009-03-10', 'JECC.JK'),
 ('2009-03-10', 'TMAS.JK'),
 ('2009-03-10', 'TPIA.JK'),
 ('2009-03-10', 'UNVR.JK'),
 ('2009-03-11', 'JECC.JK'),
 ('2009-03-11', 'TMAS.JK'),
 ('2009-03-11', 'TPIA.JK'),
 ('2009-03-11', 'UNVR.JK'),
 ('2009-03-12', 'JECC.JK'),
 ('2009-03-12', 'TMAS.JK'),
 ('2009-03-12', 'TPIA.JK'),
 ('2009-03-12', 'UNVR.JK'),
 ('2009-03-13', 'JECC.JK'),
 ('2009-03-13', 'TMAS.JK'),
 ('2009-03-13', 'TPIA.JK'),
 ('2009-03-13', 'UNVR.JK'),
 ('2009-03-14', 'JECC.JK'),
 ('2009-03-14', 'TMAS.JK'),
 ('2009-03-14', 'TPIA.JK'),
 ('2009-03-14', 'UNVR.JK'),
 ('2009-03-15', 'JECC.JK'),
 ('2009-03-15', 'TMAS.JK'),
 ('2009-03-15', 'TPIA.JK'),
 ('2009-03-15', 'UNVR.JK'),
 ('2009-03-16', 'JECC.JK'),
 ('2009-03-16', 'TMAS.JK'),
 ('2009-03-16', 'TPIA.JK'),
 ('2009-03-16', 'UNVR.JK'),
 ('2009-03-17', 'JECC.JK'),
 ('2009-03-17', 'TMAS.JK'),
 ('2009-03-17', 'TPIA.JK'),
 ('2009-03-17', 'UNVR.JK'),
 ('2009-03-18', 'JECC.JK'),
 ('2009-03-18', 'TMAS.JK'),
 ('2009-03-18', 'TPIA.JK'),
 ('2009-03-18', 'UNVR.JK'),
 ('2009-03-19', 'JECC.JK'),
 ('2009-03-19', 'TMAS.JK'),
 ('2009-03-19', 'TPIA.JK'),
 ('2009-03-19', 'UNVR.JK'),
 ('2009-03-20', 'JECC.JK'),
 ('2009-03-20', 'TMAS.JK'),
 ('2009-03-20', 'TPIA.JK'),
 ('2009-03-20', 'UNVR.JK'),
 ('2009-03-21', 'JECC.JK'),
 ('2009-03-21', 'TMAS.JK'),
 ('2009-03-21', 'TPIA.JK'),
 ('2009-03-21', 'UNVR.JK'),
 ('2009-03-22', 'JECC.JK'),
 ('2009-03-22', 'TMAS.JK'),
 ('2009-03-22', 'TPIA.JK'),
 ('2009-03-22', 'UNVR.JK'),
 ('2009-03-23', 'JECC.JK'),
 ('2009-03-23', 'TMAS.JK'),
 ('2009-03-23', 'TPIA.JK'),
 ('2009-03-23', 'UNVR.JK'),
 ('2009-03-24', 'JECC.JK'),
 ('2009-03-24', 'TMAS.JK'),
 ('2009-03-24', 'TPIA.JK'),
 ('2009-03-24', 'UNVR.JK'),
 ('2009-03-25', 'JECC.JK'),
 ('2009-03-25', 'TMAS.JK'),
 ('2009-03-25', 'TPIA.JK'),
 ('2009-03-25', 'UNVR.JK'),
 ('2009-03-26', 'JECC.JK'),
 ('2009-03-26', 'TMAS.JK'),
 ('2009-03-26', 'TPIA.JK'),
 ('2009-03-26', 'UNVR.JK'),
 ('2009-03-27', 'JECC.JK'),
 ('2009-03-27', 'TMAS.JK'),
 ('2009-03-27', 'TPIA.JK'),
 ('2009-03-27', 'UNVR.JK'),
 ('2009-03-28', 'JECC.JK'),
 ('2009-03-28', 'TMAS.JK'),
 ('2009-03-28', 'TPIA.JK'),
 ('2009-03-28', 'UNVR.JK'),
 ('2009-03-29', 'JECC.JK'),
 ('2009-03-29', 'TMAS.JK'),
 ('2009-03-29', 'TPIA.JK'),
 ('2009-03-29', 'UNVR.JK'),
 ('2009-03-30', 'JECC.JK'),
 ('2009-03-30', 'TMAS.JK'),
 ('2009-03-30', 'TPIA.JK'),
 ('2009-03-30', 'UNVR.JK'),
 ('2009-03-31', 'JECC.JK'),
 ('2009-03-31', 'TMAS.JK'),
 ('2009-03-31', 'TPIA.JK'),
 ('2009-03-31', 'UNVR.JK'),
 ('2009-04-01', 'JECC.JK'),
 ('2009-04-01', 'TMAS.JK'),
 ('2009-04-01', 'TPIA.JK'),
 ('2009-04-01', 'UNVR.JK'),
 ('2009-04-02', 'JECC.JK'),
 ('2009-04-02', 'TMAS.JK'),
 ('2009-04-02', 'TPIA.JK'),
 ('2009-04-02', 'UNVR.JK'),
 ('2009-04-03', 'JECC.JK'),
 ('2009-04-03', 'TMAS.JK'),
 ('2009-04-03', 'TPIA.JK'),
 ('2009-04-03', 'UNVR.JK'),
 ('2009-04-04', 'JECC.JK'),
 ('2009-04-04', 'TMAS.JK'),
 ('2009-04-04', 'TPIA.JK'),
 ('2009-04-04', 'UNVR.JK'),
 ('2009-04-05', 'JECC.JK'),
 ('2009-04-05', 'TMAS.JK'),
 ('2009-04-05', 'TPIA.JK'),
 ('2009-04-05', 'UNVR.JK'),
 ('2009-04-06', 'JECC.JK'),
 ('2009-04-06', 'TMAS.JK'),
 ('2009-04-06', 'TPIA.JK'),
 ('2009-04-06', 'UNVR.JK'),
 ('2009-04-07', 'JECC.JK'),
 ('2009-04-07', 'TMAS.JK'),
 ('2009-04-07', 'TPIA.JK'),
 ('2009-04-07', 'UNVR.JK'),
 ('2009-04-08', 'JECC.JK'),
 ('2009-04-08', 'TMAS.JK'),
 ('2009-04-08', 'TPIA.JK'),
 ('2009-04-08', 'UNVR.JK'),
 ('2009-04-09', 'JECC.JK'),
 ('2009-04-09', 'TMAS.JK'),
 ('2009-04-09', 'TPIA.JK'),
 ('2009-04-09', 'UNVR.JK'),
 ('2009-04-10', 'JECC.JK'),
 ('2009-04-10', 'TMAS.JK'),
 ('2009-04-10', 'TPIA.JK'),
 ('2009-04-10', 'UNVR.JK'),
 ('2009-04-11', 'JECC.JK'),
 ('2009-04-11', 'TMAS.JK'),
 ('2009-04-11', 'TPIA.JK'),
 ('2009-04-11', 'UNVR.JK'),
 ('2009-04-12', 'JECC.JK'),
 ('2009-04-12', 'TMAS.JK'),
 ('2009-04-12', 'TPIA.JK'),
 ('2009-04-12', 'UNVR.JK'),
 ('2009-04-13', 'JECC.JK'),
 ('2009-04-13', 'TMAS.JK'),
 ('2009-04-13', 'TPIA.JK'),
 ('2009-04-13', 'UNVR.JK'),
 ('2009-04-14', 'JECC.JK'),
 ('2009-04-14', 'TMAS.JK'),
 ('2009-04-14', 'TPIA.JK'),
 ('2009-04-14', 'UNVR.JK'),
 ('2009-04-15', 'JECC.JK'),
 ('2009-04-15', 'TMAS.JK'),
 ('2009-04-15', 'TPIA.JK'),
 ('2009-04-15', 'UNVR.JK'),
 ('2009-04-16', 'JECC.JK'),
 ('2009-04-16', 'TMAS.JK'),
 ('2009-04-16', 'TPIA.JK'),
 ('2009-04-16', 'UNVR.JK'),
 ('2009-04-17', 'JECC.JK'),
 ('2009-04-17', 'TMAS.JK'),
 ('2009-04-17', 'TPIA.JK'),
 ('2009-04-17', 'UNVR.JK'),
 ('2009-04-18', 'JECC.JK'),
 ('2009-04-18', 'TMAS.JK'),
 ('2009-04-18', 'TPIA.JK'),
 ('2009-04-18', 'UNVR.JK'),
 ('2009-04-19', 'JECC.JK'),
 ('2009-04-19', 'TMAS.JK'),
 ('2009-04-19', 'TPIA.JK'),
 ('2009-04-19', 'UNVR.JK'),
 ('2009-04-20', 'JECC.JK'),
 ('2009-04-20', 'TMAS.JK'),
 ('2009-04-20', 'TPIA.JK'),
 ('2009-04-20', 'UNVR.JK'),
 ('2009-04-21', 'JECC.JK'),
 ('2009-04-21', 'TMAS.JK'),
 ('2009-04-21', 'TPIA.JK'),
 ('2009-04-21', 'UNVR.JK'),
 ('2009-04-22', 'JECC.JK'),
 ('2009-04-22', 'TMAS.JK'),
 ('2009-04-22', 'TPIA.JK'),
 ('2009-04-22', 'UNVR.JK'),
 ('2009-04-23', 'JECC.JK'),
 ('2009-04-23', 'TMAS.JK'),
 ('2009-04-23', 'TPIA.JK'),
 ('2009-04-23', 'UNVR.JK'),
 ('2009-04-24', 'JECC.JK'),
 ('2009-04-24', 'TMAS.JK'),
 ('2009-04-24', 'TPIA.JK'),
 ('2009-04-24', 'UNVR.JK'),
 ('2009-04-25', 'JECC.JK'),
 ('2009-04-25', 'TMAS.JK'),
 ('2009-04-25', 'TPIA.JK'),
 ('2009-04-25', 'UNVR.JK'),
 ('2009-04-26', 'JECC.JK'),
 ('2009-04-26', 'TMAS.JK'),
 ('2009-04-26', 'TPIA.JK'),
 ('2009-04-26', 'UNVR.JK'),
 ('2009-04-27', 'JECC.JK'),
 ('2009-04-27', 'TMAS.JK'),
 ('2009-04-27', 'TPIA.JK'),
 ('2009-04-27', 'UNVR.JK'),
 ('2009-04-28', 'JECC.JK'),
 ('2009-04-28', 'TMAS.JK'),
 ('2009-04-28', 'TPIA.JK'),
 ('2009-04-28', 'UNVR.JK'),
 ('2009-04-29', 'JECC.JK'),
 ('2009-04-29', 'TMAS.JK'),
 ('2009-04-29', 'TPIA.JK'),
 ('2009-04-29', 'UNVR.JK'),
 ('2009-04-30', 'JECC.JK'),
 ('2009-04-30', 'TMAS.JK'),
 ('2009-04-30', 'TPIA.JK'),
 ('2009-04-30', 'UNVR.JK'),
 ('2009-05-01', 'JECC.JK'),
 ('2009-05-01', 'TMAS.JK'),
 ('2009-05-01', 'TPIA.JK'),
 ('2009-05-01', 'UNVR.JK'),
 ('2009-05-02', 'JECC.JK'),
 ('2009-05-02', 'TMAS.JK'),
 ('2009-05-02', 'TPIA.JK'),
 ('2009-05-02', 'UNVR.JK'),
 ('2009-05-03', 'JECC.JK'),
 ('2009-05-03', 'TMAS.JK'),
 ('2009-05-03', 'TPIA.JK'),
 ('2009-05-03', 'UNVR.JK'),
 ('2009-05-04', 'JECC.JK'),
 ('2009-05-04', 'TMAS.JK'),
 ('2009-05-04', 'TPIA.JK'),
 ('2009-05-04', 'UNVR.JK'),
 ('2009-05-05', 'JECC.JK'),
 ('2009-05-05', 'TMAS.JK'),
 ('2009-05-05', 'TPIA.JK'),
 ('2009-05-05', 'UNVR.JK'),
 ('2009-05-06', 'JECC.JK'),
 ('2009-05-06', 'TMAS.JK'),
 ('2009-05-06', 'TPIA.JK'),
 ('2009-05-06', 'UNVR.JK'),
 ('2009-05-07', 'JECC.JK'),
 ('2009-05-07', 'TMAS.JK'),
 ('2009-05-07', 'TPIA.JK'),
 ('2009-05-07', 'UNVR.JK'),
 ('2009-05-08', 'JECC.JK'),
 ('2009-05-08', 'TMAS.JK'),
 ('2009-05-08', 'TPIA.JK'),
 ('2009-05-08', 'UNVR.JK'),
 ('2009-05-09', 'JECC.JK'),
 ('2009-05-09', 'TMAS.JK'),
 ('2009-05-09', 'TPIA.JK'),
 ('2009-05-09', 'UNVR.JK'),
 ('2009-05-10', 'JECC.JK'),
 ('2009-05-10', 'TMAS.JK'),
 ('2009-05-10', 'TPIA.JK'),
 ('2009-05-10', 'UNVR.JK'),
 ('2009-05-11', 'JECC.JK'),
 ('2009-05-11', 'TMAS.JK'),
 ('2009-05-11', 'TPIA.JK'),
 ('2009-05-11', 'UNVR.JK'),
 ('2009-05-12', 'JECC.JK'),
 ('2009-05-12', 'TMAS.JK'),
 ('2009-05-12', 'TPIA.JK'),
 ('2009-05-12', 'UNVR.JK'),
 ('2009-05-13', 'JECC.JK'),
 ('2009-05-13', 'TMAS.JK'),
 ('2009-05-13', 'TPIA.JK'),
 ('2009-05-13', 'UNVR.JK'),
 ('2009-05-14', 'JECC.JK'),
 ('2009-05-14', 'TMAS.JK'),
 ('2009-05-14', 'TPIA.JK'),
 ('2009-05-14', 'UNVR.JK'),
 ('2009-05-15', 'JECC.JK'),
 ('2009-05-15', 'TMAS.JK'),
 ('2009-05-15', 'TPIA.JK'),
 ('2009-05-15', 'UNVR.JK'),
 ('2009-05-16', 'JECC.JK'),
 ('2009-05-16', 'TMAS.JK'),
 ('2009-05-16', 'TPIA.JK'),
 ('2009-05-16', 'UNVR.JK'),
 ('2009-05-17', 'JECC.JK'),
 ('2009-05-17', 'TMAS.JK'),
 ('2009-05-17', 'TPIA.JK'),
 ('2009-05-17', 'UNVR.JK'),
 ('2009-05-18', 'JECC.JK'),
 ('2009-05-18', 'TMAS.JK'),
 ('2009-05-18', 'TPIA.JK'),
 ('2009-05-18', 'UNVR.JK'),
 ('2009-05-19', 'JECC.JK'),
 ('2009-05-19', 'TMAS.JK'),
 ('2009-05-19', 'TPIA.JK'),
 ('2009-05-19', 'UNVR.JK'),
 ('2009-05-20', 'JECC.JK'),
 ('2009-05-20', 'TMAS.JK'),
 ('2009-05-20', 'TPIA.JK'),
 ('2009-05-20', 'UNVR.JK'),
 ('2009-05-21', 'JECC.JK'),
 ('2009-05-21', 'TMAS.JK'),
 ('2009-05-21', 'TPIA.JK'),
 ('2009-05-21', 'UNVR.JK'),
 ('2009-05-22', 'JECC.JK'),
 ('2009-05-22', 'TMAS.JK'),
 ('2009-05-22', 'TPIA.JK'),
 ('2009-05-22', 'UNVR.JK'),
 ('2009-05-23', 'JECC.JK'),
 ('2009-05-23', 'TMAS.JK'),
 ('2009-05-23', 'TPIA.JK'),
 ('2009-05-23', 'UNVR.JK'),
 ('2009-05-24', 'JECC.JK'),
 ('2009-05-24', 'TMAS.JK'),
 ('2009-05-24', 'TPIA.JK'),
 ('2009-05-24', 'UNVR.JK'),
 ('2009-05-25', 'JECC.JK'),
 ('2009-05-25', 'TMAS.JK'),
 ('2009-05-25', 'TPIA.JK'),
 ('2009-05-25', 'UNVR.JK'),
 ('2009-05-26', 'JECC.JK'),
 ('2009-05-26', 'TMAS.JK'),
 ('2009-05-26', 'TPIA.JK'),
 ('2009-05-26', 'UNVR.JK'),
 ('2009-05-27', 'JECC.JK'),
 ('2009-05-27', 'TMAS.JK'),
 ('2009-05-27', 'TPIA.JK'),
 ('2009-05-27', 'UNVR.JK'),
 ('2009-05-28', 'JECC.JK'),
 ('2009-05-28', 'TMAS.JK'),
 ('2009-05-28', 'TPIA.JK'),
 ('2009-05-28', 'UNVR.JK'),
 ('2009-05-29', 'JECC.JK'),
 ('2009-05-29', 'TMAS.JK'),
 ('2009-05-29', 'TPIA.JK'),
 ('2009-05-29', 'UNVR.JK'),
 ('2009-05-30', 'JECC.JK'),
 ('2009-05-30', 'TMAS.JK'),
 ('2009-05-30', 'TPIA.JK'),
 ('2009-05-30', 'UNVR.JK'),
 ('2009-05-31', 'JECC.JK'),
 ('2009-05-31', 'TMAS.JK'),
 ('2009-05-31', 'TPIA.JK'),
 ('2009-05-31', 'UNVR.JK'),
 ('2009-06-01', 'JECC.JK'),
 ('2009-06-01', 'TMAS.JK'),
 ('2009-06-01', 'TPIA.JK'),
 ('2009-06-01', 'UNVR.JK'),
 ('2009-06-02', 'JECC.JK'),
 ('2009-06-02', 'TMAS.JK'),
 ('2009-06-02', 'TPIA.JK'),
 ('2009-06-02', 'UNVR.JK'),
 ('2009-06-03', 'JECC.JK'),
 ('2009-06-03', 'TMAS.JK'),
 ('2009-06-03', 'TPIA.JK'),
 ('2009-06-03', 'UNVR.JK'),
 ('2009-06-04', 'JECC.JK'),
 ('2009-06-04', 'TMAS.JK'),
 ('2009-06-04', 'TPIA.JK'),
 ('2009-06-04', 'UNVR.JK'),
 ('2009-06-05', 'JECC.JK'),
 ('2009-06-05', 'TMAS.JK'),
 ('2009-06-05', 'TPIA.JK'),
 ('2009-06-05', 'UNVR.JK'),
 ('2009-06-06', 'JECC.JK'),
 ('2009-06-06', 'TMAS.JK'),
 ('2009-06-06', 'TPIA.JK'),
 ('2009-06-06', 'UNVR.JK'),
 ('2009-06-07', 'JECC.JK'),
 ('2009-06-07', 'TMAS.JK'),
 ('2009-06-07', 'TPIA.JK'),
 ('2009-06-07', 'UNVR.JK'),
 ('2009-06-08', 'JECC.JK'),
 ('2009-06-08', 'TMAS.JK'),
 ('2009-06-08', 'TPIA.JK'),
 ('2009-06-08', 'UNVR.JK'),
 ('2009-06-09', 'JECC.JK'),
 ('2009-06-09', 'TMAS.JK'),
 ('2009-06-09', 'TPIA.JK'),
 ('2009-06-09', 'UNVR.JK'),
 ('2009-06-10', 'JECC.JK'),
 ('2009-06-10', 'TMAS.JK'),
 ('2009-06-10', 'TPIA.JK'),
 ('2009-06-10', 'UNVR.JK'),
 ('2009-06-11', 'JECC.JK'),
 ('2009-06-11', 'TMAS.JK'),
 ('2009-06-11', 'TPIA.JK'),
 ('2009-06-11', 'UNVR.JK'),
 ('2009-06-12', 'JECC.JK'),
 ('2009-06-12', 'TMAS.JK'),
 ('2009-06-12', 'TPIA.JK'),
 ('2009-06-12', 'UNVR.JK'),
 ('2009-06-13', 'JECC.JK'),
 ('2009-06-13', 'TMAS.JK'),
 ('2009-06-13', 'TPIA.JK'),
 ('2009-06-13', 'UNVR.JK'),
 ('2009-06-14', 'JECC.JK'),
 ('2009-06-14', 'TMAS.JK'),
 ('2009-06-14', 'TPIA.JK'),
 ('2009-06-14', 'UNVR.JK'),
 ('2009-06-15', 'JECC.JK'),
 ('2009-06-15', 'TMAS.JK'),
 ('2009-06-15', 'TPIA.JK'),
 ('2009-06-15', 'UNVR.JK'),
 ('2009-06-16', 'JECC.JK'),
 ('2009-06-16', 'TMAS.JK'),
 ('2009-06-16', 'TPIA.JK'),
 ('2009-06-16', 'UNVR.JK'),
 ('2009-06-17', 'JECC.JK'),
 ('2009-06-17', 'TMAS.JK'),
 ('2009-06-17', 'TPIA.JK'),
 ('2009-06-17', 'UNVR.JK'),
 ('2009-06-18', 'JECC.JK'),
 ('2009-06-18', 'TMAS.JK'),
 ('2009-06-18', 'TPIA.JK'),
 ('2009-06-18', 'UNVR.JK'),
 ('2009-06-19', 'JECC.JK'),
 ('2009-06-19', 'TMAS.JK'),
 ('2009-06-19', 'TPIA.JK'),
 ('2009-06-19', 'UNVR.JK'),
 ('2009-06-20', 'JECC.JK'),
 ('2009-06-20', 'TMAS.JK'),
 ('2009-06-20', 'TPIA.JK'),
 ('2009-06-20', 'UNVR.JK'),
 ('2009-06-21', 'JECC.JK'),
 ('2009-06-21', 'TMAS.JK'),
 ('2009-06-21', 'TPIA.JK'),
 ('2009-06-21', 'UNVR.JK'),
 ('2009-06-22', 'JECC.JK'),
 ('2009-06-22', 'TMAS.JK'),
 ('2009-06-22', 'TPIA.JK'),
 ('2009-06-22', 'UNVR.JK'),
 ('2009-06-23', 'JECC.JK'),
 ('2009-06-23', 'TMAS.JK'),
 ('2009-06-23', 'TPIA.JK'),
 ('2009-06-23', 'UNVR.JK'),
 ('2009-06-24', 'JECC.JK'),
 ('2009-06-24', 'TMAS.JK'),
 ('2009-06-24', 'TPIA.JK'),
 ('2009-06-24', 'UNVR.JK'),
 ('2009-06-25', 'JECC.JK'),
 ('2009-06-25', 'TMAS.JK'),
 ('2009-06-25', 'TPIA.JK'),
 ('2009-06-25', 'UNVR.JK'),
 ('2009-06-26', 'JECC.JK'),
 ('2009-06-26', 'TMAS.JK'),
 ('2009-06-26', 'TPIA.JK'),
 ('2009-06-26', 'UNVR.JK'),
 ('2009-06-27', 'JECC.JK'),
 ('2009-06-27', 'TMAS.JK'),
 ('2009-06-27', 'TPIA.JK'),
 ('2009-06-27', 'UNVR.JK'),
 ('2009-06-28', 'JECC.JK'),
 ('2009-06-28', 'TMAS.JK'),
 ('2009-06-28', 'TPIA.JK'),
 ('2009-06-28', 'UNVR.JK'),
 ('2009-06-29', 'JECC.JK'),
 ('2009-06-29', 'TMAS.JK'),
 ('2009-06-29', 'TPIA.JK'),
 ('2009-06-29', 'UNVR.JK'),
 ('2009-06-30', 'JECC.JK'),
 ('2009-06-30', 'TMAS.JK'),
 ('2009-06-30', 'TPIA.JK'),
 ('2009-06-30', 'UNVR.JK'),
 ('2009-07-01', 'JECC.JK'),
 ('2009-07-01', 'TMAS.JK'),
 ('2009-07-01', 'TPIA.JK'),
 ('2009-07-01', 'UNVR.JK'),
 ('2009-07-02', 'JECC.JK'),
 ('2009-07-02', 'TMAS.JK'),

In [67]:
processed_full = pd.DataFrame(combination,columns=["date","tic"]).merge(processed,on=["date","tic"],how="left")
processed_full

,date,tic,open,high,low,close,volume,day,macd,rsi_30,cci_30,vix,turbulence
0,2009-01-05,JECC.JK,295.000000,295.000000,295.000000,198.915344,3.0,0.0,0.000000,0.000000,-66.666667,39.080002,0.000000
1,2009-01-05,TMAS.JK,46.000000,47.000000,44.000000,34.214245,775000.0,0.0,0.000000,0.000000,-66.666667,39.080002,0.000000
2,2009-01-05,TPIA.JK,82.948853,82.948853,82.948853,66.105316,0.0,0.0,0.000000,0.000000,-66.666667,39.080002,0.000000
3,2009-01-05,UNVR.JK,1620.000000,1620.000000,1560.000000,1149.686523,20.0,0.0,0.000000,0.000000,-66.666667,39.080002,0.000000
4,2009-01-06,JECC.JK,295.000000,295.000000,295.000000,198.915344,0.0,1.0,0.000000,0.000000,-66.666667,38.560001,0.000000
...,...,...,...,...,...,...,...,...,...,...,...,...,...
15995,2019-12-17,UNVR.JK,8180.000000,8225.000000,8180.000000,7612.015625,10837000.0,1.0,-70.835456,41.956723,-164.670487,12.290000,0.019866
15996,2019-12-18,JECC.JK,6175.000000,6175.000000,6175.000000,6175.000000,0.0,2.0,-2.741289,53.058014,-164.670487,12.580000,0.112172
15997,2019-12-18,TMAS.JK,98.000000,100.000000,98.000000,80.050919,2135700.0,2.0,-3.212768,38.307120,-74.912966,12.580000,0.112172
15998,2019-12-18,TPIA.JK,2487.500000,2500.000000,2481.250000,2471.146240,22134800.0,2.0,45.007680,64.526573,113.802453,12.580000,0.112172
15999,2019-12-18,UNVR.JK,8195.000000,8205.000000,8120.000000,7602.727051,15872500.0,2.0,-74.938453,41.772063,-169.670824,12.580000,0.112172

In [68]:
processed_full = processed_full[processed_full['date'].isin(processed['date'])]
processed_full

,date,tic,open,high,low,close,volume,day,macd,rsi_30,cci_30,vix,turbulence
0,2009-01-05,JECC.JK,295.000000,295.000000,295.000000,198.915344,3.0,0.0,0.000000,0.000000,-66.666667,39.080002,0.000000
1,2009-01-05,TMAS.JK,46.000000,47.000000,44.000000,34.214245,775000.0,0.0,0.000000,0.000000,-66.666667,39.080002,0.000000
2,2009-01-05,TPIA.JK,82.948853,82.948853,82.948853,66.105316,0.0,0.0,0.000000,0.000000,-66.666667,39.080002,0.000000
3,2009-01-05,UNVR.JK,1620.000000,1620.000000,1560.000000,1149.686523,20.0,0.0,0.000000,0.000000,-66.666667,39.080002,0.000000
4,2009-01-06,JECC.JK,295.000000,295.000000,295.000000,198.915344,0.0,1.0,0.000000,0.000000,-66.666667,38.560001,0.000000
...,...,...,...,...,...,...,...,...,...,...,...,...,...
15995,2019-12-17,UNVR.JK,8180.000000,8225.000000,8180.000000,7612.015625,10837000.0,1.0,-70.835456,41.956723,-164.670487,12.290000,0.019866
15996,2019-12-18,JECC.JK,6175.000000,6175.000000,6175.000000,6175.000000,0.0,2.0,-2.741289,53.058014,-164.670487,12.580000,0.112172
15997,2019-12-18,TMAS.JK,98.000000,100.000000,98.000000,80.050919,2135700.0,2.0,-3.212768,38.307120,-74.912966,12.580000,0.112172
15998,2019-12-18,TPIA.JK,2487.500000,2500.000000,2481.250000,2471.146240,22134800.0,2.0,45.007680,64.526573,113.802453,12.580000,0.112172
15999,2019-12-18,UNVR.JK,8195.000000,8205.000000,8120.000000,7602.727051,15872500.0,2.0,-74.938453,41.772063,-169.670824,12.580000,0.112172

In [69]:
processed_full = processed_full.sort_values(['date','tic'])
processed_full

,date,tic,open,high,low,close,volume,day,macd,rsi_30,cci_30,vix,turbulence
0,2009-01-05,JECC.JK,295.000000,295.000000,295.000000,198.915344,3.0,0.0,0.000000,0.000000,-66.666667,39.080002,0.000000
1,2009-01-05,TMAS.JK,46.000000,47.000000,44.000000,34.214245,775000.0,0.0,0.000000,0.000000,-66.666667,39.080002,0.000000
2,2009-01-05,TPIA.JK,82.948853,82.948853,82.948853,66.105316,0.0,0.0,0.000000,0.000000,-66.666667,39.080002,0.000000
3,2009-01-05,UNVR.JK,1620.000000,1620.000000,1560.000000,1149.686523,20.0,0.0,0.000000,0.000000,-66.666667,39.080002,0.000000
4,2009-01-06,JECC.JK,295.000000,295.000000,295.000000,198.915344,0.0,1.0,0.000000,0.000000,-66.666667,38.560001,0.000000
...,...,...,...,...,...,...,...,...,...,...,...,...,...
15995,2019-12-17,UNVR.JK,8180.000000,8225.000000,8180.000000,7612.015625,10837000.0,1.0,-70.835456,41.956723,-164.670487,12.290000,0.019866
15996,2019-12-18,JECC.JK,6175.000000,6175.000000,6175.000000,6175.000000,0.0,2.0,-2.741289,53.058014,-164.670487,12.580000,0.112172
15997,2019-12-18,TMAS.JK,98.000000,100.000000,98.000000,80.050919,2135700.0,2.0,-3.212768,38.307120,-74.912966,12.580000,0.112172
15998,2019-12-18,TPIA.JK,2487.500000,2500.000000,2481.250000,2471.146240,22134800.0,2.0,45.007680,64.526573,113.802453,12.580000,0.112172
15999,2019-12-18,UNVR.JK,8195.000000,8205.000000,8120.000000,7602.727051,15872500.0,2.0,-74.938453,41.772063,-169.670824,12.580000,0.112172

In [70]:
processed_full = processed_full.fillna(0)
processed_full

,date,tic,open,high,low,close,volume,day,macd,rsi_30,cci_30,vix,turbulence
0,2009-01-05,JECC.JK,295.000000,295.000000,295.000000,198.915344,3.0,0.0,0.000000,0.000000,-66.666667,39.080002,0.000000
1,2009-01-05,TMAS.JK,46.000000,47.000000,44.000000,34.214245,775000.0,0.0,0.000000,0.000000,-66.666667,39.080002,0.000000
2,2009-01-05,TPIA.JK,82.948853,82.948853,82.948853,66.105316,0.0,0.0,0.000000,0.000000,-66.666667,39.080002,0.000000
3,2009-01-05,UNVR.JK,1620.000000,1620.000000,1560.000000,1149.686523,20.0,0.0,0.000000,0.000000,-66.666667,39.080002,0.000000
4,2009-01-06,JECC.JK,295.000000,295.000000,295.000000,198.915344,0.0,1.0,0.000000,0.000000,-66.666667,38.560001,0.000000
...,...,...,...,...,...,...,...,...,...,...,...,...,...
15995,2019-12-17,UNVR.JK,8180.000000,8225.000000,8180.000000,7612.015625,10837000.0,1.0,-70.835456,41.956723,-164.670487,12.290000,0.019866
15996,2019-12-18,JECC.JK,6175.000000,6175.000000,6175.000000,6175.000000,0.0,2.0,-2.741289,53.058014,-164.670487,12.580000,0.112172
15997,2019-12-18,TMAS.JK,98.000000,100.000000,98.000000,80.050919,2135700.0,2.0,-3.212768,38.307120,-74.912966,12.580000,0.112172
15998,2019-12-18,TPIA.JK,2487.500000,2500.000000,2481.250000,2471.146240,22134800.0,2.0,45.007680,64.526573,113.802453,12.580000,0.112172
15999,2019-12-18,UNVR.JK,8195.000000,8205.000000,8120.000000,7602.727051,15872500.0,2.0,-74.938453,41.772063,-169.670824,12.580000,0.112172

In [71]:
processed_full.sort_values(['date','tic'],ignore_index=True).head(10)

,date,tic,open,high,low,close,volume,day,macd,rsi_30,cci_30,vix,turbulence
0,2009-01-05,JECC.JK,295.000000,295.000000,295.000000,198.915344,3.0,0.0,0.000000,0.0,-66.666667,39.080002,0.0
1,2009-01-05,TMAS.JK,46.000000,47.000000,44.000000,34.214245,775000.0,0.0,0.000000,0.0,-66.666667,39.080002,0.0
2,2009-01-05,TPIA.JK,82.948853,82.948853,82.948853,66.105316,0.0,0.0,0.000000,0.0,-66.666667,39.080002,0.0
3,2009-01-05,UNVR.JK,1620.000000,1620.000000,1560.000000,1149.686523,20.0,0.0,0.000000,0.0,-66.666667,39.080002,0.0
4,2009-01-06,JECC.JK,295.000000,295.000000,295.000000,198.915344,0.0,1.0,0.000000,0.0,-66.666667,38.560001,0.0
5,2009-01-06,TMAS.JK,46.000000,47.000000,44.000000,33.470459,1107500.0,1.0,-0.016688,0.0,-66.666667,38.560001,0.0
6,2009-01-06,TPIA.JK,82.948853,82.948853,82.948853,66.105316,0.0,1.0,0.000000,0.0,-66.666667,38.560001,0.0
7,2009-01-06,UNVR.JK,1620.000000,1670.000000,1600.000000,1163.880005,16432500.0,1.0,0.318443,100.0,66.666667,38.560001,0.0
8,2009-01-07,JECC.JK,270.000000,270.000000,270.000000,182.058121,10000.0,2.0,-0.522741,0.0,-100.000000,43.389999,0.0
9,2009-01-07,TMAS.JK,44.000000,48.000000,44.000000,32.726669,1765000.0,2.0,-0.044328,0.0,-18.789383,43.389999,0.0

In [72]:
processed_full.nunique()

date           2652
tic               4
open           2044
high           2054
low            2085
close          3333
volume         5270
day               5
macd          10592
rsi_30         7226
cci_30        10168
vix            1441
turbulence     2399
dtype: int64

In [73]:
#memperbarui dataframe dengan bentuk harga per lot

processed_full_lot = processed_full[['open','high','low','close']].mul(100)

#drop some columns
processed_full_noOHLC = processed_full.drop(['open','high','low','close'], axis=1)
  
processed_full_lot = pd.concat([processed_full_noOHLC, processed_full_lot], axis=1)

processed_full_lot = processed_full_lot[['date', 'tic', 'open', 'high', 'low', 'close', 'volume', 'day', 'macd', 'rsi_30', 'cci_30', 'vix', 'turbulence']]

processed_full_lot

,date,tic,open,high,low,close,volume,day,macd,rsi_30,cci_30,vix,turbulence
0,2009-01-05,JECC.JK,29500.000000,29500.000000,29500.000000,19891.534424,3.0,0.0,0.000000,0.000000,-66.666667,39.080002,0.000000
1,2009-01-05,TMAS.JK,4600.000000,4700.000000,4400.000000,3421.424484,775000.0,0.0,0.000000,0.000000,-66.666667,39.080002,0.000000
2,2009-01-05,TPIA.JK,8294.885254,8294.885254,8294.885254,6610.531616,0.0,0.0,0.000000,0.000000,-66.666667,39.080002,0.000000
3,2009-01-05,UNVR.JK,162000.000000,162000.000000,156000.000000,114968.652344,20.0,0.0,0.000000,0.000000,-66.666667,39.080002,0.000000
4,2009-01-06,JECC.JK,29500.000000,29500.000000,29500.000000,19891.534424,0.0,1.0,0.000000,0.000000,-66.666667,38.560001,0.000000
...,...,...,...,...,...,...,...,...,...,...,...,...,...
15995,2019-12-17,UNVR.JK,818000.000000,822500.000000,818000.000000,761201.562500,10837000.0,1.0,-70.835456,41.956723,-164.670487,12.290000,0.019866
15996,2019-12-18,JECC.JK,617500.000000,617500.000000,617500.000000,617500.000000,0.0,2.0,-2.741289,53.058014,-164.670487,12.580000,0.112172
15997,2019-12-18,TMAS.JK,9800.000000,10000.000000,9800.000000,8005.091858,2135700.0,2.0,-3.212768,38.307120,-74.912966,12.580000,0.112172
15998,2019-12-18,TPIA.JK,248750.000000,250000.000000,248125.000000,247114.624023,22134800.0,2.0,45.007680,64.526573,113.802453,12.580000,0.112172
15999,2019-12-18,UNVR.JK,819500.000000,820500.000000,812000.000000,760272.705078,15872500.0,2.0,-74.938453,41.772063,-169.670824,12.580000,0.112172

<a id='4'></a>
# Bagian 5. Membangun Lingkungan Jual-Beli Saham dengan OpenAI Gym-style
Proses *training* meliputi mengamati perubahan harga saham, mengambil tindakan dan perhitungan *reward*. Dengan berinteraksi dengan lingkungan pasar, agen pada akhirnya akan memperoleh strategi perdagangan yang dapat memaksimalkan imbalan.

*Environment* pasar dibangun  menggunakan OpenAI Gym yang mensimulasikan pasar saham dengan data historis pasar.

<a id='4.1'></a>
## 5.1. Memisahkan Data
Data dibagi menjadi dua bagian, yaitu bagian pelatihan dan bagian pengujian dengan keterangan sebagai berikut:

Periode data pelatihan: 2009-01-01 hingga 2017-12-31

Periode data perdagangan: 2018-01-01 hingga 2022-08-15

In [74]:
train = data_split(processed_full_lot, TRAIN_START_DATE,TRAIN_END_DATE)
trade = data_split(processed_full_lot, TRADE_START_DATE,TRADE_END_DATE)
print(len(train))
print(len(trade))

8628
1980

In [75]:
train.tail()

,date,tic,open,high,low,close,volume,day,macd,rsi_30,cci_30,vix,turbulence
2155,2017-12-28,UNVR.JK,1083000.0,1088000.0,1061000.0,962059.082031,14564500.0,3.0,222.473482,67.975785,120.659972,10.18,5.395510
2156,2017-12-29,JECC.JK,470000.0,470000.0,470000.0,434712.109375,100.0,4.0,-45.023809,43.469840,-56.271744,11.04,15.259179
2156,2017-12-29,TMAS.JK,22800.0,22900.0,22800.0,18516.827393,3500.0,4.0,-1.871567,48.538844,-32.664573,11.04,15.259179
2156,2017-12-29,TPIA.JK,143125.0,150000.0,141875.0,146239.025879,24246800.0,4.0,12.320735,63.029749,167.268737,11.04,15.259179
2156,2017-12-29,UNVR.JK,1088000.0,1119500.0,1087500.0,988586.328125,12763000.0,4.0,243.419107,72.053433,162.612752,11.04,15.259179

In [76]:
trade.head()

,date,tic,open,high,low,close,volume,day,macd,rsi_30,cci_30,vix,turbulence
0,2018-01-02,JECC.JK,470000.0,470000.0,470000.0,434712.109375,0.0,1.0,-41.005663,43.469840,-55.959358,9.77,6.604075
0,2018-01-02,TMAS.JK,22900.0,22900.0,21800.0,17627.372742,16500.0,1.0,-2.067100,43.270811,-110.403816,9.77,6.604075
0,2018-01-02,TPIA.JK,150625.0,150625.0,143750.0,144411.035156,22387200.0,1.0,19.810006,60.719805,142.844451,9.77,6.604075
0,2018-01-02,UNVR.JK,1123500.0,1162000.0,1100000.0,988144.238281,12108500.0,1.0,264.457196,71.890179,158.326562,9.77,6.604075
1,2018-01-03,JECC.JK,470000.0,470000.0,470000.0,434712.109375,0.0,2.0,-38.939904,43.469840,-55.648295,9.15,24.801770

In [77]:
stock_dimension = len(train.tic.unique())
state_space = 1 + 2*stock_dimension + len(INDICATORS)*stock_dimension
print(f"Stock Dimension: {stock_dimension}, State Space: {state_space}")

Stock Dimension: 4, State Space: 21

In [78]:
buy_cost_list = [0.0023] * stock_dimension
sell_cost_list = [0.0054] * stock_dimension
num_stock_shares = [0] * stock_dimension

env_kwargs = {
    "hmax": 100,
    "initial_amount": 100000000,
    "num_stock_shares": num_stock_shares,
    "buy_cost_pct": buy_cost_list,
    "sell_cost_pct": sell_cost_list,
    "state_space": state_space,
    "stock_dim": stock_dimension,
    "tech_indicator_list": INDICATORS,
    "action_space": stock_dimension,
    "reward_scaling": 1e-4
}


e_train_gym = StockTradingEnv(df = train, **env_kwargs)

<a id='4.2'></a>
## 5.2. Lingkungan untuk Pelatihan *(Training)*

In [79]:
env_train, _ = e_train_gym.get_sb_env()
print(type(env_train))

<class 'stable_baselines3.common.vec_env.dummy_vec_env.DummyVecEnv'>

<a id='5'></a>
# Bagian 6: Melatih Agen DRL
* Algoritma DRL dibangun dengan menggunakan **Stable Baselines 3**. 

* FinRL mencakup algoritma DRL standar yang disempurnakan, seperti DQN, DDPG, DDPG Multi-Agen, PPO, SAC, A2C, dan TD3. FinRL juga mengizinkan pengguna untuk merancang algoritma DRL sendiri dengan mengadaptasi algoritma DRL yang telah disebutkan.

In [80]:
agent = DRLAgent(env = env_train)

**Agent Training: 5 algorithms (A2C, PPO, TD3, SAC, DDPG)**

<a id='5.1'></a>
##6.1. Agen 1: A2C

In [81]:
A2C_PARAMS = {
    "n_steps": 150, 
    "ent_coef": 0.0001, 
    "learning_rate": 0.0014,
}
model_a2c = agent.get_model("a2c",model_kwargs = A2C_PARAMS)

{'n_steps': 150, 'ent_coef': 0.0001, 'learning_rate': 0.0014}
Using cuda device

In [82]:
trained_a2c = agent.train_model(model=model_a2c, 
                             tb_log_name='a2c',
                             total_timesteps=50000)

--------------------------------------
| time/                 |            |
|    fps                | 342        |
|    iterations         | 100        |
|    time_elapsed       | 43         |
|    total_timesteps    | 15000      |
| train/                |            |
|    entropy_loss       | -5.62      |
|    explained_variance | -3.58e-06  |
|    learning_rate      | 0.0014     |
|    n_updates          | 99         |
|    policy_loss        | 7.49e+04   |
|    reward             | -204.71495 |
|    std                | 0.987      |
|    value_loss         | 2.37e+08   |
--------------------------------------
day: 2156, episode: 10
begin_total_asset: 100000000.00
end_total_asset: 103872546.59
total_reward: 3872546.59
total_cost: 76659546.75
total_trades: 5993
Sharpe: 0.244
=================================
-------------------------------------
| time/                 |           |
|    fps                | 343       |
|    iterations         | 200       |
|    time_elapsed       | 87        |
|    total_timesteps    | 30000     |
| train/                |           |
|    entropy_loss       | -5.61     |
|    explained_variance | 1.85e-05  |
|    learning_rate      | 0.0014    |
|    n_updates          | 199       |
|    policy_loss        | 2.18e+04  |
|    reward             | 132.39287 |
|    std                | 0.983     |
|    value_loss         | 1.59e+07  |
-------------------------------------
day: 2156, episode: 20
begin_total_asset: 100000000.00
end_total_asset: 917367299.35
total_reward: 817367299.35
total_cost: 70961532.54
total_trades: 5228
Sharpe: 0.850
=================================
--------------------------------------
| time/                 |            |
|    fps                | 342        |
|    iterations         | 300        |
|    time_elapsed       | 131        |
|    total_timesteps    | 45000      |
| train/                |            |
|    entropy_loss       | -5.61      |
|    explained_variance | -3.68e-05  |
|    learning_rate      | 0.0014     |
|    n_updates          | 299        |
|    policy_loss        | 2.55e+04   |
|    reward             | -175.66205 |
|    std                | 0.985      |
|    value_loss         | 2.34e+07   |
--------------------------------------

<a id='5.2'></a>
##6.2. Agen 2: PPO

In [83]:
PPO_PARAMS = {
    "n_steps": 50000,
    "ent_coef": 0.7,
    "learning_rate": 0.0016,
    "batch_size": 1750,
}
model_ppo = agent.get_model("ppo",model_kwargs = PPO_PARAMS)

{'n_steps': 50000, 'ent_coef': 0.7, 'learning_rate': 0.0016, 'batch_size': 1750}
Using cuda device

/usr/local/lib/python3.7/dist-packages/stable_baselines3/ppo/ppo.py:147: UserWarning: You have specified a mini-batch size of 1750, but because the `RolloutBuffer` is of size `n_steps * n_envs = 50000`, after every 28 untruncated mini-batches, there will be a truncated mini-batch of size 1000
We recommend using a `batch_size` that is a factor of `n_steps * n_envs`.
Info: (n_steps=50000 and n_envs=1)
  f"You have specified a mini-batch size of {batch_size},"

In [84]:
trained_ppo = agent.train_model(model=model_ppo, 
                             tb_log_name='ppo',
                             total_timesteps=50000)

day: 2156, episode: 30
begin_total_asset: 100000000.00
end_total_asset: 27236048.28
total_reward: -72763951.72
total_cost: 125502591.40
total_trades: 7575
Sharpe: -0.333
=================================
day: 2156, episode: 40
begin_total_asset: 100000000.00
end_total_asset: 19325899.51
total_reward: -80674100.49
total_cost: 116169373.74
total_trades: 7541
Sharpe: -0.535
=================================
------------------------------------
| time/              |             |
|    fps             | 346         |
|    iterations      | 1           |
|    time_elapsed    | 144         |
|    total_timesteps | 50000       |
| train/             |             |
|    reward          | 0.026022337 |
------------------------------------

<a id='5.3'></a>
##6.3. Agen 3: TD3

In [85]:
TD3_PARAMS = {
    "batch_size": 7000, 
    "buffer_size": 10000, 
    "learning_rate": 0.9  
}
model_td3 = agent.get_model("td3",model_kwargs = TD3_PARAMS)

{'batch_size': 7000, 'buffer_size': 10000, 'learning_rate': 0.9}
Using cuda device

In [86]:
trained_td3 = agent.train_model(model=model_td3, 
                             tb_log_name='td3',
                             total_timesteps=50000)

day: 2156, episode: 50
begin_total_asset: 100000000.00
end_total_asset: 464850969.75
total_reward: 364850969.75
total_cost: 2989856.66
total_trades: 4218
Sharpe: 0.610
=================================
----------------------------------
| time/              |           |
|    episodes        | 4         |
|    fps             | 83        |
|    time_elapsed    | 103       |
|    total_timesteps | 8628      |
| train/             |           |
|    actor_loss      | 1.21e+09  |
|    critic_loss     | 5.79e+18  |
|    learning_rate   | 0.9       |
|    n_updates       | 6471      |
|    reward          | 10.610898 |
----------------------------------
----------------------------------
| time/              |           |
|    episodes        | 8         |
|    fps             | 73        |
|    time_elapsed    | 235       |
|    total_timesteps | 17256     |
| train/             |           |
|    actor_loss      | 7.98e+08  |
|    critic_loss     | 5.52e+17  |
|    learning_rate   | 0.9       |
|    n_updates       | 15099     |
|    reward          | 10.610898 |
----------------------------------
day: 2156, episode: 60
begin_total_asset: 100000000.00
end_total_asset: 465061265.79
total_reward: 365061265.79
total_cost: 234098.54
total_trades: 4061
Sharpe: 0.598
=================================
----------------------------------
| time/              |           |
|    episodes        | 12        |
|    fps             | 70        |
|    time_elapsed    | 367       |
|    total_timesteps | 25884     |
| train/             |           |
|    actor_loss      | 6.32e+08  |
|    critic_loss     | 3.11e+17  |
|    learning_rate   | 0.9       |
|    n_updates       | 23727     |
|    reward          | 10.610898 |
----------------------------------
----------------------------------
| time/              |           |
|    episodes        | 16        |
|    fps             | 69        |
|    time_elapsed    | 498       |
|    total_timesteps | 34512     |
| train/             |           |
|    actor_loss      | 5.89e+08  |
|    critic_loss     | 1.66e+17  |
|    learning_rate   | 0.9       |
|    n_updates       | 32355     |
|    reward          | 10.610898 |
----------------------------------
----------------------------------
| time/              |           |
|    episodes        | 20        |
|    fps             | 68        |
|    time_elapsed    | 630       |
|    total_timesteps | 43140     |
| train/             |           |
|    actor_loss      | 4.56e+08  |
|    critic_loss     | 9.71e+16  |
|    learning_rate   | 0.9       |
|    n_updates       | 40983     |
|    reward          | 10.610898 |
----------------------------------
day: 2156, episode: 70
begin_total_asset: 100000000.00
end_total_asset: 465061265.79
total_reward: 365061265.79
total_cost: 234098.54
total_trades: 4061
Sharpe: 0.598
=================================
----------------------------------
| time/              |           |
|    episodes        | 24        |
|    fps             | 67        |
|    time_elapsed    | 762       |
|    total_timesteps | 51768     |
| train/             |           |
|    actor_loss      | 3.38e+08  |
|    critic_loss     | 4.84e+16  |
|    learning_rate   | 0.9       |
|    n_updates       | 49611     |
|    reward          | 10.610898 |
----------------------------------

<a id='5.4'></a>
##6.4. Agen 4: SAC

In [87]:
SAC_PARAMS = {
    "ent_coef": 1.25,
    "learning_rate": 0.0001,
    "batch_size": 4000,
    "buffer_size": 5000,
    "learning_starts": 14,
    
}
model_sac = agent.get_model("sac",model_kwargs = SAC_PARAMS)

{'ent_coef': 1.25, 'learning_rate': 0.0001, 'batch_size': 4000, 'buffer_size': 5000, 'learning_starts': 14}
Using cuda device

In [88]:
trained_sac = agent.train_model(model=model_sac, 
                             tb_log_name='sac',
                             total_timesteps=30000)

-----------------------------------
| time/              |            |
|    episodes        | 4          |
|    fps             | 58         |
|    time_elapsed    | 147        |
|    total_timesteps | 8628       |
| train/             |            |
|    actor_loss      | 1.71e+04   |
|    critic_loss     | 2.01e+06   |
|    ent_coef        | 1.25       |
|    learning_rate   | 0.0001     |
|    n_updates       | 8613       |
|    reward          | 0.73119384 |
-----------------------------------
day: 2156, episode: 80
begin_total_asset: 100000000.00
end_total_asset: 1497732454.41
total_reward: 1397732454.41
total_cost: 229465.33
total_trades: 4277
Sharpe: 0.799
=================================
-----------------------------------
| time/              |            |
|    episodes        | 8          |
|    fps             | 58         |
|    time_elapsed    | 294        |
|    total_timesteps | 17256      |
| train/             |            |
|    actor_loss      | 1.37e+04   |
|    critic_loss     | 1.61e+06   |
|    ent_coef        | 1.25       |
|    learning_rate   | 0.0001     |
|    n_updates       | 17241      |
|    reward          | 0.73119384 |
-----------------------------------
-----------------------------------
| time/              |            |
|    episodes        | 12         |
|    fps             | 58         |
|    time_elapsed    | 441        |
|    total_timesteps | 25884      |
| train/             |            |
|    actor_loss      | 1.21e+04   |
|    critic_loss     | 1.57e+06   |
|    ent_coef        | 1.25       |
|    learning_rate   | 0.0001     |
|    n_updates       | 25869      |
|    reward          | 0.73119384 |
-----------------------------------

<a id='5.5'></a>
##6.5. Agen 5: DDPG

In [89]:
DDPG_PARAMS = {
    "batch_size": 1250, 
    "buffer_size": 50000, 
    "learning_rate": 0.0003
}
model_ddpg = agent.get_model("ddpg",model_kwargs = DDPG_PARAMS)

{'batch_size': 1250, 'buffer_size': 50000, 'learning_rate': 0.0003}
Using cuda device

In [90]:
trained_ddpg = agent.train_model(model=model_ddpg, 
                             tb_log_name='ddpg',
                             total_timesteps=60000)

day: 2156, episode: 90
begin_total_asset: 100000000.00
end_total_asset: 100065609.16
total_reward: 65609.16
total_cost: 229472.14
total_trades: 8624
Sharpe: 0.452
=================================
----------------------------------
| time/              |           |
|    episodes        | 4         |
|    fps             | 111       |
|    time_elapsed    | 77        |
|    total_timesteps | 8628      |
| train/             |           |
|    actor_loss      | -1.44e+04 |
|    critic_loss     | 2.76e+07  |
|    learning_rate   | 0.0003    |
|    n_updates       | 6471      |
|    reward          | 271.122   |
----------------------------------
----------------------------------
| time/              |           |
|    episodes        | 8         |
|    fps             | 99        |
|    time_elapsed    | 172       |
|    total_timesteps | 17256     |
| train/             |           |
|    actor_loss      | -9.89e+03 |
|    critic_loss     | 2.91e+05  |
|    learning_rate   | 0.0003    |
|    n_updates       | 15099     |
|    reward          | 271.122   |
----------------------------------
day: 2156, episode: 100
begin_total_asset: 100000000.00
end_total_asset: 100065609.16
total_reward: 65609.16
total_cost: 229472.14
total_trades: 8624
Sharpe: 0.452
=================================
----------------------------------
| time/              |           |
|    episodes        | 12        |
|    fps             | 96        |
|    time_elapsed    | 269       |
|    total_timesteps | 25884     |
| train/             |           |
|    actor_loss      | -6.29e+03 |
|    critic_loss     | 5.8e+04   |
|    learning_rate   | 0.0003    |
|    n_updates       | 23727     |
|    reward          | 271.122   |
----------------------------------
----------------------------------
| time/              |           |
|    episodes        | 16        |
|    fps             | 94        |
|    time_elapsed    | 366       |
|    total_timesteps | 34512     |
| train/             |           |
|    actor_loss      | -3.88e+03 |
|    critic_loss     | 2.63e+04  |
|    learning_rate   | 0.0003    |
|    n_updates       | 32355     |
|    reward          | 271.122   |
----------------------------------
---------------------------------
| time/              |          |
|    episodes        | 20       |
|    fps             | 92       |
|    time_elapsed    | 464      |
|    total_timesteps | 43140    |
| train/             |          |
|    actor_loss      | -2.6e+03 |
|    critic_loss     | 4.33e+04 |
|    learning_rate   | 0.0003   |
|    n_updates       | 40983    |
|    reward          | 271.122  |
---------------------------------
day: 2156, episode: 110
begin_total_asset: 100000000.00
end_total_asset: 100065609.16
total_reward: 65609.16
total_cost: 229472.14
total_trades: 8624
Sharpe: 0.452
=================================
----------------------------------
| time/              |           |
|    episodes        | 24        |
|    fps             | 92        |
|    time_elapsed    | 561       |
|    total_timesteps | 51768     |
| train/             |           |
|    actor_loss      | -1.81e+03 |
|    critic_loss     | 4.18e+04  |
|    learning_rate   | 0.0003    |
|    n_updates       | 49611     |
|    reward          | 271.122   |
----------------------------------
----------------------------------
| time/              |           |
|    episodes        | 28        |
|    fps             | 91        |
|    time_elapsed    | 659       |
|    total_timesteps | 60396     |
| train/             |           |
|    actor_loss      | -1.35e+03 |
|    critic_loss     | 3.59e+04  |
|    learning_rate   | 0.0003    |
|    n_updates       | 58239     |
|    reward          | 271.122   |
----------------------------------

<a id='6'></a>
# Bagian 7: Melakukan Jual-Beli

<a id='6.1'></a>
## 7.1. Performa di Dalam Sampel

Asumsikan modal awal adalah Rp100.000.000.

In [91]:
data_risk_indicator = processed_full_lot[(processed_full_lot.date<TRAIN_END_DATE) & (processed_full_lot.date>=TRAIN_START_DATE)]
insample_risk_indicator = data_risk_indicator.drop_duplicates(subset=['date'])

In [92]:
insample_risk_indicator.vix.describe()

count    2157.000000
mean       18.666583
std         7.813415
min         9.140000
25%        13.370000
50%        16.299999
75%        21.540001
max        56.650002
Name: vix, dtype: float64

In [93]:
insample_risk_indicator.vix.quantile(0.996)

48.84047967529307

In [94]:
insample_risk_indicator.turbulence.describe()

count    2157.000000
mean        3.855361
std        11.346048
min         0.000000
25%         0.269241
50%         1.242765
75%         3.754844
max       306.793334
Name: turbulence, dtype: float64

In [95]:
insample_risk_indicator.turbulence.quantile(0.996)

50.3035776258692

<a id='6.2'></a>
##7.2. Performa di Luar Sampel

FinRL dapat diatur dengan cara melakukan pelatihan ulang secara berkala, misalnya, pelatihan ulang setiap tiga bulan, bulanan, atau mingguan. 

Pada notebook ini, *hyperparameter* hanya diatur satu kali dengan menggunakan data sampel selama periode yang telah ditetapkan. Sehingga, terjadi beberapa peluruhan alfa seiring dengan perpanjangan tanggal perdagangan.

Banyak *hyperparameter* – mis. learning rate, mempengaruhi proses pembelajaran dan biasanya ditentukan dengan menguji beberapa variasi.

In [96]:
e_trade_gym = StockTradingEnv(df = trade, turbulence_threshold = 70, risk_indicator_col='vix', **env_kwargs)
# env_trade, obs_trade = e_trade_gym.get_sb_env()

<a id='6.3'></a>
##7.3. Hasil Jual-Beli Untuk Setiap Agen Berupa Rangkuman Aksi

<a id='6.3.1'></a>
###7.3.1. Agen 1: A2C

In [97]:
df_account_value_a2c, df_actions_a2c = DRLAgent.DRL_prediction(
    model=trained_a2c, 
    environment = e_trade_gym)

hit end!

<a id='6.3.2'></a>
###7.3.2. Agen 2: PPO

In [98]:
df_account_value_ppo, df_actions_ppo = DRLAgent.DRL_prediction(
    model=trained_ppo, 
    environment = e_trade_gym)

hit end!

<a id='6.3.3'></a>
###7.3.3. Agen 3: TD3

In [99]:
df_account_value_td3, df_actions_td3 = DRLAgent.DRL_prediction(
    model=trained_td3, 
    environment = e_trade_gym)

hit end!

<a id='6.3.4'></a>
###7.3.4. Agen 4: SAC

In [100]:
df_account_value_sac, df_actions_sac = DRLAgent.DRL_prediction(
    model=trained_sac, 
    environment = e_trade_gym)

hit end!

<a id='6.3.5'></a>
###7.3.5. Agen 5: DDPG

In [101]:
df_account_value_ddpg, df_actions_ddpg = DRLAgent.DRL_prediction(
    model=trained_ddpg, 
    environment = e_trade_gym)

hit end!

<a id='7'></a>
# Bagian 8: Performa Backtesting
Backtesting memiliki peran kunci dalam mengevaluasi kinerja strategi perdagangan. Alat backtesting otomatis lebih disukai karena dapat meminimalisir kesalahan manusia. Backtesting dapat dilakukan dengan menggunakan paket Quantopian pyfolio untuk menguji strategi perdagangan pada notebook ini. Backtesting tersebut mudah digunakan dan terdiri dari berbagai plot yang memberikan gambaran komprehensif tentang kinerja strategi perdagangan.

<a id='7.1'></a>
## 8.1 Status BackTesting

###8.1.1 Agen A2C

In [102]:
print("===========Get Backtest Results of A2C Model===========")
now = datetime.datetime.now().strftime('%Y%m%d-%Hh%M')

perf_stats_all = backtest_stats(account_value=df_account_value_a2c)
perf_stats_all = pd.DataFrame(perf_stats_all)
perf_stats_all.to_csv("./"+RESULTS_DIR+"/perf_stats_all_a2c_"+now+'.csv')

===========Get Backtest Results of A2C Model===========
Annual return         -0.124408
Cumulative returns    -0.229692
Annual volatility      0.251214
Sharpe ratio          -0.404528
Calmar ratio          -0.434676
Stability              0.152806
Max drawdown          -0.286208
Omega ratio            0.930481
Sortino ratio         -0.572422
Skew                        NaN
Kurtosis                    NaN
Tail ratio             0.998757
Daily value at risk   -0.032053
dtype: float64

###8.1.2 Agen ppo

In [103]:
print("===========Get Backtest Results of PPO Model===========")
now = datetime.datetime.now().strftime('%Y%m%d-%Hh%M')

perf_stats_all = backtest_stats(account_value=df_account_value_ppo)
perf_stats_all = pd.DataFrame(perf_stats_all)
perf_stats_all.to_csv("./"+RESULTS_DIR+"/perf_stats_all_ppo_"+now+'.csv')

===========Get Backtest Results of PPO Model===========
Annual return         -0.116688
Cumulative returns    -0.216295
Annual volatility      0.244956
Sharpe ratio          -0.385272
Calmar ratio          -0.411253
Stability              0.200279
Max drawdown          -0.283738
Omega ratio            0.933652
Sortino ratio         -0.543646
Skew                        NaN
Kurtosis                    NaN
Tail ratio             1.007505
Daily value at risk   -0.031236
dtype: float64

###8.1.3 Agen TD3

In [104]:
print("===========Get Backtest Results of TD3 Model===========")
now = datetime.datetime.now().strftime('%Y%m%d-%Hh%M')

perf_stats_all = backtest_stats(account_value=df_account_value_td3)
perf_stats_all = pd.DataFrame(perf_stats_all)
perf_stats_all.to_csv("./"+RESULTS_DIR+"/perf_stats_all_td3_"+now+'.csv')

===========Get Backtest Results of TD3 Model===========
Annual return         -0.306208
Cumulative returns    -0.512327
Annual volatility      0.481405
Sharpe ratio          -0.518228
Calmar ratio          -0.591946
Stability              0.819913
Max drawdown          -0.517291
Omega ratio            0.865783
Sortino ratio         -0.734926
Skew                        NaN
Kurtosis                    NaN
Tail ratio             1.028698
Daily value at risk   -0.061641
dtype: float64

###8.1.4 Agen SAC

In [105]:
print("===========Get Backtest Results of SAC Model===========")
now = datetime.datetime.now().strftime('%Y%m%d-%Hh%M')

perf_stats_all = backtest_stats(account_value=df_account_value_sac)
perf_stats_all = pd.DataFrame(perf_stats_all)
perf_stats_all.to_csv("./"+RESULTS_DIR+"/perf_stats_all_sac_"+now+'.csv')

===========Get Backtest Results of SAC Model===========
Annual return          0.194316
Cumulative returns     0.417373
Annual volatility      0.446174
Sharpe ratio           0.616164
Calmar ratio           0.518426
Stability              0.240051
Max drawdown          -0.374819
Omega ratio            1.406742
Sortino ratio          1.054708
Skew                        NaN
Kurtosis                    NaN
Tail ratio             0.008034
Daily value at risk   -0.055122
dtype: float64

###8.1.5 Agen DDPG

In [106]:
print("===========Get Backtest Results of DDPG Model===========")
now = datetime.datetime.now().strftime('%Y%m%d-%Hh%M')

perf_stats_all = backtest_stats(account_value=df_account_value_ddpg)
perf_stats_all = pd.DataFrame(perf_stats_all)
perf_stats_all.to_csv("./"+RESULTS_DIR+"/perf_stats_all_ddpg_"+now+'.csv')

===========Get Backtest Results of DDPG Model===========
Annual return         -0.121400
Cumulative returns    -0.224485
Annual volatility      0.251315
Sharpe ratio          -0.390572
Calmar ratio          -0.421647
Stability              0.131372
Max drawdown          -0.287918
Omega ratio            0.932848
Sortino ratio         -0.550884
Skew                        NaN
Kurtosis                    NaN
Tail ratio             0.999961
Daily value at risk   -0.032052
dtype: float64

###8.1.6. Baseline Stats

In [107]:
#baseline stats
print("===========Get Baseline Stats===========")
baseline_df = get_baseline(
        ticker="^JKII", 
        start = df_account_value_a2c.loc[0,'date'],
        end = df_account_value_a2c.loc[len(df_account_value_a2c)-1,'date'])

stats = backtest_stats(baseline_df, value_col_name = 'close')

===========Get Baseline Stats===========
[*********************100%***********************]  1 of 1 completed
Shape of DataFrame:  (478, 8)
Annual return         -0.041972
Cumulative returns    -0.078113
Annual volatility      0.185511
Sharpe ratio          -0.138819
Calmar ratio          -0.175216
Stability              0.093175
Max drawdown          -0.239543
Omega ratio            0.977818
Sortino ratio         -0.189296
Skew                        NaN
Kurtosis                    NaN
Tail ratio             0.900451
Daily value at risk   -0.023474
dtype: float64