<a href="https://colab.research.google.com/github/shintaroudlotulhanafia/DRLforMultipleStocksTradingUsingFinRL/blob/main/FractionsTest3/3_22_fraksi5_TugasAkhirS1_Shinta_DRLforMultipleStocksTradingUsingFinRL.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Notebook ini dijalankan menggunakan email shintafiaa@gmail.com

# Deep Reinforcement Learning untuk Jual-Beli Saham (Dari Awal): Jual-beli Banyak Saham 

* **Pytorch Version**

# Daftar Isi:

* [1. Pendeskrisian Tugas](#0)
* [2. Instalasi Paket Python](#1)
    * [2.1. Instalasi Paket](#1.1)    
    * [2.2. Daftar Paket Python](#1.2)
    * [2.3. Impot Paket](#1.3)
    * [2.4. Membuat Folder](#1.4)
* [3. Mengunduh Data](#2)
* [4. Memproses Data](#3)        
    * [4.1. IndiKator Teknikal](#3.1)
    * [4.2. Melakukan *Feature Engineering*](#3.2)
* [5. Membangun Lingkungan Jual-Beli Saham dengan OpenAI Gym-style](#4)  
    * [5.1. Pemisahan Data](#4.1)  
    * [5.2. Lingkungan untuk Pelatihan *(Training)*](#4.2)    
* [6. Melatih Agen DRL](#5)
    * [6.1. Agen 1: A2C](#5.1)
    * [6.2. Agen 2: PPO](#5.2)
    * [6.3. Agen 3: TD3](#5.3)
    * [6.4. Agen 4: SAC](#5.4)
    * [6.5. Agen 5: DDPG](#5.5)
* [7. Melakukan Jual-Beli](#6)
    * [7.1. Performa di Dalam Sampel](#6.1)
    * [7.2. Performa di Luar Sampel](#6.2)
    * [7.3. Hasil Jual-Beli Untuk Setiap Agen Berupa Rangkuman Aksi](#6.3)
      * [7.3.1. Agen 1: A2C](#6.3.1)
      * [7.3.2. Agen 2: PPO](#6.3.2)
      * [7.3.3. Agen 3: TD3](#6.3.3)
      * [7.3.4. Agen 4: SAC](#6.3.4)
      * [7.3.5. Agen 5: DDPG](#6.3.5)
* [8. Performa Backtesting](#7)  
    * [8.1. Status BackTesting](#7.1)
    * [8.2. Gambaran BackTesting](#7.2)

<a id='0'></a>
# Bagian 1. Pendeskrisian Tugas

Agen DRL dilatih untuk melakukan jual-beli saham. Tugas tersebut dimodelkan sebagai Markov Decision Process (MDP), dengan fungsi dan tujuannya adalah memaksimalkan pengembalian pengembalian kumulatif *(cummulative return)* yang diharapkan.

Definisi state-action-reward pada algoritam DRL kasus kali ini adalah sebagai berikut:

* **State s**: Kondisi atau *state* mewakili persepsi agen tentang lingkungan pasar. Sama seperti *trader* manusia yang menganalisis berbagai informasi, agen juga secara pasif mengamati banyak fitur dan belajar dengan cara berinteraksi dengan lingkungan pasar (biasanya dengan menjalankan ulang data historis).

* **Tindakan atau *action* a**: Ruang aksi mencakup aksi atau tindakan yang dapat dilakukan agen di setiap status atau kondisi. Misalnya, a {−1, 0, 1}, -1 berarti menjual, 0 berarti menahan, dan 1 berarti membeli. Ketika suatu aksi mengoperasikan beberapa saham, maka, a {−k, ..., 1, 0, 1, ..., k}. Misalnya, "Beli
10 saham TLKM" atau "Jual 10 saham TLKM" maka masing-masing nilai a adalah 10 atau -10.

* **Fungsi *reward* atau imbalan r(s, a, s′)**: *Reward* adalah insentif bagi agen untuk mempelajari kebijakan yang lebih baik. Misalnya *reward* dapat berupa perubahan nilai portofolio saat mengambil a pada keadaan s dan tiba pada keadaan baru s', yaitu, r(s, a, s′) = v′-v, v′ mewakili nilai portofolio pada keadaan s′ dan v mewakili nilai portofolio pada keadaan s.

* **Environment atau lingkungan jual-beli**: saham penyusun indeks JII dengan tanggal sesuai periode pengujian yang diatur.


Data untuk studi kasus ini diperoleh dari Yahoo Finance API. Data berisi harga *Open-High-Low-Close* dan *Volume*.

<a id='1'></a>
# Bagian 2. Instalasi Paket Python

<a id='1.1'></a>
## 2.1. Instalasi Paket

In [1]:
# install finrl library
!pip install git+https://github.com/shintaroudlotulhanafia/FinRL.git

Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/
Collecting git+https://github.com/shintaroudlotulhanafia/FinRL.git
  Cloning https://github.com/shintaroudlotulhanafia/FinRL.git to /tmp/pip-req-build-qzmxdrol
  Running command git clone -q https://github.com/shintaroudlotulhanafia/FinRL.git /tmp/pip-req-build-qzmxdrol
Collecting pyfolio@ git+https://github.com/quantopian/pyfolio.git#egg=pyfolio-0.9.2
  Cloning https://github.com/quantopian/pyfolio.git to /tmp/pip-install-iirq79yc/pyfolio_79bc5ef5a8cd4af88b65630696470aa0
  Running command git clone -q https://github.com/quantopian/pyfolio.git /tmp/pip-install-iirq79yc/pyfolio_79bc5ef5a8cd4af88b65630696470aa0
Collecting elegantrl@ git+https://github.com/AI4Finance-Foundation/ElegantRL.git#egg=elegantrl
  Cloning https://github.com/AI4Finance-Foundation/ElegantRL.git to /tmp/pip-install-iirq79yc/elegantrl_aac9096580f7432aa738dcc9036cbec0
  Running command git clone -q https://github.com/AI4Finance-Foundation/ElegantRL.git /tmp/pip-install-iirq79yc/elegantrl_aac9096580f7432aa738dcc9036cbec0
Collecting alpaca_trade_api>=2.1.0
  Downloading alpaca_trade_api-2.3.0-py3-none-any.whl (33 kB)
Collecting ccxt==1.66.32
  Downloading ccxt-1.66.32-py2.py3-none-any.whl (2.3 MB)
     |████████████████████████████████| 2.3 MB 12.8 MB/s
Collecting elegantrl
  Downloading elegantrl-0.3.3-py3-none-any.whl (234 kB)
     |████████████████████████████████| 234 kB 58.7 MB/s
Collecting exchange_calendars
  Downloading exchange_calendars-3.6.3.tar.gz (152 kB)
     |████████████████████████████████| 152 kB 83.0 MB/s
Collecting gputil
  Downloading GPUtil-1.4.0.tar.gz (5.5 kB)
Requirement already satisfied: gym>=0.17 in /usr/local/lib/python3.7/dist-packages (from finrl==0.3.5) (0.25.2)
Collecting jqdatasdk
  Downloading jqdatasdk-1.8.10-py3-none-any.whl (153 kB)
     |████████████████████████████████| 153 kB 63.2 MB/s
Collecting lz4
  Downloading lz4-4.0.2-cp37-cp37m-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (1.2 MB)
     |████████████████████████████████| 1.2 MB 71.4 MB/s
Requirement already satisfied: matplotlib in /usr/local/lib/python3.7/dist-packages (from finrl==0.3.5) (3.2.2)
Requirement already satisfied: numpy>=1.17.3 in /usr/local/lib/python3.7/dist-packages (from finrl==0.3.5) (1.21.6)
Requirement already satisfied: pandas>=1.1.5 in /usr/local/lib/python3.7/dist-packages (from finrl==0.3.5) (1.3.5)
Collecting pre-commit
  Downloading pre_commit-2.20.0-py2.py3-none-any.whl (199 kB)
     |████████████████████████████████| 199 kB 70.4 MB/s
Requirement already satisfied: pytest in /usr/local/lib/python3.7/dist-packages (from finrl==0.3.5) (3.6.4)
Collecting ray[default]
  Downloading ray-2.0.0-cp37-cp37m-manylinux2014_x86_64.whl (59.4 MB)
     |████████████████████████████████| 59.4 MB 1.2 MB/s
Requirement already satisfied: scikit-learn>=0.21.0 in /usr/local/lib/python3.7/dist-packages (from finrl==0.3.5) (1.0.2)
Collecting setuptools==59.5.0
  Downloading setuptools-59.5.0-py3-none-any.whl (952 kB)
     |████████████████████████████████| 952 kB 87.6 MB/s
Collecting stable-baselines3[extra]
  Downloading stable_baselines3-1.6.0-py3-none-any.whl (177 kB)
     |████████████████████████████████| 177 kB 107.1 MB/s
Collecting stockstats>=0.4.0
  Downloading stockstats-0.4.1-py2.py3-none-any.whl (19 kB)
Collecting tensorboardX
  Downloading tensorboardX-2.5.1-py2.py3-none-any.whl (125 kB)
     |████████████████████████████████| 125 kB 63.8 MB/s
Requirement already satisfied: wheel>=0.33.6 in /usr/local/lib/python3.7/dist-packages (from finrl==0.3.5) (0.37.1)
Collecting wrds
  Downloading wrds-3.1.2-py3-none-any.whl (13 kB)
Collecting yfinance
  Downloading yfinance-0.1.74-py2.py3-none-any.whl (27 kB)
Collecting pybullet
  Downloading pybullet-3.2.5-cp37-cp37m-manylinux_2_5_x86_64.manylinux1_x86_64.whl (91.7 MB)
     |████████████████████████████████| 91.7 MB 74.8 MB/s
Requirement already satisfied: torch in /usr/local/lib/python3.7/dist-packages (from elegantrl@ git+https://github.com/AI4Finance-Foundation/ElegantRL.git#egg=elegantrl->finrl==0.3.5) (1.12.1+cu113)
Requirement already satisfied: opencv-python in /usr/local/lib/python3.7/dist-packages (from elegantrl@ git+https://github.com/AI4Finance-Foundation/ElegantRL.git#egg=elegantrl->finrl==0.3.5) (4.6.0.66)
Collecting box2d-py
  Downloading box2d_py-2.3.8-cp37-cp37m-manylinux1_x86_64.whl (448 kB)
     |████████████████████████████████| 448 kB 78.6 MB/s
Requirement already satisfied: ipython>=3.2.3 in /usr/local/lib/python3.7/dist-packages (from pyfolio@ git+https://github.com/quantopian/pyfolio.git#egg=pyfolio-0.9.2->finrl==0.3.5) (7.9.0)
Requirement already satisfied: pytz>=2014.10 in /usr/local/lib/python3.7/dist-packages (from pyfolio@ git+https://github.com/quantopian/pyfolio.git#egg=pyfolio-0.9.2->finrl==0.3.5) (2022.2.1)
Requirement already satisfied: scipy>=0.14.0 in /usr/local/lib/python3.7/dist-packages (from pyfolio@ git+https://github.com/quantopian/pyfolio.git#egg=pyfolio-0.9.2->finrl==0.3.5) (1.7.3)
Requirement already satisfied: seaborn>=0.7.1 in /usr/local/lib/python3.7/dist-packages (from pyfolio@ git+https://github.com/quantopian/pyfolio.git#egg=pyfolio-0.9.2->finrl==0.3.5) (0.11.2)
Collecting empyrical>=0.5.0
  Downloading empyrical-0.5.5.tar.gz (52 kB)
     |████████████████████████████████| 52 kB 1.6 MB/s
Requirement already satisfied: aiohttp>=3.8 in /usr/local/lib/python3.7/dist-packages (from ccxt==1.66.32->finrl==0.3.5) (3.8.1)
Collecting yarl==1.7.2
  Downloading yarl-1.7.2-cp37-cp37m-manylinux_2_5_x86_64.manylinux1_x86_64.manylinux_2_12_x86_64.manylinux2010_x86_64.whl (271 kB)
     |████████████████████████████████| 271 kB 93.1 MB/s
Collecting aiodns>=1.1.1
  Downloading aiodns-3.0.0-py3-none-any.whl (5.0 kB)
Collecting cryptography>=2.6.1
  Downloading cryptography-37.0.4-cp36-abi3-manylinux_2_24_x86_64.whl (4.1 MB)
     |████████████████████████████████| 4.1 MB 87.1 MB/s
Requirement already satisfied: certifi>=2018.1.18 in /usr/local/lib/python3.7/dist-packages (from ccxt==1.66.32->finrl==0.3.5) (2022.6.15)
Requirement already satisfied: requests>=2.18.4 in /usr/local/lib/python3.7/dist-packages (from ccxt==1.66.32->finrl==0.3.5) (2.23.0)
Requirement already satisfied: multidict>=4.0 in /usr/local/lib/python3.7/dist-packages (from yarl==1.7.2->ccxt==1.66.32->finrl==0.3.5) (6.0.2)
Requirement already satisfied: idna>=2.0 in /usr/local/lib/python3.7/dist-packages (from yarl==1.7.2->ccxt==1.66.32->finrl==0.3.5) (2.10)
Requirement already satisfied: typing-extensions>=3.7.4 in /usr/local/lib/python3.7/dist-packages (from yarl==1.7.2->ccxt==1.66.32->finrl==0.3.5) (4.1.1)
Collecting pycares>=4.0.0
  Downloading pycares-4.2.2-cp37-cp37m-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (288 kB)
     |████████████████████████████████| 288 kB 92.0 MB/s
Requirement already satisfied: asynctest==0.13.0 in /usr/local/lib/python3.7/dist-packages (from aiohttp>=3.8->ccxt==1.66.32->finrl==0.3.5) (0.13.0)
Requirement already satisfied: async-timeout<5.0,>=4.0.0a3 in /usr/local/lib/python3.7/dist-packages (from aiohttp>=3.8->ccxt==1.66.32->finrl==0.3.5) (4.0.2)
Requirement already satisfied: aiosignal>=1.1.2 in /usr/local/lib/python3.7/dist-packages (from aiohttp>=3.8->ccxt==1.66.32->finrl==0.3.5) (1.2.0)
Requirement already satisfied: frozenlist>=1.1.1 in /usr/local/lib/python3.7/dist-packages (from aiohttp>=3.8->ccxt==1.66.32->finrl==0.3.5) (1.3.1)
Requirement already satisfied: charset-normalizer<3.0,>=2.0 in /usr/local/lib/python3.7/dist-packages (from aiohttp>=3.8->ccxt==1.66.32->finrl==0.3.5) (2.1.1)
Requirement already satisfied: attrs>=17.3.0 in /usr/local/lib/python3.7/dist-packages (from aiohttp>=3.8->ccxt==1.66.32->finrl==0.3.5) (22.1.0)
Requirement already satisfied: urllib3<2,>1.24 in /usr/local/lib/python3.7/dist-packages (from alpaca_trade_api>=2.1.0->finrl==0.3.5) (1.24.3)
Collecting msgpack==1.0.3
  Downloading msgpack-1.0.3-cp37-cp37m-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (299 kB)
     |████████████████████████████████| 299 kB 94.6 MB/s
Collecting websockets<11,>=9.0
  Downloading websockets-10.3-cp37-cp37m-manylinux_2_5_x86_64.manylinux1_x86_64.manylinux_2_12_x86_64.manylinux2010_x86_64.whl (112 kB)
     |████████████████████████████████| 112 kB 99.4 MB/s
Collecting deprecation==2.1.0
  Downloading deprecation-2.1.0-py2.py3-none-any.whl (11 kB)
Requirement already satisfied: PyYAML==6.0 in /usr/local/lib/python3.7/dist-packages (from alpaca_trade_api>=2.1.0->finrl==0.3.5) (6.0)
Collecting websocket-client<2,>=0.56.0
  Downloading websocket_client-1.4.1-py3-none-any.whl (55 kB)
     |████████████████████████████████| 55 kB 4.4 MB/s
Requirement already satisfied: packaging in /usr/local/lib/python3.7/dist-packages (from deprecation==2.1.0->alpaca_trade_api>=2.1.0->finrl==0.3.5) (21.3)
Requirement already satisfied: cffi>=1.12 in /usr/local/lib/python3.7/dist-packages (from cryptography>=2.6.1->ccxt==1.66.32->finrl==0.3.5) (1.15.1)
Requirement already satisfied: pycparser in /usr/local/lib/python3.7/dist-packages (from cffi>=1.12->cryptography>=2.6.1->ccxt==1.66.32->finrl==0.3.5) (2.21)
Requirement already satisfied: pandas-datareader>=0.2 in /usr/local/lib/python3.7/dist-packages (from empyrical>=0.5.0->pyfolio@ git+https://github.com/quantopian/pyfolio.git#egg=pyfolio-0.9.2->finrl==0.3.5) (0.9.0)
Requirement already satisfied: cloudpickle>=1.2.0 in /usr/local/lib/python3.7/dist-packages (from gym>=0.17->finrl==0.3.5) (1.5.0)
Requirement already satisfied: importlib-metadata>=4.8.0 in /usr/local/lib/python3.7/dist-packages (from gym>=0.17->finrl==0.3.5) (4.12.0)
Requirement already satisfied: gym-notices>=0.0.4 in /usr/local/lib/python3.7/dist-packages (from gym>=0.17->finrl==0.3.5) (0.0.8)
Requirement already satisfied: zipp>=0.5 in /usr/local/lib/python3.7/dist-packages (from importlib-metadata>=4.8.0->gym>=0.17->finrl==0.3.5) (3.8.1)
Requirement already satisfied: backcall in /usr/local/lib/python3.7/dist-packages (from ipython>=3.2.3->pyfolio@ git+https://github.com/quantopian/pyfolio.git#egg=pyfolio-0.9.2->finrl==0.3.5) (0.2.0)
Requirement already satisfied: pickleshare in /usr/local/lib/python3.7/dist-packages (from ipython>=3.2.3->pyfolio@ git+https://github.com/quantopian/pyfolio.git#egg=pyfolio-0.9.2->finrl==0.3.5) (0.7.5)
Collecting jedi>=0.10
  Downloading jedi-0.18.1-py2.py3-none-any.whl (1.6 MB)
     |████████████████████████████████| 1.6 MB 66.7 MB/s
Requirement already satisfied: decorator in /usr/local/lib/python3.7/dist-packages (from ipython>=3.2.3->pyfolio@ git+https://github.com/quantopian/pyfolio.git#egg=pyfolio-0.9.2->finrl==0.3.5) (4.4.2)
Requirement already satisfied: pexpect in /usr/local/lib/python3.7/dist-packages (from ipython>=3.2.3->pyfolio@ git+https://github.com/quantopian/pyfolio.git#egg=pyfolio-0.9.2->finrl==0.3.5) (4.8.0)
Requirement already satisfied: traitlets>=4.2 in /usr/local/lib/python3.7/dist-packages (from ipython>=3.2.3->pyfolio@ git+https://github.com/quantopian/pyfolio.git#egg=pyfolio-0.9.2->finrl==0.3.5) (5.1.1)
Requirement already satisfied: pygments in /usr/local/lib/python3.7/dist-packages (from ipython>=3.2.3->pyfolio@ git+https://github.com/quantopian/pyfolio.git#egg=pyfolio-0.9.2->finrl==0.3.5) (2.6.1)
Requirement already satisfied: prompt-toolkit<2.1.0,>=2.0.0 in /usr/local/lib/python3.7/dist-packages (from ipython>=3.2.3->pyfolio@ git+https://github.com/quantopian/pyfolio.git#egg=pyfolio-0.9.2->finrl==0.3.5) (2.0.10)
Requirement already satisfied: parso<0.9.0,>=0.8.0 in /usr/local/lib/python3.7/dist-packages (from jedi>=0.10->ipython>=3.2.3->pyfolio@ git+https://github.com/quantopian/pyfolio.git#egg=pyfolio-0.9.2->finrl==0.3.5) (0.8.3)
Requirement already satisfied: kiwisolver>=1.0.1 in /usr/local/lib/python3.7/dist-packages (from matplotlib->finrl==0.3.5) (1.4.4)
Requirement already satisfied: cycler>=0.10 in /usr/local/lib/python3.7/dist-packages (from matplotlib->finrl==0.3.5) (0.11.0)
Requirement already satisfied: python-dateutil>=2.1 in /usr/local/lib/python3.7/dist-packages (from matplotlib->finrl==0.3.5) (2.8.2)
Requirement already satisfied: pyparsing!=2.0.4,!=2.1.2,!=2.1.6,>=2.0.1 in /usr/local/lib/python3.7/dist-packages (from matplotlib->finrl==0.3.5) (3.0.9)
Requirement already satisfied: lxml in /usr/local/lib/python3.7/dist-packages (from pandas-datareader>=0.2->empyrical>=0.5.0->pyfolio@ git+https://github.com/quantopian/pyfolio.git#egg=pyfolio-0.9.2->finrl==0.3.5) (4.9.1)
Requirement already satisfied: wcwidth in /usr/local/lib/python3.7/dist-packages (from prompt-toolkit<2.1.0,>=2.0.0->ipython>=3.2.3->pyfolio@ git+https://github.com/quantopian/pyfolio.git#egg=pyfolio-0.9.2->finrl==0.3.5) (0.2.5)
Requirement already satisfied: six>=1.9.0 in /usr/local/lib/python3.7/dist-packages (from prompt-toolkit<2.1.0,>=2.0.0->ipython>=3.2.3->pyfolio@ git+https://github.com/quantopian/pyfolio.git#egg=pyfolio-0.9.2->finrl==0.3.5) (1.15.0)
Requirement already satisfied: chardet<4,>=3.0.2 in /usr/local/lib/python3.7/dist-packages (from requests>=2.18.4->ccxt==1.66.32->finrl==0.3.5) (3.0.4)
Requirement already satisfied: joblib>=0.11 in /usr/local/lib/python3.7/dist-packages (from scikit-learn>=0.21.0->finrl==0.3.5) (1.1.0)
Requirement already satisfied: threadpoolctl>=2.0.0 in /usr/local/lib/python3.7/dist-packages (from scikit-learn>=0.21.0->finrl==0.3.5) (3.1.0)
Collecting pyluach
  Downloading pyluach-2.0.1-py3-none-any.whl (22 kB)
Requirement already satisfied: toolz in /usr/local/lib/python3.7/dist-packages (from exchange_calendars->finrl==0.3.5) (0.12.0)
Requirement already satisfied: korean_lunar_calendar in /usr/local/lib/python3.7/dist-packages (from exchange_calendars->finrl==0.3.5) (0.2.1)
Collecting thriftpy2>=0.3.9
  Downloading thriftpy2-0.4.14.tar.gz (361 kB)
     |████████████████████████████████| 361 kB 67.7 MB/s
Requirement already satisfied: SQLAlchemy>=1.2.8 in /usr/local/lib/python3.7/dist-packages (from jqdatasdk->finrl==0.3.5) (1.4.40)
Collecting pymysql>=0.7.6
  Downloading PyMySQL-1.0.2-py3-none-any.whl (43 kB)
     |████████████████████████████████| 43 kB 2.7 MB/s
Requirement already satisfied: greenlet!=0.4.17 in /usr/local/lib/python3.7/dist-packages (from SQLAlchemy>=1.2.8->jqdatasdk->finrl==0.3.5) (1.1.3)
Collecting ply<4.0,>=3.4
  Downloading ply-3.11-py2.py3-none-any.whl (49 kB)
     |████████████████████████████████| 49 kB 7.3 MB/s
Requirement already satisfied: ptyprocess>=0.5 in /usr/local/lib/python3.7/dist-packages (from pexpect->ipython>=3.2.3->pyfolio@ git+https://github.com/quantopian/pyfolio.git#egg=pyfolio-0.9.2->finrl==0.3.5) (0.7.0)
Requirement already satisfied: toml in /usr/local/lib/python3.7/dist-packages (from pre-commit->finrl==0.3.5) (0.10.2)
Collecting identify>=1.0.0
  Downloading identify-2.5.3-py2.py3-none-any.whl (98 kB)
     |████████████████████████████████| 98 kB 701 kB/s
Collecting virtualenv>=20.0.8
  Downloading virtualenv-20.16.4-py3-none-any.whl (8.8 MB)
     |████████████████████████████████| 8.8 MB 76.7 MB/s
Collecting nodeenv>=0.11.1
  Downloading nodeenv-1.7.0-py2.py3-none-any.whl (21 kB)
Collecting cfgv>=2.0.0
  Downloading cfgv-3.3.1-py2.py3-none-any.whl (7.3 kB)
Requirement already satisfied: filelock<4,>=3.4.1 in /usr/local/lib/python3.7/dist-packages (from virtualenv>=20.0.8->pre-commit->finrl==0.3.5) (3.8.0)
Collecting platformdirs<3,>=2.4
  Downloading platformdirs-2.5.2-py3-none-any.whl (14 kB)
Collecting distlib<1,>=0.3.5
  Downloading distlib-0.3.6-py2.py3-none-any.whl (468 kB)
     |████████████████████████████████| 468 kB 78.9 MB/s
Requirement already satisfied: atomicwrites>=1.0 in /usr/local/lib/python3.7/dist-packages (from pytest->finrl==0.3.5) (1.4.1)
Requirement already satisfied: py>=1.5.0 in /usr/local/lib/python3.7/dist-packages (from pytest->finrl==0.3.5) (1.11.0)
Requirement already satisfied: more-itertools>=4.0.0 in /usr/local/lib/python3.7/dist-packages (from pytest->finrl==0.3.5) (8.14.0)
Requirement already satisfied: pluggy<0.8,>=0.5 in /usr/local/lib/python3.7/dist-packages (from pytest->finrl==0.3.5) (0.7.1)
Requirement already satisfied: click<=8.0.4,>=7.0 in /usr/local/lib/python3.7/dist-packages (from ray[default]->finrl==0.3.5) (7.1.2)
Requirement already satisfied: jsonschema in /usr/local/lib/python3.7/dist-packages (from ray[default]->finrl==0.3.5) (4.3.3)
Collecting grpcio<=1.43.0,>=1.28.1
  Downloading grpcio-1.43.0-cp37-cp37m-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (4.1 MB)
     |████████████████████████████████| 4.1 MB 69.7 MB/s
Requirement already satisfied: protobuf<4.0.0,>=3.15.3 in /usr/local/lib/python3.7/dist-packages (from ray[default]->finrl==0.3.5) (3.17.3)
Requirement already satisfied: pydantic in /usr/local/lib/python3.7/dist-packages (from ray[default]->finrl==0.3.5) (1.9.2)
Collecting colorful
  Downloading colorful-0.5.4-py2.py3-none-any.whl (201 kB)
     |████████████████████████████████| 201 kB 89.6 MB/s
Collecting gpustat>=1.0.0b1
  Downloading gpustat-1.0.0.tar.gz (90 kB)
     |████████████████████████████████| 90 kB 11.8 MB/s
Collecting aiohttp-cors
  Downloading aiohttp_cors-0.7.0-py3-none-any.whl (27 kB)
Collecting py-spy>=0.2.0
  Downloading py_spy-0.3.12-py2.py3-none-manylinux_2_5_x86_64.manylinux1_x86_64.whl (3.1 MB)
     |████████████████████████████████| 3.1 MB 70.8 MB/s
Collecting prometheus-client<0.14.0,>=0.7.1
  Downloading prometheus_client-0.13.1-py3-none-any.whl (57 kB)
     |████████████████████████████████| 57 kB 6.3 MB/s
Requirement already satisfied: smart-open in /usr/local/lib/python3.7/dist-packages (from ray[default]->finrl==0.3.5) (5.2.1)
Collecting opencensus
  Downloading opencensus-0.11.0-py2.py3-none-any.whl (128 kB)
     |████████████████████████████████| 128 kB 70.9 MB/s
Collecting nvidia-ml-py<=11.495.46,>=11.450.129
  Downloading nvidia_ml_py-11.495.46-py3-none-any.whl (25 kB)
Collecting psutil>=5.6.0
  Downloading psutil-5.9.2-cp37-cp37m-manylinux_2_12_x86_64.manylinux2010_x86_64.manylinux_2_17_x86_64.manylinux2014_x86_64.whl (281 kB)
     |████████████████████████████████| 281 kB 71.9 MB/s
Collecting blessed>=1.17.1
  Downloading blessed-1.19.1-py2.py3-none-any.whl (58 kB)
     |████████████████████████████████| 58 kB 7.7 MB/s
Requirement already satisfied: importlib-resources>=1.4.0 in /usr/local/lib/python3.7/dist-packages (from jsonschema->ray[default]->finrl==0.3.5) (5.9.0)
Requirement already satisfied: pyrsistent!=0.17.0,!=0.17.1,!=0.17.2,>=0.14.0 in /usr/local/lib/python3.7/dist-packages (from jsonschema->ray[default]->finrl==0.3.5) (0.18.1)
Collecting opencensus-context>=0.1.3
  Downloading opencensus_context-0.1.3-py2.py3-none-any.whl (5.1 kB)
Requirement already satisfied: google-api-core<3.0.0,>=1.0.0 in /usr/local/lib/python3.7/dist-packages (from opencensus->ray[default]->finrl==0.3.5) (1.31.6)
Requirement already satisfied: google-auth<2.0dev,>=1.25.0 in /usr/local/lib/python3.7/dist-packages (from google-api-core<3.0.0,>=1.0.0->opencensus->ray[default]->finrl==0.3.5) (1.35.0)
Requirement already satisfied: googleapis-common-protos<2.0dev,>=1.6.0 in /usr/local/lib/python3.7/dist-packages (from google-api-core<3.0.0,>=1.0.0->opencensus->ray[default]->finrl==0.3.5) (1.56.4)
Requirement already satisfied: cachetools<5.0,>=2.0.0 in /usr/local/lib/python3.7/dist-packages (from google-auth<2.0dev,>=1.25.0->google-api-core<3.0.0,>=1.0.0->opencensus->ray[default]->finrl==0.3.5) (4.2.4)
Requirement already satisfied: pyasn1-modules>=0.2.1 in /usr/local/lib/python3.7/dist-packages (from google-auth<2.0dev,>=1.25.0->google-api-core<3.0.0,>=1.0.0->opencensus->ray[default]->finrl==0.3.5) (0.2.8)
Requirement already satisfied: rsa<5,>=3.1.4 in /usr/local/lib/python3.7/dist-packages (from google-auth<2.0dev,>=1.25.0->google-api-core<3.0.0,>=1.0.0->opencensus->ray[default]->finrl==0.3.5) (4.9)
Requirement already satisfied: pyasn1<0.5.0,>=0.4.6 in /usr/local/lib/python3.7/dist-packages (from pyasn1-modules>=0.2.1->google-auth<2.0dev,>=1.25.0->google-api-core<3.0.0,>=1.0.0->opencensus->ray[default]->finrl==0.3.5) (0.4.8)

<a id='1.2'></a>
## 2.2. Daftar Paket Python
* Yahoo Finance API
* pandas
* numpy
* matplotlib
* stockstats
* OpenAI gym
* stable-baselines
* tensorflow
* pyfolio

<a id='1.3'></a>
## 2.3. Impot Paket

* Modul Python **pandas** digunakan untuk menganalisis dan memanipulasi data.
* Modul Python **numpy** digunakan untuk memproses larik atau array.
* Modul Python **matplotlib** digunakan membuat visualisasi data dalam dua dimensi.
* Modul Python **matplotlib.pyplot** adalah kumpulan fungsi yang membuat matplotlib berfungsi seperti MATLAB.
* Modul Python **Datetime** menyediakan sejumlah fungsi untuk menangani tanggal, waktu, dan interval waktu. Date dan datetime adalah objek dalam Python, bukan string atau timestamps.
* **YahooDownloader** menyediakan metode untuk mengambil data saham harian dari API Keuangan Yahoo!
* **FeatureEngineer** menyediakan metode untuk preprocessing data harga saham
* **data_split** membagi dataset menjadi data pelatihan dan data pengujian berdasarkan tanggal
* **StockTradingEnv** Lingkungan perdagangan saham untuk OpenAI gym
* **DRLAgent** menyediakan implementasi untuk algoritma DRL
* **DataProcessor** memproses data menggunakan prosesor data terpadu
* **backtest_stats** menghitung statistik *backtesting*
* **backtest_plot** membuat dan menampilkan plot ringkasan laporan *backtesting*.
* **get_daily_return** 
* **get_baseline** mengunduh data berdasarkan suatu indeks pada periode waktu tertentu.
* Metode **sys.path.append()** digunakan untuk menambahkan jalur sementara. Dengan demikian, jalur tersebut akan valid untuk sebuah sesi, misalnya.
* Python **itertool** adalah modul yang menyediakan berbagai fungsi yang bekerja pada iterator untuk menghasilkan iterator yang kompleks. Modul ini berfungsi sebagai alat yang cepat dan hemat memori.

In [2]:
import pandas as pd
import numpy as np
import matplotlib
import matplotlib.pyplot as plt
# matplotlib.use('Agg')
import datetime

%matplotlib inline
from finrl.meta.preprocessor.yahoodownloader import YahooDownloader
from finrl.meta.preprocessor.preprocessors import FeatureEngineer, data_split
from finrl.meta.env_stock_trading.env_stocktrading import StockTradingEnv
from finrl.agents.stablebaselines3.models import DRLAgent
from finrl.meta.data_processor import DataProcessor

from finrl.plot import backtest_stats, backtest_plot, get_daily_return, get_baseline
from pprint import pprint

import sys
sys.path.append("../FinRL")

import itertools

/usr/local/lib/python3.7/dist-packages/pyfolio/pos.py:27: UserWarning: Module "zipline.assets" not found; multipliers will not be applied to position notionals.
  'Module "zipline.assets" not found; multipliers will not be applied'

<a id='1.4'></a>
## 2.4. Membuat Folder

In [3]:
from finrl import config
from finrl import config_tickers
import os
from finrl.main import check_and_make_directories
from finrl.config import (
    DATA_SAVE_DIR,
    TRAINED_MODEL_DIR,
    TENSORBOARD_LOG_DIR,
    RESULTS_DIR,
    INDICATORS,
    TRAIN_START_DATE,
    TRAIN_END_DATE,
    TEST_START_DATE,
    TEST_END_DATE,
    TRADE_START_DATE,
    TRADE_END_DATE,
)
check_and_make_directories([DATA_SAVE_DIR, TRAINED_MODEL_DIR, TENSORBOARD_LOG_DIR, RESULTS_DIR])

<a id='2'></a>
# Part 3. Mengunduh Data

Yahoo Finance menyediakan data saham, berita keuangan, laporan keuangan, dll, secara gratis.
* FinRL *Library* menggunakan kelas **YahooDownloader** di FinRL-Meta untuk mengambil data melalui Yahoo Finance API
* Batas Pemanggilan: Menggunakan API Publik (tanpa autentikasi), Pengguna dibatasi hingga 2.000 permintaan per jam per IP (atau hingga total 48.000 permintaan per hari).

In [4]:
TRAIN_START_DATE = '2009-01-01'
TRAIN_END_DATE = '2017-12-31'
TRADE_START_DATE = '2018-01-01'
TRADE_END_DATE = '2019-12-20'

In [5]:
#Data diperoleh dari idx.co.id diakses pada tanggal 27/08/2022
#Fraksi 1: x<Rp200,00
fraksi1 = ['KIJA.JK', 'LCGP.JK', 'LMPI.JK', 'LPKR.JK']

#Fraksi 2: Rp200,00<= x <Rp500,00
fraksi2 = ['BMTR.JK','BTON.JK','FORU.JK','GEMA.JK']

#Fraksi 3: Rp500,00<= x <Rp2.000,00
fraksi3 = ['AKRA.JK','BRPT.JK','KLBF.JK','MEDC.JK']

#Fraksi 4: Rp2000,00<= x <Rp5000,00
fraksi4 = ['JECC.JK', 'TMAS.JK', 'TPIA.JK', 'UNVR.JK']

#Fraksi 5: >=Rp5000,00
fraksi5 =['INCO.JK','INDF.JK','INTP.JK','UNTR.JK']

In [159]:
df = YahooDownloader(start_date = TRAIN_START_DATE,
                     end_date = TRADE_END_DATE,
                     ticker_list = fraksi5).fetch_data()

[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
Shape of DataFrame:  (10912, 8)

In [160]:
df.nunique()

date       2728
open       1787
high       1851
low        1822
close      4888
volume    10004
tic           4
day           5
dtype: int64

In [161]:
print(df['tic'].unique())

['INCO.JK' 'INDF.JK' 'INTP.JK' 'UNTR.JK']

* **sort_values()** berfungsi mengurutkan bingkai data dalam urutan Ascending atau Descending dari kolom yang dilewati.
* **ignore_index** berfungsi untuk menentukan untuk mereset indeks mulai dari nol. Secara default disetel *false*.
* **head()** digunakan untuk mendapatkan n baris pertama.

In [162]:
df.sort_values(['date','tic'],ignore_index=True).head()

,date,open,high,low,close,volume,tic,day
0,2009-01-05,2050.000000,2300.000000,2030.000000,1792.011108,30353500,INCO.JK,0
1,2009-01-05,980.000000,980.000000,920.000000,638.533020,154640500,INDF.JK,0
2,2009-01-05,4600.000000,5050.000000,4600.000000,3106.131348,3534000,INTP.JK,0
3,2009-01-05,4326.423828,5071.530273,4326.423828,3122.125000,25673281,UNTR.JK,0
4,2009-01-06,2300.000000,2325.000000,2100.000000,1733.576050,21013000,INCO.JK,1

<a id='3'></a>
# Bagian 4: Memproses Data

Periksa data yang hilang dan melakukan *feature engineering* untuk mengubah data menjadi *state*.
* **Menambahkan indikator teknis**

  Dalam praktik jual-beli, berbagai informasi perlu diperhitungkan, seperti harga historis, kepemilikan saham saat ini, indikator teknis, dll. Indikator teknis yang dapat digunakan antara lain, MACD, RSI, CCI, ADX, Bollinger Bands, dll. 
* **Menambahkan indeks turbulensi**

  Risk-aversion mencerminkan seberapa berani investor melakukan jual-beli saham dengan risiko yang tinggi. Hal ini mempengaruhi strategi trading investor ketika menghadapi tingkat volatilitas pasar yang berbeda. Untuk mengendalikan risiko dalam skenario terburuk, seperti krisis keuangan tahun 1998, FinRL menggunakan indeks turbulensi yang mengukur fluktuasi harga aset yang ekstrem.

In [163]:
INDICATORS = [
    "macd",
    "rsi_30",
    "cci_30"
]

Membersihkan data mentah dari nilai-nilai yang hilang. Sehingga saham dengan data yang hilang dihapus dari daftar.

In [164]:
fe = FeatureEngineer(
                    use_technical_indicator=True,
                    tech_indicator_list = INDICATORS,
                    use_vix=True,
                    use_turbulence=True,
                    user_defined_feature = False)

processed = fe.preprocess_data(df)

Successfully added technical indicators
[*********************100%***********************]  1 of 1 completed
Shape of DataFrame:  (2759, 8)
Successfully added vix
Successfully added turbulence index

In [165]:
processed.nunique()

date           2651
open           1775
high           1835
low            1809
close          4828
volume         9764
tic               4
day               5
macd          10601
rsi_30         9608
cci_30        10598
vix            1441
turbulence     2397
dtype: int64

In [166]:
list_ticker = processed["tic"].unique().tolist()
list_ticker

['INCO.JK', 'INDF.JK', 'INTP.JK', 'UNTR.JK']

In [167]:
list_date = list(pd.date_range(processed['date'].min(),processed['date'].max()).astype(str))
list_date

['2009-01-05',
 '2009-01-06',
 '2009-01-07',
 '2009-01-08',
 '2009-01-09',
 '2009-01-10',
 '2009-01-11',
 '2009-01-12',
 '2009-01-13',
 '2009-01-14',
 '2009-01-15',
 '2009-01-16',
 '2009-01-17',
 '2009-01-18',
 '2009-01-19',
 '2009-01-20',
 '2009-01-21',
 '2009-01-22',
 '2009-01-23',
 '2009-01-24',
 '2009-01-25',
 '2009-01-26',
 '2009-01-27',
 '2009-01-28',
 '2009-01-29',
 '2009-01-30',
 '2009-01-31',
 '2009-02-01',
 '2009-02-02',
 '2009-02-03',
 '2009-02-04',
 '2009-02-05',
 '2009-02-06',
 '2009-02-07',
 '2009-02-08',
 '2009-02-09',
 '2009-02-10',
 '2009-02-11',
 '2009-02-12',
 '2009-02-13',
 '2009-02-14',
 '2009-02-15',
 '2009-02-16',
 '2009-02-17',
 '2009-02-18',
 '2009-02-19',
 '2009-02-20',
 '2009-02-21',
 '2009-02-22',
 '2009-02-23',
 '2009-02-24',
 '2009-02-25',
 '2009-02-26',
 '2009-02-27',
 '2009-02-28',
 '2009-03-01',
 '2009-03-02',
 '2009-03-03',
 '2009-03-04',
 '2009-03-05',
 '2009-03-06',
 '2009-03-07',
 '2009-03-08',
 '2009-03-09',
 '2009-03-10',
 '2009-03-11',
 '2009-03-12',
 '2009-03-13',
 '2009-03-14',
 '2009-03-15',
 '2009-03-16',
 '2009-03-17',
 '2009-03-18',
 '2009-03-19',
 '2009-03-20',
 '2009-03-21',
 '2009-03-22',
 '2009-03-23',
 '2009-03-24',
 '2009-03-25',
 '2009-03-26',
 '2009-03-27',
 '2009-03-28',
 '2009-03-29',
 '2009-03-30',
 '2009-03-31',
 '2009-04-01',
 '2009-04-02',
 '2009-04-03',
 '2009-04-04',
 '2009-04-05',
 '2009-04-06',
 '2009-04-07',
 '2009-04-08',
 '2009-04-09',
 '2009-04-10',
 '2009-04-11',
 '2009-04-12',
 '2009-04-13',
 '2009-04-14',
 '2009-04-15',
 '2009-04-16',
 '2009-04-17',
 '2009-04-18',
 '2009-04-19',
 '2009-04-20',
 '2009-04-21',
 '2009-04-22',
 '2009-04-23',
 '2009-04-24',
 '2009-04-25',
 '2009-04-26',
 '2009-04-27',
 '2009-04-28',
 '2009-04-29',
 '2009-04-30',
 '2009-05-01',
 '2009-05-02',
 '2009-05-03',
 '2009-05-04',
 '2009-05-05',
 '2009-05-06',
 '2009-05-07',
 '2009-05-08',
 '2009-05-09',
 '2009-05-10',
 '2009-05-11',
 '2009-05-12',
 '2009-05-13',
 '2009-05-14',
 '2009-05-15',
 '2009-05-16',
 '2009-05-17',
 '2009-05-18',
 '2009-05-19',
 '2009-05-20',
 '2009-05-21',
 '2009-05-22',
 '2009-05-23',
 '2009-05-24',
 '2009-05-25',
 '2009-05-26',
 '2009-05-27',
 '2009-05-28',
 '2009-05-29',
 '2009-05-30',
 '2009-05-31',
 '2009-06-01',
 '2009-06-02',
 '2009-06-03',
 '2009-06-04',
 '2009-06-05',
 '2009-06-06',
 '2009-06-07',
 '2009-06-08',
 '2009-06-09',
 '2009-06-10',
 '2009-06-11',
 '2009-06-12',
 '2009-06-13',
 '2009-06-14',
 '2009-06-15',
 '2009-06-16',
 '2009-06-17',
 '2009-06-18',
 '2009-06-19',
 '2009-06-20',
 '2009-06-21',
 '2009-06-22',
 '2009-06-23',
 '2009-06-24',
 '2009-06-25',
 '2009-06-26',
 '2009-06-27',
 '2009-06-28',
 '2009-06-29',
 '2009-06-30',
 '2009-07-01',
 '2009-07-02',
 '2009-07-03',
 '2009-07-04',
 '2009-07-05',
 '2009-07-06',
 '2009-07-07',
 '2009-07-08',
 '2009-07-09',
 '2009-07-10',
 '2009-07-11',
 '2009-07-12',
 '2009-07-13',
 '2009-07-14',
 '2009-07-15',
 '2009-07-16',
 '2009-07-17',
 '2009-07-18',
 '2009-07-19',
 '2009-07-20',
 '2009-07-21',
 '2009-07-22',
 '2009-07-23',
 '2009-07-24',
 '2009-07-25',
 '2009-07-26',
 '2009-07-27',
 '2009-07-28',
 '2009-07-29',
 '2009-07-30',
 '2009-07-31',
 '2009-08-01',
 '2009-08-02',
 '2009-08-03',
 '2009-08-04',
 '2009-08-05',
 '2009-08-06',
 '2009-08-07',
 '2009-08-08',
 '2009-08-09',
 '2009-08-10',
 '2009-08-11',
 '2009-08-12',
 '2009-08-13',
 '2009-08-14',
 '2009-08-15',
 '2009-08-16',
 '2009-08-17',
 '2009-08-18',
 '2009-08-19',
 '2009-08-20',
 '2009-08-21',
 '2009-08-22',
 '2009-08-23',
 '2009-08-24',
 '2009-08-25',
 '2009-08-26',
 '2009-08-27',
 '2009-08-28',
 '2009-08-29',
 '2009-08-30',
 '2009-08-31',
 '2009-09-01',
 '2009-09-02',
 '2009-09-03',
 '2009-09-04',
 '2009-09-05',
 '2009-09-06',
 '2009-09-07',
 '2009-09-08',
 '2009-09-09',
 '2009-09-10',
 '2009-09-11',
 '2009-09-12',
 '2009-09-13',
 '2009-09-14',
 '2009-09-15',
 '2009-09-16',
 '2009-09-17',
 '2009-09-18',
 '2009-09-19',
 '2009-09-20',
 '2009-09-21',
 '2009-09-22',
 '2009-09-23',
 '2009-09-24',
 '2009-09-25',
 '2009-09-26',
 '2009-09-27',
 '2009-09-28',
 '2009-09-29',
 '2009-09-30',
 '2009-10-01',
 '2009-10-02',
 '2009-10-03',
 '2009-10-04',
 '2009-10-05',
 '2009-10-06',
 '2009-10-07',
 '2009-10-08',
 '2009-10-09',
 '2009-10-10',
 '2009-10-11',
 '2009-10-12',
 '2009-10-13',
 '2009-10-14',
 '2009-10-15',
 '2009-10-16',
 '2009-10-17',
 '2009-10-18',
 '2009-10-19',
 '2009-10-20',
 '2009-10-21',
 '2009-10-22',
 '2009-10-23',
 '2009-10-24',
 '2009-10-25',
 '2009-10-26',
 '2009-10-27',
 '2009-10-28',
 '2009-10-29',
 '2009-10-30',
 '2009-10-31',
 '2009-11-01',
 '2009-11-02',
 '2009-11-03',
 '2009-11-04',
 '2009-11-05',
 '2009-11-06',
 '2009-11-07',
 '2009-11-08',
 '2009-11-09',
 '2009-11-10',
 '2009-11-11',
 '2009-11-12',
 '2009-11-13',
 '2009-11-14',
 '2009-11-15',
 '2009-11-16',
 '2009-11-17',
 '2009-11-18',
 '2009-11-19',
 '2009-11-20',
 '2009-11-21',
 '2009-11-22',
 '2009-11-23',
 '2009-11-24',
 '2009-11-25',
 '2009-11-26',
 '2009-11-27',
 '2009-11-28',
 '2009-11-29',
 '2009-11-30',
 '2009-12-01',
 '2009-12-02',
 '2009-12-03',
 '2009-12-04',
 '2009-12-05',
 '2009-12-06',
 '2009-12-07',
 '2009-12-08',
 '2009-12-09',
 '2009-12-10',
 '2009-12-11',
 '2009-12-12',
 '2009-12-13',
 '2009-12-14',
 '2009-12-15',
 '2009-12-16',
 '2009-12-17',
 '2009-12-18',
 '2009-12-19',
 '2009-12-20',
 '2009-12-21',
 '2009-12-22',
 '2009-12-23',
 '2009-12-24',
 '2009-12-25',
 '2009-12-26',
 '2009-12-27',
 '2009-12-28',
 '2009-12-29',
 '2009-12-30',
 '2009-12-31',
 '2010-01-01',
 '2010-01-02',
 '2010-01-03',
 '2010-01-04',
 '2010-01-05',
 '2010-01-06',
 '2010-01-07',
 '2010-01-08',
 '2010-01-09',
 '2010-01-10',
 '2010-01-11',
 '2010-01-12',
 '2010-01-13',
 '2010-01-14',
 '2010-01-15',
 '2010-01-16',
 '2010-01-17',
 '2010-01-18',
 '2010-01-19',
 '2010-01-20',
 '2010-01-21',
 '2010-01-22',
 '2010-01-23',
 '2010-01-24',
 '2010-01-25',
 '2010-01-26',
 '2010-01-27',
 '2010-01-28',
 '2010-01-29',
 '2010-01-30',
 '2010-01-31',
 '2010-02-01',
 '2010-02-02',
 '2010-02-03',
 '2010-02-04',
 '2010-02-05',
 '2010-02-06',
 '2010-02-07',
 '2010-02-08',
 '2010-02-09',
 '2010-02-10',
 '2010-02-11',
 '2010-02-12',
 '2010-02-13',
 '2010-02-14',
 '2010-02-15',
 '2010-02-16',
 '2010-02-17',
 '2010-02-18',
 '2010-02-19',
 '2010-02-20',
 '2010-02-21',
 '2010-02-22',
 '2010-02-23',
 '2010-02-24',
 '2010-02-25',
 '2010-02-26',
 '2010-02-27',
 '2010-02-28',
 '2010-03-01',
 '2010-03-02',
 '2010-03-03',
 '2010-03-04',
 '2010-03-05',
 '2010-03-06',
 '2010-03-07',
 '2010-03-08',
 '2010-03-09',
 '2010-03-10',
 '2010-03-11',
 '2010-03-12',
 '2010-03-13',
 '2010-03-14',
 '2010-03-15',
 '2010-03-16',
 '2010-03-17',
 '2010-03-18',
 '2010-03-19',
 '2010-03-20',
 '2010-03-21',
 '2010-03-22',
 '2010-03-23',
 '2010-03-24',
 '2010-03-25',
 '2010-03-26',
 '2010-03-27',
 '2010-03-28',
 '2010-03-29',
 '2010-03-30',
 '2010-03-31',
 '2010-04-01',
 '2010-04-02',
 '2010-04-03',
 '2010-04-04',
 '2010-04-05',
 '2010-04-06',
 '2010-04-07',
 '2010-04-08',
 '2010-04-09',
 '2010-04-10',
 '2010-04-11',
 '2010-04-12',
 '2010-04-13',
 '2010-04-14',
 '2010-04-15',
 '2010-04-16',
 '2010-04-17',
 '2010-04-18',
 '2010-04-19',
 '2010-04-20',
 '2010-04-21',
 '2010-04-22',
 '2010-04-23',
 '2010-04-24',
 '2010-04-25',
 '2010-04-26',
 '2010-04-27',
 '2010-04-28',
 '2010-04-29',
 '2010-04-30',
 '2010-05-01',
 '2010-05-02',
 '2010-05-03',
 '2010-05-04',
 '2010-05-05',
 '2010-05-06',
 '2010-05-07',
 '2010-05-08',
 '2010-05-09',
 '2010-05-10',
 '2010-05-11',
 '2010-05-12',
 '2010-05-13',
 '2010-05-14',
 '2010-05-15',
 '2010-05-16',
 '2010-05-17',
 '2010-05-18',
 '2010-05-19',
 '2010-05-20',
 '2010-05-21',
 '2010-05-22',
 '2010-05-23',
 '2010-05-24',
 '2010-05-25',
 '2010-05-26',
 '2010-05-27',
 '2010-05-28',
 '2010-05-29',
 '2010-05-30',
 '2010-05-31',
 '2010-06-01',
 '2010-06-02',
 '2010-06-03',
 '2010-06-04',
 '2010-06-05',
 '2010-06-06',
 '2010-06-07',
 '2010-06-08',
 '2010-06-09',
 '2010-06-10',
 '2010-06-11',
 '2010-06-12',
 '2010-06-13',
 '2010-06-14',
 '2010-06-15',
 '2010-06-16',
 '2010-06-17',
 '2010-06-18',
 '2010-06-19',
 '2010-06-20',
 '2010-06-21',
 '2010-06-22',
 '2010-06-23',
 '2010-06-24',
 '2010-06-25',
 '2010-06-26',
 '2010-06-27',
 '2010-06-28',
 '2010-06-29',
 '2010-06-30',
 '2010-07-01',
 '2010-07-02',
 '2010-07-03',
 '2010-07-04',
 '2010-07-05',
 '2010-07-06',
 '2010-07-07',
 '2010-07-08',
 '2010-07-09',
 '2010-07-10',
 '2010-07-11',
 '2010-07-12',
 '2010-07-13',
 '2010-07-14',
 '2010-07-15',
 '2010-07-16',
 '2010-07-17',
 '2010-07-18',
 '2010-07-19',
 '2010-07-20',
 '2010-07-21',
 '2010-07-22',
 '2010-07-23',
 '2010-07-24',
 '2010-07-25',
 '2010-07-26',
 '2010-07-27',
 '2010-07-28',
 '2010-07-29',
 '2010-07-30',
 '2010-07-31',
 '2010-08-01',
 '2010-08-02',
 '2010-08-03',
 '2010-08-04',
 '2010-08-05',
 '2010-08-06',
 '2010-08-07',
 '2010-08-08',
 '2010-08-09',
 '2010-08-10',
 '2010-08-11',
 '2010-08-12',
 '2010-08-13',
 '2010-08-14',
 '2010-08-15',
 '2010-08-16',
 '2010-08-17',
 '2010-08-18',
 '2010-08-19',
 '2010-08-20',
 '2010-08-21',
 '2010-08-22',
 '2010-08-23',
 '2010-08-24',
 '2010-08-25',
 '2010-08-26',
 '2010-08-27',
 '2010-08-28',
 '2010-08-29',
 '2010-08-30',
 '2010-08-31',
 '2010-09-01',
 '2010-09-02',
 '2010-09-03',
 '2010-09-04',
 '2010-09-05',
 '2010-09-06',
 '2010-09-07',
 '2010-09-08',
 '2010-09-09',
 '2010-09-10',
 '2010-09-11',
 '2010-09-12',
 '2010-09-13',
 '2010-09-14',
 '2010-09-15',
 '2010-09-16',
 '2010-09-17',
 '2010-09-18',
 '2010-09-19',
 '2010-09-20',
 '2010-09-21',
 '2010-09-22',
 '2010-09-23',
 '2010-09-24',
 '2010-09-25',
 '2010-09-26',
 '2010-09-27',
 '2010-09-28',
 '2010-09-29',
 '2010-09-30',
 '2010-10-01',
 '2010-10-02',
 '2010-10-03',
 '2010-10-04',
 '2010-10-05',
 '2010-10-06',
 '2010-10-07',
 '2010-10-08',
 '2010-10-09',
 '2010-10-10',
 '2010-10-11',
 '2010-10-12',
 '2010-10-13',
 '2010-10-14',
 '2010-10-15',
 '2010-10-16',
 '2010-10-17',
 '2010-10-18',
 '2010-10-19',
 '2010-10-20',
 '2010-10-21',
 '2010-10-22',
 '2010-10-23',
 '2010-10-24',
 '2010-10-25',
 '2010-10-26',
 '2010-10-27',
 '2010-10-28',
 '2010-10-29',
 '2010-10-30',
 '2010-10-31',
 '2010-11-01',
 '2010-11-02',
 '2010-11-03',
 '2010-11-04',
 '2010-11-05',
 '2010-11-06',
 '2010-11-07',
 '2010-11-08',
 '2010-11-09',
 '2010-11-10',
 '2010-11-11',
 '2010-11-12',
 '2010-11-13',
 '2010-11-14',
 '2010-11-15',
 '2010-11-16',
 '2010-11-17',
 '2010-11-18',
 '2010-11-19',
 '2010-11-20',
 '2010-11-21',
 '2010-11-22',
 '2010-11-23',
 '2010-11-24',
 '2010-11-25',
 '2010-11-26',
 '2010-11-27',
 '2010-11-28',
 '2010-11-29',
 '2010-11-30',
 '2010-12-01',
 '2010-12-02',
 '2010-12-03',
 '2010-12-04',
 '2010-12-05',
 '2010-12-06',
 '2010-12-07',
 '2010-12-08',
 '2010-12-09',
 '2010-12-10',
 '2010-12-11',
 '2010-12-12',
 '2010-12-13',
 '2010-12-14',
 '2010-12-15',
 '2010-12-16',
 '2010-12-17',
 '2010-12-18',
 '2010-12-19',
 '2010-12-20',
 '2010-12-21',
 '2010-12-22',
 '2010-12-23',
 '2010-12-24',
 '2010-12-25',
 '2010-12-26',
 '2010-12-27',
 '2010-12-28',
 '2010-12-29',
 '2010-12-30',
 '2010-12-31',
 '2011-01-01',
 '2011-01-02',
 '2011-01-03',
 '2011-01-04',
 '2011-01-05',
 '2011-01-06',
 '2011-01-07',
 '2011-01-08',
 '2011-01-09',
 '2011-01-10',
 '2011-01-11',
 '2011-01-12',
 '2011-01-13',
 '2011-01-14',
 '2011-01-15',
 '2011-01-16',
 '2011-01-17',
 '2011-01-18',
 '2011-01-19',
 '2011-01-20',
 '2011-01-21',
 '2011-01-22',
 '2011-01-23',
 '2011-01-24',
 '2011-01-25',
 '2011-01-26',
 '2011-01-27',
 '2011-01-28',
 '2011-01-29',
 '2011-01-30',
 '2011-01-31',
 '2011-02-01',
 '2011-02-02',
 '2011-02-03',
 '2011-02-04',
 '2011-02-05',
 '2011-02-06',
 '2011-02-07',
 '2011-02-08',
 '2011-02-09',
 '2011-02-10',
 '2011-02-11',
 '2011-02-12',
 '2011-02-13',
 '2011-02-14',
 '2011-02-15',
 '2011-02-16',
 '2011-02-17',
 '2011-02-18',
 '2011-02-19',
 '2011-02-20',
 '2011-02-21',
 '2011-02-22',
 '2011-02-23',
 '2011-02-24',
 '2011-02-25',
 '2011-02-26',
 '2011-02-27',
 '2011-02-28',
 '2011-03-01',
 '2011-03-02',
 '2011-03-03',
 '2011-03-04',
 '2011-03-05',
 '2011-03-06',
 '2011-03-07',
 '2011-03-08',
 '2011-03-09',
 '2011-03-10',
 '2011-03-11',
 '2011-03-12',
 '2011-03-13',
 '2011-03-14',
 '2011-03-15',
 '2011-03-16',
 '2011-03-17',
 '2011-03-18',
 '2011-03-19',
 '2011-03-20',
 '2011-03-21',
 '2011-03-22',
 '2011-03-23',
 '2011-03-24',
 '2011-03-25',
 '2011-03-26',
 '2011-03-27',
 '2011-03-28',
 '2011-03-29',
 '2011-03-30',
 '2011-03-31',
 '2011-04-01',
 '2011-04-02',
 '2011-04-03',
 '2011-04-04',
 '2011-04-05',
 '2011-04-06',
 '2011-04-07',
 '2011-04-08',
 '2011-04-09',
 '2011-04-10',
 '2011-04-11',
 '2011-04-12',
 '2011-04-13',
 '2011-04-14',
 '2011-04-15',
 '2011-04-16',
 '2011-04-17',
 '2011-04-18',
 '2011-04-19',
 '2011-04-20',
 '2011-04-21',
 '2011-04-22',
 '2011-04-23',
 '2011-04-24',
 '2011-04-25',
 '2011-04-26',
 '2011-04-27',
 '2011-04-28',
 '2011-04-29',
 '2011-04-30',
 '2011-05-01',
 '2011-05-02',
 '2011-05-03',
 '2011-05-04',
 '2011-05-05',
 '2011-05-06',
 '2011-05-07',
 '2011-05-08',
 '2011-05-09',
 '2011-05-10',
 '2011-05-11',
 '2011-05-12',
 '2011-05-13',
 '2011-05-14',
 '2011-05-15',
 '2011-05-16',
 '2011-05-17',
 '2011-05-18',
 '2011-05-19',
 '2011-05-20',
 '2011-05-21',
 '2011-05-22',
 '2011-05-23',
 '2011-05-24',
 '2011-05-25',
 '2011-05-26',
 '2011-05-27',
 '2011-05-28',
 '2011-05-29',
 '2011-05-30',
 '2011-05-31',
 '2011-06-01',
 '2011-06-02',
 '2011-06-03',
 '2011-06-04',
 '2011-06-05',
 '2011-06-06',
 '2011-06-07',
 '2011-06-08',
 '2011-06-09',
 '2011-06-10',
 '2011-06-11',
 '2011-06-12',
 '2011-06-13',
 '2011-06-14',
 '2011-06-15',
 '2011-06-16',
 '2011-06-17',
 '2011-06-18',
 '2011-06-19',
 '2011-06-20',
 '2011-06-21',
 '2011-06-22',
 '2011-06-23',
 '2011-06-24',
 '2011-06-25',
 '2011-06-26',
 '2011-06-27',
 '2011-06-28',
 '2011-06-29',
 '2011-06-30',
 '2011-07-01',
 '2011-07-02',
 '2011-07-03',
 '2011-07-04',
 '2011-07-05',
 '2011-07-06',
 '2011-07-07',
 '2011-07-08',
 '2011-07-09',
 '2011-07-10',
 '2011-07-11',
 '2011-07-12',
 '2011-07-13',
 '2011-07-14',
 '2011-07-15',
 '2011-07-16',
 '2011-07-17',
 '2011-07-18',
 '2011-07-19',
 '2011-07-20',
 '2011-07-21',
 '2011-07-22',
 '2011-07-23',
 '2011-07-24',
 '2011-07-25',
 '2011-07-26',
 '2011-07-27',
 '2011-07-28',
 '2011-07-29',
 '2011-07-30',
 '2011-07-31',
 '2011-08-01',
 '2011-08-02',
 '2011-08-03',
 '2011-08-04',
 '2011-08-05',
 '2011-08-06',
 '2011-08-07',
 '2011-08-08',
 '2011-08-09',
 '2011-08-10',
 '2011-08-11',
 '2011-08-12',
 '2011-08-13',
 '2011-08-14',
 '2011-08-15',
 '2011-08-16',
 '2011-08-17',
 '2011-08-18',
 '2011-08-19',
 '2011-08-20',
 '2011-08-21',
 '2011-08-22',
 '2011-08-23',
 '2011-08-24',
 '2011-08-25',
 '2011-08-26',
 '2011-08-27',
 '2011-08-28',
 '2011-08-29',
 '2011-08-30',
 '2011-08-31',
 '2011-09-01',
 '2011-09-02',
 '2011-09-03',
 '2011-09-04',
 '2011-09-05',
 '2011-09-06',
 '2011-09-07',
 '2011-09-08',
 '2011-09-09',
 '2011-09-10',
 '2011-09-11',
 '2011-09-12',
 '2011-09-13',
 '2011-09-14',
 '2011-09-15',
 '2011-09-16',
 '2011-09-17',
 '2011-09-18',
 '2011-09-19',
 '2011-09-20',
 '2011-09-21',
 '2011-09-22',
 '2011-09-23',
 '2011-09-24',
 '2011-09-25',
 '2011-09-26',
 '2011-09-27',
 '2011-09-28',
 '2011-09-29',
 '2011-09-30',
 '2011-10-01',
 ...]

In [168]:
combination = list(itertools.product(list_date,list_ticker))
combination

[('2009-01-05', 'INCO.JK'),
 ('2009-01-05', 'INDF.JK'),
 ('2009-01-05', 'INTP.JK'),
 ('2009-01-05', 'UNTR.JK'),
 ('2009-01-06', 'INCO.JK'),
 ('2009-01-06', 'INDF.JK'),
 ('2009-01-06', 'INTP.JK'),
 ('2009-01-06', 'UNTR.JK'),
 ('2009-01-07', 'INCO.JK'),
 ('2009-01-07', 'INDF.JK'),
 ('2009-01-07', 'INTP.JK'),
 ('2009-01-07', 'UNTR.JK'),
 ('2009-01-08', 'INCO.JK'),
 ('2009-01-08', 'INDF.JK'),
 ('2009-01-08', 'INTP.JK'),
 ('2009-01-08', 'UNTR.JK'),
 ('2009-01-09', 'INCO.JK'),
 ('2009-01-09', 'INDF.JK'),
 ('2009-01-09', 'INTP.JK'),
 ('2009-01-09', 'UNTR.JK'),
 ('2009-01-10', 'INCO.JK'),
 ('2009-01-10', 'INDF.JK'),
 ('2009-01-10', 'INTP.JK'),
 ('2009-01-10', 'UNTR.JK'),
 ('2009-01-11', 'INCO.JK'),
 ('2009-01-11', 'INDF.JK'),
 ('2009-01-11', 'INTP.JK'),
 ('2009-01-11', 'UNTR.JK'),
 ('2009-01-12', 'INCO.JK'),
 ('2009-01-12', 'INDF.JK'),
 ('2009-01-12', 'INTP.JK'),
 ('2009-01-12', 'UNTR.JK'),
 ('2009-01-13', 'INCO.JK'),
 ('2009-01-13', 'INDF.JK'),
 ('2009-01-13', 'INTP.JK'),
 ('2009-01-13', 'UNTR.JK'),
 ('2009-01-14', 'INCO.JK'),
 ('2009-01-14', 'INDF.JK'),
 ('2009-01-14', 'INTP.JK'),
 ('2009-01-14', 'UNTR.JK'),
 ('2009-01-15', 'INCO.JK'),
 ('2009-01-15', 'INDF.JK'),
 ('2009-01-15', 'INTP.JK'),
 ('2009-01-15', 'UNTR.JK'),
 ('2009-01-16', 'INCO.JK'),
 ('2009-01-16', 'INDF.JK'),
 ('2009-01-16', 'INTP.JK'),
 ('2009-01-16', 'UNTR.JK'),
 ('2009-01-17', 'INCO.JK'),
 ('2009-01-17', 'INDF.JK'),
 ('2009-01-17', 'INTP.JK'),
 ('2009-01-17', 'UNTR.JK'),
 ('2009-01-18', 'INCO.JK'),
 ('2009-01-18', 'INDF.JK'),
 ('2009-01-18', 'INTP.JK'),
 ('2009-01-18', 'UNTR.JK'),
 ('2009-01-19', 'INCO.JK'),
 ('2009-01-19', 'INDF.JK'),
 ('2009-01-19', 'INTP.JK'),
 ('2009-01-19', 'UNTR.JK'),
 ('2009-01-20', 'INCO.JK'),
 ('2009-01-20', 'INDF.JK'),
 ('2009-01-20', 'INTP.JK'),
 ('2009-01-20', 'UNTR.JK'),
 ('2009-01-21', 'INCO.JK'),
 ('2009-01-21', 'INDF.JK'),
 ('2009-01-21', 'INTP.JK'),
 ('2009-01-21', 'UNTR.JK'),
 ('2009-01-22', 'INCO.JK'),
 ('2009-01-22', 'INDF.JK'),
 ('2009-01-22', 'INTP.JK'),
 ('2009-01-22', 'UNTR.JK'),
 ('2009-01-23', 'INCO.JK'),
 ('2009-01-23', 'INDF.JK'),
 ('2009-01-23', 'INTP.JK'),
 ('2009-01-23', 'UNTR.JK'),
 ('2009-01-24', 'INCO.JK'),
 ('2009-01-24', 'INDF.JK'),
 ('2009-01-24', 'INTP.JK'),
 ('2009-01-24', 'UNTR.JK'),
 ('2009-01-25', 'INCO.JK'),
 ('2009-01-25', 'INDF.JK'),
 ('2009-01-25', 'INTP.JK'),
 ('2009-01-25', 'UNTR.JK'),
 ('2009-01-26', 'INCO.JK'),
 ('2009-01-26', 'INDF.JK'),
 ('2009-01-26', 'INTP.JK'),
 ('2009-01-26', 'UNTR.JK'),
 ('2009-01-27', 'INCO.JK'),
 ('2009-01-27', 'INDF.JK'),
 ('2009-01-27', 'INTP.JK'),
 ('2009-01-27', 'UNTR.JK'),
 ('2009-01-28', 'INCO.JK'),
 ('2009-01-28', 'INDF.JK'),
 ('2009-01-28', 'INTP.JK'),
 ('2009-01-28', 'UNTR.JK'),
 ('2009-01-29', 'INCO.JK'),
 ('2009-01-29', 'INDF.JK'),
 ('2009-01-29', 'INTP.JK'),
 ('2009-01-29', 'UNTR.JK'),
 ('2009-01-30', 'INCO.JK'),
 ('2009-01-30', 'INDF.JK'),
 ('2009-01-30', 'INTP.JK'),
 ('2009-01-30', 'UNTR.JK'),
 ('2009-01-31', 'INCO.JK'),
 ('2009-01-31', 'INDF.JK'),
 ('2009-01-31', 'INTP.JK'),
 ('2009-01-31', 'UNTR.JK'),
 ('2009-02-01', 'INCO.JK'),
 ('2009-02-01', 'INDF.JK'),
 ('2009-02-01', 'INTP.JK'),
 ('2009-02-01', 'UNTR.JK'),
 ('2009-02-02', 'INCO.JK'),
 ('2009-02-02', 'INDF.JK'),
 ('2009-02-02', 'INTP.JK'),
 ('2009-02-02', 'UNTR.JK'),
 ('2009-02-03', 'INCO.JK'),
 ('2009-02-03', 'INDF.JK'),
 ('2009-02-03', 'INTP.JK'),
 ('2009-02-03', 'UNTR.JK'),
 ('2009-02-04', 'INCO.JK'),
 ('2009-02-04', 'INDF.JK'),
 ('2009-02-04', 'INTP.JK'),
 ('2009-02-04', 'UNTR.JK'),
 ('2009-02-05', 'INCO.JK'),
 ('2009-02-05', 'INDF.JK'),
 ('2009-02-05', 'INTP.JK'),
 ('2009-02-05', 'UNTR.JK'),
 ('2009-02-06', 'INCO.JK'),
 ('2009-02-06', 'INDF.JK'),
 ('2009-02-06', 'INTP.JK'),
 ('2009-02-06', 'UNTR.JK'),
 ('2009-02-07', 'INCO.JK'),
 ('2009-02-07', 'INDF.JK'),
 ('2009-02-07', 'INTP.JK'),
 ('2009-02-07', 'UNTR.JK'),
 ('2009-02-08', 'INCO.JK'),
 ('2009-02-08', 'INDF.JK'),
 ('2009-02-08', 'INTP.JK'),
 ('2009-02-08', 'UNTR.JK'),
 ('2009-02-09', 'INCO.JK'),
 ('2009-02-09', 'INDF.JK'),
 ('2009-02-09', 'INTP.JK'),
 ('2009-02-09', 'UNTR.JK'),
 ('2009-02-10', 'INCO.JK'),
 ('2009-02-10', 'INDF.JK'),
 ('2009-02-10', 'INTP.JK'),
 ('2009-02-10', 'UNTR.JK'),
 ('2009-02-11', 'INCO.JK'),
 ('2009-02-11', 'INDF.JK'),
 ('2009-02-11', 'INTP.JK'),
 ('2009-02-11', 'UNTR.JK'),
 ('2009-02-12', 'INCO.JK'),
 ('2009-02-12', 'INDF.JK'),
 ('2009-02-12', 'INTP.JK'),
 ('2009-02-12', 'UNTR.JK'),
 ('2009-02-13', 'INCO.JK'),
 ('2009-02-13', 'INDF.JK'),
 ('2009-02-13', 'INTP.JK'),
 ('2009-02-13', 'UNTR.JK'),
 ('2009-02-14', 'INCO.JK'),
 ('2009-02-14', 'INDF.JK'),
 ('2009-02-14', 'INTP.JK'),
 ('2009-02-14', 'UNTR.JK'),
 ('2009-02-15', 'INCO.JK'),
 ('2009-02-15', 'INDF.JK'),
 ('2009-02-15', 'INTP.JK'),
 ('2009-02-15', 'UNTR.JK'),
 ('2009-02-16', 'INCO.JK'),
 ('2009-02-16', 'INDF.JK'),
 ('2009-02-16', 'INTP.JK'),
 ('2009-02-16', 'UNTR.JK'),
 ('2009-02-17', 'INCO.JK'),
 ('2009-02-17', 'INDF.JK'),
 ('2009-02-17', 'INTP.JK'),
 ('2009-02-17', 'UNTR.JK'),
 ('2009-02-18', 'INCO.JK'),
 ('2009-02-18', 'INDF.JK'),
 ('2009-02-18', 'INTP.JK'),
 ('2009-02-18', 'UNTR.JK'),
 ('2009-02-19', 'INCO.JK'),
 ('2009-02-19', 'INDF.JK'),
 ('2009-02-19', 'INTP.JK'),
 ('2009-02-19', 'UNTR.JK'),
 ('2009-02-20', 'INCO.JK'),
 ('2009-02-20', 'INDF.JK'),
 ('2009-02-20', 'INTP.JK'),
 ('2009-02-20', 'UNTR.JK'),
 ('2009-02-21', 'INCO.JK'),
 ('2009-02-21', 'INDF.JK'),
 ('2009-02-21', 'INTP.JK'),
 ('2009-02-21', 'UNTR.JK'),
 ('2009-02-22', 'INCO.JK'),
 ('2009-02-22', 'INDF.JK'),
 ('2009-02-22', 'INTP.JK'),
 ('2009-02-22', 'UNTR.JK'),
 ('2009-02-23', 'INCO.JK'),
 ('2009-02-23', 'INDF.JK'),
 ('2009-02-23', 'INTP.JK'),
 ('2009-02-23', 'UNTR.JK'),
 ('2009-02-24', 'INCO.JK'),
 ('2009-02-24', 'INDF.JK'),
 ('2009-02-24', 'INTP.JK'),
 ('2009-02-24', 'UNTR.JK'),
 ('2009-02-25', 'INCO.JK'),
 ('2009-02-25', 'INDF.JK'),
 ('2009-02-25', 'INTP.JK'),
 ('2009-02-25', 'UNTR.JK'),
 ('2009-02-26', 'INCO.JK'),
 ('2009-02-26', 'INDF.JK'),
 ('2009-02-26', 'INTP.JK'),
 ('2009-02-26', 'UNTR.JK'),
 ('2009-02-27', 'INCO.JK'),
 ('2009-02-27', 'INDF.JK'),
 ('2009-02-27', 'INTP.JK'),
 ('2009-02-27', 'UNTR.JK'),
 ('2009-02-28', 'INCO.JK'),
 ('2009-02-28', 'INDF.JK'),
 ('2009-02-28', 'INTP.JK'),
 ('2009-02-28', 'UNTR.JK'),
 ('2009-03-01', 'INCO.JK'),
 ('2009-03-01', 'INDF.JK'),
 ('2009-03-01', 'INTP.JK'),
 ('2009-03-01', 'UNTR.JK'),
 ('2009-03-02', 'INCO.JK'),
 ('2009-03-02', 'INDF.JK'),
 ('2009-03-02', 'INTP.JK'),
 ('2009-03-02', 'UNTR.JK'),
 ('2009-03-03', 'INCO.JK'),
 ('2009-03-03', 'INDF.JK'),
 ('2009-03-03', 'INTP.JK'),
 ('2009-03-03', 'UNTR.JK'),
 ('2009-03-04', 'INCO.JK'),
 ('2009-03-04', 'INDF.JK'),
 ('2009-03-04', 'INTP.JK'),
 ('2009-03-04', 'UNTR.JK'),
 ('2009-03-05', 'INCO.JK'),
 ('2009-03-05', 'INDF.JK'),
 ('2009-03-05', 'INTP.JK'),
 ('2009-03-05', 'UNTR.JK'),
 ('2009-03-06', 'INCO.JK'),
 ('2009-03-06', 'INDF.JK'),
 ('2009-03-06', 'INTP.JK'),
 ('2009-03-06', 'UNTR.JK'),
 ('2009-03-07', 'INCO.JK'),
 ('2009-03-07', 'INDF.JK'),
 ('2009-03-07', 'INTP.JK'),
 ('2009-03-07', 'UNTR.JK'),
 ('2009-03-08', 'INCO.JK'),
 ('2009-03-08', 'INDF.JK'),
 ('2009-03-08', 'INTP.JK'),
 ('2009-03-08', 'UNTR.JK'),
 ('2009-03-09', 'INCO.JK'),
 ('2009-03-09', 'INDF.JK'),
 ('2009-03-09', 'INTP.JK'),
 ('2009-03-09', 'UNTR.JK'),
 ('2009-03-10', 'INCO.JK'),
 ('2009-03-10', 'INDF.JK'),
 ('2009-03-10', 'INTP.JK'),
 ('2009-03-10', 'UNTR.JK'),
 ('2009-03-11', 'INCO.JK'),
 ('2009-03-11', 'INDF.JK'),
 ('2009-03-11', 'INTP.JK'),
 ('2009-03-11', 'UNTR.JK'),
 ('2009-03-12', 'INCO.JK'),
 ('2009-03-12', 'INDF.JK'),
 ('2009-03-12', 'INTP.JK'),
 ('2009-03-12', 'UNTR.JK'),
 ('2009-03-13', 'INCO.JK'),
 ('2009-03-13', 'INDF.JK'),
 ('2009-03-13', 'INTP.JK'),
 ('2009-03-13', 'UNTR.JK'),
 ('2009-03-14', 'INCO.JK'),
 ('2009-03-14', 'INDF.JK'),
 ('2009-03-14', 'INTP.JK'),
 ('2009-03-14', 'UNTR.JK'),
 ('2009-03-15', 'INCO.JK'),
 ('2009-03-15', 'INDF.JK'),
 ('2009-03-15', 'INTP.JK'),
 ('2009-03-15', 'UNTR.JK'),
 ('2009-03-16', 'INCO.JK'),
 ('2009-03-16', 'INDF.JK'),
 ('2009-03-16', 'INTP.JK'),
 ('2009-03-16', 'UNTR.JK'),
 ('2009-03-17', 'INCO.JK'),
 ('2009-03-17', 'INDF.JK'),
 ('2009-03-17', 'INTP.JK'),
 ('2009-03-17', 'UNTR.JK'),
 ('2009-03-18', 'INCO.JK'),
 ('2009-03-18', 'INDF.JK'),
 ('2009-03-18', 'INTP.JK'),
 ('2009-03-18', 'UNTR.JK'),
 ('2009-03-19', 'INCO.JK'),
 ('2009-03-19', 'INDF.JK'),
 ('2009-03-19', 'INTP.JK'),
 ('2009-03-19', 'UNTR.JK'),
 ('2009-03-20', 'INCO.JK'),
 ('2009-03-20', 'INDF.JK'),
 ('2009-03-20', 'INTP.JK'),
 ('2009-03-20', 'UNTR.JK'),
 ('2009-03-21', 'INCO.JK'),
 ('2009-03-21', 'INDF.JK'),
 ('2009-03-21', 'INTP.JK'),
 ('2009-03-21', 'UNTR.JK'),
 ('2009-03-22', 'INCO.JK'),
 ('2009-03-22', 'INDF.JK'),
 ('2009-03-22', 'INTP.JK'),
 ('2009-03-22', 'UNTR.JK'),
 ('2009-03-23', 'INCO.JK'),
 ('2009-03-23', 'INDF.JK'),
 ('2009-03-23', 'INTP.JK'),
 ('2009-03-23', 'UNTR.JK'),
 ('2009-03-24', 'INCO.JK'),
 ('2009-03-24', 'INDF.JK'),
 ('2009-03-24', 'INTP.JK'),
 ('2009-03-24', 'UNTR.JK'),
 ('2009-03-25', 'INCO.JK'),
 ('2009-03-25', 'INDF.JK'),
 ('2009-03-25', 'INTP.JK'),
 ('2009-03-25', 'UNTR.JK'),
 ('2009-03-26', 'INCO.JK'),
 ('2009-03-26', 'INDF.JK'),
 ('2009-03-26', 'INTP.JK'),
 ('2009-03-26', 'UNTR.JK'),
 ('2009-03-27', 'INCO.JK'),
 ('2009-03-27', 'INDF.JK'),
 ('2009-03-27', 'INTP.JK'),
 ('2009-03-27', 'UNTR.JK'),
 ('2009-03-28', 'INCO.JK'),
 ('2009-03-28', 'INDF.JK'),
 ('2009-03-28', 'INTP.JK'),
 ('2009-03-28', 'UNTR.JK'),
 ('2009-03-29', 'INCO.JK'),
 ('2009-03-29', 'INDF.JK'),
 ('2009-03-29', 'INTP.JK'),
 ('2009-03-29', 'UNTR.JK'),
 ('2009-03-30', 'INCO.JK'),
 ('2009-03-30', 'INDF.JK'),
 ('2009-03-30', 'INTP.JK'),
 ('2009-03-30', 'UNTR.JK'),
 ('2009-03-31', 'INCO.JK'),
 ('2009-03-31', 'INDF.JK'),
 ('2009-03-31', 'INTP.JK'),
 ('2009-03-31', 'UNTR.JK'),
 ('2009-04-01', 'INCO.JK'),
 ('2009-04-01', 'INDF.JK'),
 ('2009-04-01', 'INTP.JK'),
 ('2009-04-01', 'UNTR.JK'),
 ('2009-04-02', 'INCO.JK'),
 ('2009-04-02', 'INDF.JK'),
 ('2009-04-02', 'INTP.JK'),
 ('2009-04-02', 'UNTR.JK'),
 ('2009-04-03', 'INCO.JK'),
 ('2009-04-03', 'INDF.JK'),
 ('2009-04-03', 'INTP.JK'),
 ('2009-04-03', 'UNTR.JK'),
 ('2009-04-04', 'INCO.JK'),
 ('2009-04-04', 'INDF.JK'),
 ('2009-04-04', 'INTP.JK'),
 ('2009-04-04', 'UNTR.JK'),
 ('2009-04-05', 'INCO.JK'),
 ('2009-04-05', 'INDF.JK'),
 ('2009-04-05', 'INTP.JK'),
 ('2009-04-05', 'UNTR.JK'),
 ('2009-04-06', 'INCO.JK'),
 ('2009-04-06', 'INDF.JK'),
 ('2009-04-06', 'INTP.JK'),
 ('2009-04-06', 'UNTR.JK'),
 ('2009-04-07', 'INCO.JK'),
 ('2009-04-07', 'INDF.JK'),
 ('2009-04-07', 'INTP.JK'),
 ('2009-04-07', 'UNTR.JK'),
 ('2009-04-08', 'INCO.JK'),
 ('2009-04-08', 'INDF.JK'),
 ('2009-04-08', 'INTP.JK'),
 ('2009-04-08', 'UNTR.JK'),
 ('2009-04-09', 'INCO.JK'),
 ('2009-04-09', 'INDF.JK'),
 ('2009-04-09', 'INTP.JK'),
 ('2009-04-09', 'UNTR.JK'),
 ('2009-04-10', 'INCO.JK'),
 ('2009-04-10', 'INDF.JK'),
 ('2009-04-10', 'INTP.JK'),
 ('2009-04-10', 'UNTR.JK'),
 ('2009-04-11', 'INCO.JK'),
 ('2009-04-11', 'INDF.JK'),
 ('2009-04-11', 'INTP.JK'),
 ('2009-04-11', 'UNTR.JK'),
 ('2009-04-12', 'INCO.JK'),
 ('2009-04-12', 'INDF.JK'),
 ('2009-04-12', 'INTP.JK'),
 ('2009-04-12', 'UNTR.JK'),
 ('2009-04-13', 'INCO.JK'),
 ('2009-04-13', 'INDF.JK'),
 ('2009-04-13', 'INTP.JK'),
 ('2009-04-13', 'UNTR.JK'),
 ('2009-04-14', 'INCO.JK'),
 ('2009-04-14', 'INDF.JK'),
 ('2009-04-14', 'INTP.JK'),
 ('2009-04-14', 'UNTR.JK'),
 ('2009-04-15', 'INCO.JK'),
 ('2009-04-15', 'INDF.JK'),
 ('2009-04-15', 'INTP.JK'),
 ('2009-04-15', 'UNTR.JK'),
 ('2009-04-16', 'INCO.JK'),
 ('2009-04-16', 'INDF.JK'),
 ('2009-04-16', 'INTP.JK'),
 ('2009-04-16', 'UNTR.JK'),
 ('2009-04-17', 'INCO.JK'),
 ('2009-04-17', 'INDF.JK'),
 ('2009-04-17', 'INTP.JK'),
 ('2009-04-17', 'UNTR.JK'),
 ('2009-04-18', 'INCO.JK'),
 ('2009-04-18', 'INDF.JK'),
 ('2009-04-18', 'INTP.JK'),
 ('2009-04-18', 'UNTR.JK'),
 ('2009-04-19', 'INCO.JK'),
 ('2009-04-19', 'INDF.JK'),
 ('2009-04-19', 'INTP.JK'),
 ('2009-04-19', 'UNTR.JK'),
 ('2009-04-20', 'INCO.JK'),
 ('2009-04-20', 'INDF.JK'),
 ('2009-04-20', 'INTP.JK'),
 ('2009-04-20', 'UNTR.JK'),
 ('2009-04-21', 'INCO.JK'),
 ('2009-04-21', 'INDF.JK'),
 ('2009-04-21', 'INTP.JK'),
 ('2009-04-21', 'UNTR.JK'),
 ('2009-04-22', 'INCO.JK'),
 ('2009-04-22', 'INDF.JK'),
 ('2009-04-22', 'INTP.JK'),
 ('2009-04-22', 'UNTR.JK'),
 ('2009-04-23', 'INCO.JK'),
 ('2009-04-23', 'INDF.JK'),
 ('2009-04-23', 'INTP.JK'),
 ('2009-04-23', 'UNTR.JK'),
 ('2009-04-24', 'INCO.JK'),
 ('2009-04-24', 'INDF.JK'),
 ('2009-04-24', 'INTP.JK'),
 ('2009-04-24', 'UNTR.JK'),
 ('2009-04-25', 'INCO.JK'),
 ('2009-04-25', 'INDF.JK'),
 ('2009-04-25', 'INTP.JK'),
 ('2009-04-25', 'UNTR.JK'),
 ('2009-04-26', 'INCO.JK'),
 ('2009-04-26', 'INDF.JK'),
 ('2009-04-26', 'INTP.JK'),
 ('2009-04-26', 'UNTR.JK'),
 ('2009-04-27', 'INCO.JK'),
 ('2009-04-27', 'INDF.JK'),
 ('2009-04-27', 'INTP.JK'),
 ('2009-04-27', 'UNTR.JK'),
 ('2009-04-28', 'INCO.JK'),
 ('2009-04-28', 'INDF.JK'),
 ('2009-04-28', 'INTP.JK'),
 ('2009-04-28', 'UNTR.JK'),
 ('2009-04-29', 'INCO.JK'),
 ('2009-04-29', 'INDF.JK'),
 ('2009-04-29', 'INTP.JK'),
 ('2009-04-29', 'UNTR.JK'),
 ('2009-04-30', 'INCO.JK'),
 ('2009-04-30', 'INDF.JK'),
 ('2009-04-30', 'INTP.JK'),
 ('2009-04-30', 'UNTR.JK'),
 ('2009-05-01', 'INCO.JK'),
 ('2009-05-01', 'INDF.JK'),
 ('2009-05-01', 'INTP.JK'),
 ('2009-05-01', 'UNTR.JK'),
 ('2009-05-02', 'INCO.JK'),
 ('2009-05-02', 'INDF.JK'),
 ('2009-05-02', 'INTP.JK'),
 ('2009-05-02', 'UNTR.JK'),
 ('2009-05-03', 'INCO.JK'),
 ('2009-05-03', 'INDF.JK'),
 ('2009-05-03', 'INTP.JK'),
 ('2009-05-03', 'UNTR.JK'),
 ('2009-05-04', 'INCO.JK'),
 ('2009-05-04', 'INDF.JK'),
 ('2009-05-04', 'INTP.JK'),
 ('2009-05-04', 'UNTR.JK'),
 ('2009-05-05', 'INCO.JK'),
 ('2009-05-05', 'INDF.JK'),
 ('2009-05-05', 'INTP.JK'),
 ('2009-05-05', 'UNTR.JK'),
 ('2009-05-06', 'INCO.JK'),
 ('2009-05-06', 'INDF.JK'),
 ('2009-05-06', 'INTP.JK'),
 ('2009-05-06', 'UNTR.JK'),
 ('2009-05-07', 'INCO.JK'),
 ('2009-05-07', 'INDF.JK'),
 ('2009-05-07', 'INTP.JK'),
 ('2009-05-07', 'UNTR.JK'),
 ('2009-05-08', 'INCO.JK'),
 ('2009-05-08', 'INDF.JK'),
 ('2009-05-08', 'INTP.JK'),
 ('2009-05-08', 'UNTR.JK'),
 ('2009-05-09', 'INCO.JK'),
 ('2009-05-09', 'INDF.JK'),
 ('2009-05-09', 'INTP.JK'),
 ('2009-05-09', 'UNTR.JK'),
 ('2009-05-10', 'INCO.JK'),
 ('2009-05-10', 'INDF.JK'),
 ('2009-05-10', 'INTP.JK'),
 ('2009-05-10', 'UNTR.JK'),
 ('2009-05-11', 'INCO.JK'),
 ('2009-05-11', 'INDF.JK'),
 ('2009-05-11', 'INTP.JK'),
 ('2009-05-11', 'UNTR.JK'),
 ('2009-05-12', 'INCO.JK'),
 ('2009-05-12', 'INDF.JK'),
 ('2009-05-12', 'INTP.JK'),
 ('2009-05-12', 'UNTR.JK'),
 ('2009-05-13', 'INCO.JK'),
 ('2009-05-13', 'INDF.JK'),
 ('2009-05-13', 'INTP.JK'),
 ('2009-05-13', 'UNTR.JK'),
 ('2009-05-14', 'INCO.JK'),
 ('2009-05-14', 'INDF.JK'),
 ('2009-05-14', 'INTP.JK'),
 ('2009-05-14', 'UNTR.JK'),
 ('2009-05-15', 'INCO.JK'),
 ('2009-05-15', 'INDF.JK'),
 ('2009-05-15', 'INTP.JK'),
 ('2009-05-15', 'UNTR.JK'),
 ('2009-05-16', 'INCO.JK'),
 ('2009-05-16', 'INDF.JK'),
 ('2009-05-16', 'INTP.JK'),
 ('2009-05-16', 'UNTR.JK'),
 ('2009-05-17', 'INCO.JK'),
 ('2009-05-17', 'INDF.JK'),
 ('2009-05-17', 'INTP.JK'),
 ('2009-05-17', 'UNTR.JK'),
 ('2009-05-18', 'INCO.JK'),
 ('2009-05-18', 'INDF.JK'),
 ('2009-05-18', 'INTP.JK'),
 ('2009-05-18', 'UNTR.JK'),
 ('2009-05-19', 'INCO.JK'),
 ('2009-05-19', 'INDF.JK'),
 ('2009-05-19', 'INTP.JK'),
 ('2009-05-19', 'UNTR.JK'),
 ('2009-05-20', 'INCO.JK'),
 ('2009-05-20', 'INDF.JK'),
 ('2009-05-20', 'INTP.JK'),
 ('2009-05-20', 'UNTR.JK'),
 ('2009-05-21', 'INCO.JK'),
 ('2009-05-21', 'INDF.JK'),
 ('2009-05-21', 'INTP.JK'),
 ('2009-05-21', 'UNTR.JK'),
 ('2009-05-22', 'INCO.JK'),
 ('2009-05-22', 'INDF.JK'),
 ('2009-05-22', 'INTP.JK'),
 ('2009-05-22', 'UNTR.JK'),
 ('2009-05-23', 'INCO.JK'),
 ('2009-05-23', 'INDF.JK'),
 ('2009-05-23', 'INTP.JK'),
 ('2009-05-23', 'UNTR.JK'),
 ('2009-05-24', 'INCO.JK'),
 ('2009-05-24', 'INDF.JK'),
 ('2009-05-24', 'INTP.JK'),
 ('2009-05-24', 'UNTR.JK'),
 ('2009-05-25', 'INCO.JK'),
 ('2009-05-25', 'INDF.JK'),
 ('2009-05-25', 'INTP.JK'),
 ('2009-05-25', 'UNTR.JK'),
 ('2009-05-26', 'INCO.JK'),
 ('2009-05-26', 'INDF.JK'),
 ('2009-05-26', 'INTP.JK'),
 ('2009-05-26', 'UNTR.JK'),
 ('2009-05-27', 'INCO.JK'),
 ('2009-05-27', 'INDF.JK'),
 ('2009-05-27', 'INTP.JK'),
 ('2009-05-27', 'UNTR.JK'),
 ('2009-05-28', 'INCO.JK'),
 ('2009-05-28', 'INDF.JK'),
 ('2009-05-28', 'INTP.JK'),
 ('2009-05-28', 'UNTR.JK'),
 ('2009-05-29', 'INCO.JK'),
 ('2009-05-29', 'INDF.JK'),
 ('2009-05-29', 'INTP.JK'),
 ('2009-05-29', 'UNTR.JK'),
 ('2009-05-30', 'INCO.JK'),
 ('2009-05-30', 'INDF.JK'),
 ('2009-05-30', 'INTP.JK'),
 ('2009-05-30', 'UNTR.JK'),
 ('2009-05-31', 'INCO.JK'),
 ('2009-05-31', 'INDF.JK'),
 ('2009-05-31', 'INTP.JK'),
 ('2009-05-31', 'UNTR.JK'),
 ('2009-06-01', 'INCO.JK'),
 ('2009-06-01', 'INDF.JK'),
 ('2009-06-01', 'INTP.JK'),
 ('2009-06-01', 'UNTR.JK'),
 ('2009-06-02', 'INCO.JK'),
 ('2009-06-02', 'INDF.JK'),
 ('2009-06-02', 'INTP.JK'),
 ('2009-06-02', 'UNTR.JK'),
 ('2009-06-03', 'INCO.JK'),
 ('2009-06-03', 'INDF.JK'),
 ('2009-06-03', 'INTP.JK'),
 ('2009-06-03', 'UNTR.JK'),
 ('2009-06-04', 'INCO.JK'),
 ('2009-06-04', 'INDF.JK'),
 ('2009-06-04', 'INTP.JK'),
 ('2009-06-04', 'UNTR.JK'),
 ('2009-06-05', 'INCO.JK'),
 ('2009-06-05', 'INDF.JK'),
 ('2009-06-05', 'INTP.JK'),
 ('2009-06-05', 'UNTR.JK'),
 ('2009-06-06', 'INCO.JK'),
 ('2009-06-06', 'INDF.JK'),
 ('2009-06-06', 'INTP.JK'),
 ('2009-06-06', 'UNTR.JK'),
 ('2009-06-07', 'INCO.JK'),
 ('2009-06-07', 'INDF.JK'),
 ('2009-06-07', 'INTP.JK'),
 ('2009-06-07', 'UNTR.JK'),
 ('2009-06-08', 'INCO.JK'),
 ('2009-06-08', 'INDF.JK'),
 ('2009-06-08', 'INTP.JK'),
 ('2009-06-08', 'UNTR.JK'),
 ('2009-06-09', 'INCO.JK'),
 ('2009-06-09', 'INDF.JK'),
 ('2009-06-09', 'INTP.JK'),
 ('2009-06-09', 'UNTR.JK'),
 ('2009-06-10', 'INCO.JK'),
 ('2009-06-10', 'INDF.JK'),
 ('2009-06-10', 'INTP.JK'),
 ('2009-06-10', 'UNTR.JK'),
 ('2009-06-11', 'INCO.JK'),
 ('2009-06-11', 'INDF.JK'),
 ('2009-06-11', 'INTP.JK'),
 ('2009-06-11', 'UNTR.JK'),
 ('2009-06-12', 'INCO.JK'),
 ('2009-06-12', 'INDF.JK'),
 ('2009-06-12', 'INTP.JK'),
 ('2009-06-12', 'UNTR.JK'),
 ('2009-06-13', 'INCO.JK'),
 ('2009-06-13', 'INDF.JK'),
 ('2009-06-13', 'INTP.JK'),
 ('2009-06-13', 'UNTR.JK'),
 ('2009-06-14', 'INCO.JK'),
 ('2009-06-14', 'INDF.JK'),
 ('2009-06-14', 'INTP.JK'),
 ('2009-06-14', 'UNTR.JK'),
 ('2009-06-15', 'INCO.JK'),
 ('2009-06-15', 'INDF.JK'),
 ('2009-06-15', 'INTP.JK'),
 ('2009-06-15', 'UNTR.JK'),
 ('2009-06-16', 'INCO.JK'),
 ('2009-06-16', 'INDF.JK'),
 ('2009-06-16', 'INTP.JK'),
 ('2009-06-16', 'UNTR.JK'),
 ('2009-06-17', 'INCO.JK'),
 ('2009-06-17', 'INDF.JK'),
 ('2009-06-17', 'INTP.JK'),
 ('2009-06-17', 'UNTR.JK'),
 ('2009-06-18', 'INCO.JK'),
 ('2009-06-18', 'INDF.JK'),
 ('2009-06-18', 'INTP.JK'),
 ('2009-06-18', 'UNTR.JK'),
 ('2009-06-19', 'INCO.JK'),
 ('2009-06-19', 'INDF.JK'),
 ('2009-06-19', 'INTP.JK'),
 ('2009-06-19', 'UNTR.JK'),
 ('2009-06-20', 'INCO.JK'),
 ('2009-06-20', 'INDF.JK'),
 ('2009-06-20', 'INTP.JK'),
 ('2009-06-20', 'UNTR.JK'),
 ('2009-06-21', 'INCO.JK'),
 ('2009-06-21', 'INDF.JK'),
 ('2009-06-21', 'INTP.JK'),
 ('2009-06-21', 'UNTR.JK'),
 ('2009-06-22', 'INCO.JK'),
 ('2009-06-22', 'INDF.JK'),
 ('2009-06-22', 'INTP.JK'),
 ('2009-06-22', 'UNTR.JK'),
 ('2009-06-23', 'INCO.JK'),
 ('2009-06-23', 'INDF.JK'),
 ('2009-06-23', 'INTP.JK'),
 ('2009-06-23', 'UNTR.JK'),
 ('2009-06-24', 'INCO.JK'),
 ('2009-06-24', 'INDF.JK'),
 ('2009-06-24', 'INTP.JK'),
 ('2009-06-24', 'UNTR.JK'),
 ('2009-06-25', 'INCO.JK'),
 ('2009-06-25', 'INDF.JK'),
 ('2009-06-25', 'INTP.JK'),
 ('2009-06-25', 'UNTR.JK'),
 ('2009-06-26', 'INCO.JK'),
 ('2009-06-26', 'INDF.JK'),
 ('2009-06-26', 'INTP.JK'),
 ('2009-06-26', 'UNTR.JK'),
 ('2009-06-27', 'INCO.JK'),
 ('2009-06-27', 'INDF.JK'),
 ('2009-06-27', 'INTP.JK'),
 ('2009-06-27', 'UNTR.JK'),
 ('2009-06-28', 'INCO.JK'),
 ('2009-06-28', 'INDF.JK'),
 ('2009-06-28', 'INTP.JK'),
 ('2009-06-28', 'UNTR.JK'),
 ('2009-06-29', 'INCO.JK'),
 ('2009-06-29', 'INDF.JK'),
 ('2009-06-29', 'INTP.JK'),
 ('2009-06-29', 'UNTR.JK'),
 ('2009-06-30', 'INCO.JK'),
 ('2009-06-30', 'INDF.JK'),
 ('2009-06-30', 'INTP.JK'),
 ('2009-06-30', 'UNTR.JK'),
 ('2009-07-01', 'INCO.JK'),
 ('2009-07-01', 'INDF.JK'),
 ('2009-07-01', 'INTP.JK'),
 ('2009-07-01', 'UNTR.JK'),
 ('2009-07-02', 'INCO.JK'),
 ('2009-07-02', 'INDF.JK'),

In [169]:
processed_full = pd.DataFrame(combination,columns=["date","tic"]).merge(processed,on=["date","tic"],how="left")
processed_full

,date,tic,open,high,low,close,volume,day,macd,rsi_30,cci_30,vix,turbulence
0,2009-01-05,INCO.JK,2050.000000,2300.000000,2030.000000,1792.011108,30353500.0,0.0,0.000000,0.000000,66.666667,39.080002,0.000000
1,2009-01-05,INDF.JK,980.000000,980.000000,920.000000,638.533020,154640500.0,0.0,0.000000,0.000000,66.666667,39.080002,0.000000
2,2009-01-05,INTP.JK,4600.000000,5050.000000,4600.000000,3106.131348,3534000.0,0.0,0.000000,0.000000,66.666667,39.080002,0.000000
3,2009-01-05,UNTR.JK,4326.423828,5071.530273,4326.423828,3122.125000,25673281.0,0.0,0.000000,0.000000,66.666667,39.080002,0.000000
4,2009-01-06,INCO.JK,2300.000000,2325.000000,2100.000000,1733.576050,21013000.0,1.0,-1.311043,0.000000,66.666667,38.560001,0.000000
...,...,...,...,...,...,...,...,...,...,...,...,...,...
15995,2019-12-17,UNTR.JK,22000.000000,22375.000000,21750.000000,19864.076172,4607100.0,1.0,-78.720722,52.760267,20.354854,12.290000,0.951753
15996,2019-12-18,INCO.JK,3600.000000,3600.000000,3440.000000,3418.002930,14110300.0,2.0,27.673484,51.602337,90.205381,12.580000,4.030014
15997,2019-12-18,INDF.JK,7975.000000,7975.000000,7900.000000,7000.262695,8303900.0,2.0,11.639580,53.440024,59.891985,12.580000,4.030014
15998,2019-12-18,INTP.JK,20000.000000,20075.000000,19800.000000,17098.693359,2290000.0,2.0,-13.626001,49.586670,-17.159791,12.580000,4.030014
15999,2019-12-18,UNTR.JK,22300.000000,22325.000000,21800.000000,19353.603516,3803500.0,2.0,-49.095959,50.405708,6.805599,12.580000,4.030014

In [170]:
processed_full = processed_full[processed_full['date'].isin(processed['date'])]
processed_full

,date,tic,open,high,low,close,volume,day,macd,rsi_30,cci_30,vix,turbulence
0,2009-01-05,INCO.JK,2050.000000,2300.000000,2030.000000,1792.011108,30353500.0,0.0,0.000000,0.000000,66.666667,39.080002,0.000000
1,2009-01-05,INDF.JK,980.000000,980.000000,920.000000,638.533020,154640500.0,0.0,0.000000,0.000000,66.666667,39.080002,0.000000
2,2009-01-05,INTP.JK,4600.000000,5050.000000,4600.000000,3106.131348,3534000.0,0.0,0.000000,0.000000,66.666667,39.080002,0.000000
3,2009-01-05,UNTR.JK,4326.423828,5071.530273,4326.423828,3122.125000,25673281.0,0.0,0.000000,0.000000,66.666667,39.080002,0.000000
4,2009-01-06,INCO.JK,2300.000000,2325.000000,2100.000000,1733.576050,21013000.0,1.0,-1.311043,0.000000,66.666667,38.560001,0.000000
...,...,...,...,...,...,...,...,...,...,...,...,...,...
15995,2019-12-17,UNTR.JK,22000.000000,22375.000000,21750.000000,19864.076172,4607100.0,1.0,-78.720722,52.760267,20.354854,12.290000,0.951753
15996,2019-12-18,INCO.JK,3600.000000,3600.000000,3440.000000,3418.002930,14110300.0,2.0,27.673484,51.602337,90.205381,12.580000,4.030014
15997,2019-12-18,INDF.JK,7975.000000,7975.000000,7900.000000,7000.262695,8303900.0,2.0,11.639580,53.440024,59.891985,12.580000,4.030014
15998,2019-12-18,INTP.JK,20000.000000,20075.000000,19800.000000,17098.693359,2290000.0,2.0,-13.626001,49.586670,-17.159791,12.580000,4.030014
15999,2019-12-18,UNTR.JK,22300.000000,22325.000000,21800.000000,19353.603516,3803500.0,2.0,-49.095959,50.405708,6.805599,12.580000,4.030014

In [171]:
processed_full = processed_full.sort_values(['date','tic'])
processed_full

,date,tic,open,high,low,close,volume,day,macd,rsi_30,cci_30,vix,turbulence
0,2009-01-05,INCO.JK,2050.000000,2300.000000,2030.000000,1792.011108,30353500.0,0.0,0.000000,0.000000,66.666667,39.080002,0.000000
1,2009-01-05,INDF.JK,980.000000,980.000000,920.000000,638.533020,154640500.0,0.0,0.000000,0.000000,66.666667,39.080002,0.000000
2,2009-01-05,INTP.JK,4600.000000,5050.000000,4600.000000,3106.131348,3534000.0,0.0,0.000000,0.000000,66.666667,39.080002,0.000000
3,2009-01-05,UNTR.JK,4326.423828,5071.530273,4326.423828,3122.125000,25673281.0,0.0,0.000000,0.000000,66.666667,39.080002,0.000000
4,2009-01-06,INCO.JK,2300.000000,2325.000000,2100.000000,1733.576050,21013000.0,1.0,-1.311043,0.000000,66.666667,38.560001,0.000000
...,...,...,...,...,...,...,...,...,...,...,...,...,...
15995,2019-12-17,UNTR.JK,22000.000000,22375.000000,21750.000000,19864.076172,4607100.0,1.0,-78.720722,52.760267,20.354854,12.290000,0.951753
15996,2019-12-18,INCO.JK,3600.000000,3600.000000,3440.000000,3418.002930,14110300.0,2.0,27.673484,51.602337,90.205381,12.580000,4.030014
15997,2019-12-18,INDF.JK,7975.000000,7975.000000,7900.000000,7000.262695,8303900.0,2.0,11.639580,53.440024,59.891985,12.580000,4.030014
15998,2019-12-18,INTP.JK,20000.000000,20075.000000,19800.000000,17098.693359,2290000.0,2.0,-13.626001,49.586670,-17.159791,12.580000,4.030014
15999,2019-12-18,UNTR.JK,22300.000000,22325.000000,21800.000000,19353.603516,3803500.0,2.0,-49.095959,50.405708,6.805599,12.580000,4.030014

In [172]:
processed_full = processed_full.fillna(0)
processed_full

,date,tic,open,high,low,close,volume,day,macd,rsi_30,cci_30,vix,turbulence
0,2009-01-05,INCO.JK,2050.000000,2300.000000,2030.000000,1792.011108,30353500.0,0.0,0.000000,0.000000,66.666667,39.080002,0.000000
1,2009-01-05,INDF.JK,980.000000,980.000000,920.000000,638.533020,154640500.0,0.0,0.000000,0.000000,66.666667,39.080002,0.000000
2,2009-01-05,INTP.JK,4600.000000,5050.000000,4600.000000,3106.131348,3534000.0,0.0,0.000000,0.000000,66.666667,39.080002,0.000000
3,2009-01-05,UNTR.JK,4326.423828,5071.530273,4326.423828,3122.125000,25673281.0,0.0,0.000000,0.000000,66.666667,39.080002,0.000000
4,2009-01-06,INCO.JK,2300.000000,2325.000000,2100.000000,1733.576050,21013000.0,1.0,-1.311043,0.000000,66.666667,38.560001,0.000000
...,...,...,...,...,...,...,...,...,...,...,...,...,...
15995,2019-12-17,UNTR.JK,22000.000000,22375.000000,21750.000000,19864.076172,4607100.0,1.0,-78.720722,52.760267,20.354854,12.290000,0.951753
15996,2019-12-18,INCO.JK,3600.000000,3600.000000,3440.000000,3418.002930,14110300.0,2.0,27.673484,51.602337,90.205381,12.580000,4.030014
15997,2019-12-18,INDF.JK,7975.000000,7975.000000,7900.000000,7000.262695,8303900.0,2.0,11.639580,53.440024,59.891985,12.580000,4.030014
15998,2019-12-18,INTP.JK,20000.000000,20075.000000,19800.000000,17098.693359,2290000.0,2.0,-13.626001,49.586670,-17.159791,12.580000,4.030014
15999,2019-12-18,UNTR.JK,22300.000000,22325.000000,21800.000000,19353.603516,3803500.0,2.0,-49.095959,50.405708,6.805599,12.580000,4.030014

In [173]:
processed_full.sort_values(['date','tic'],ignore_index=True).head(10)

,date,tic,open,high,low,close,volume,day,macd,rsi_30,cci_30,vix,turbulence
0,2009-01-05,INCO.JK,2050.000000,2300.000000,2030.000000,1792.011108,30353500.0,0.0,0.000000,0.0000,66.666667,39.080002,0.0
1,2009-01-05,INDF.JK,980.000000,980.000000,920.000000,638.533020,154640500.0,0.0,0.000000,0.0000,66.666667,39.080002,0.0
2,2009-01-05,INTP.JK,4600.000000,5050.000000,4600.000000,3106.131348,3534000.0,0.0,0.000000,0.0000,66.666667,39.080002,0.0
3,2009-01-05,UNTR.JK,4326.423828,5071.530273,4326.423828,3122.125000,25673281.0,0.0,0.000000,0.0000,66.666667,39.080002,0.0
4,2009-01-06,INCO.JK,2300.000000,2325.000000,2100.000000,1733.576050,21013000.0,1.0,-1.311043,0.0000,66.666667,38.560001,0.0
5,2009-01-06,INDF.JK,1000.000000,1110.000000,980.000000,664.595459,346017500.0,1.0,0.584734,100.0000,66.666667,38.560001,0.0
6,2009-01-06,INTP.JK,5100.000000,5250.000000,5050.000000,3198.392822,2973000.0,1.0,2.069969,100.0000,66.666667,38.560001,0.0
7,2009-01-06,UNTR.JK,5143.637207,5335.922852,4759.066406,3048.140137,23181674.0,1.0,-1.659917,0.0000,66.666667,38.560001,0.0
8,2009-01-07,INCO.JK,2300.000000,2650.000000,2275.000000,2025.751709,58399500.0,2.0,7.389821,83.7989,100.000000,43.389999,0.0
9,2009-01-07,INDF.JK,1020.000000,1080.000000,1020.000000,664.595459,147142500.0,2.0,0.745067,100.0000,53.392707,43.389999,0.0

In [174]:
processed_full.nunique()

date           2651
tic               4
open           1775
high           1835
low            1809
close          4828
volume         9764
day               5
macd          10601
rsi_30         9608
cci_30        10598
vix            1441
turbulence     2397
dtype: int64

In [175]:
#memperbarui dataframe dengan bentuk harga per lot

processed_full_lot = processed_full[['open','high','low','close']].mul(100)

#drop some columns
processed_full_noOHLC = processed_full.drop(['open','high','low','close'], axis=1)
  
processed_full_lot = pd.concat([processed_full_noOHLC, processed_full_lot], axis=1)

processed_full_lot = processed_full_lot[['date', 'tic', 'open', 'high', 'low', 'close', 'volume', 'day', 'macd', 'rsi_30', 'cci_30', 'vix', 'turbulence']]

processed_full_lot

,date,tic,open,high,low,close,volume,day,macd,rsi_30,cci_30,vix,turbulence
0,2009-01-05,INCO.JK,2.050000e+05,2.300000e+05,2.030000e+05,1.792011e+05,30353500.0,0.0,0.000000,0.000000,66.666667,39.080002,0.000000
1,2009-01-05,INDF.JK,9.800000e+04,9.800000e+04,9.200000e+04,6.385330e+04,154640500.0,0.0,0.000000,0.000000,66.666667,39.080002,0.000000
2,2009-01-05,INTP.JK,4.600000e+05,5.050000e+05,4.600000e+05,3.106131e+05,3534000.0,0.0,0.000000,0.000000,66.666667,39.080002,0.000000
3,2009-01-05,UNTR.JK,4.326424e+05,5.071530e+05,4.326424e+05,3.122125e+05,25673281.0,0.0,0.000000,0.000000,66.666667,39.080002,0.000000
4,2009-01-06,INCO.JK,2.300000e+05,2.325000e+05,2.100000e+05,1.733576e+05,21013000.0,1.0,-1.311043,0.000000,66.666667,38.560001,0.000000
...,...,...,...,...,...,...,...,...,...,...,...,...,...
15995,2019-12-17,UNTR.JK,2.200000e+06,2.237500e+06,2.175000e+06,1.986408e+06,4607100.0,1.0,-78.720722,52.760267,20.354854,12.290000,0.951753
15996,2019-12-18,INCO.JK,3.600000e+05,3.600000e+05,3.440000e+05,3.418003e+05,14110300.0,2.0,27.673484,51.602337,90.205381,12.580000,4.030014
15997,2019-12-18,INDF.JK,7.975000e+05,7.975000e+05,7.900000e+05,7.000263e+05,8303900.0,2.0,11.639580,53.440024,59.891985,12.580000,4.030014
15998,2019-12-18,INTP.JK,2.000000e+06,2.007500e+06,1.980000e+06,1.709869e+06,2290000.0,2.0,-13.626001,49.586670,-17.159791,12.580000,4.030014
15999,2019-12-18,UNTR.JK,2.230000e+06,2.232500e+06,2.180000e+06,1.935360e+06,3803500.0,2.0,-49.095959,50.405708,6.805599,12.580000,4.030014

<a id='4'></a>
# Bagian 5. Membangun Lingkungan Jual-Beli Saham dengan OpenAI Gym-style
Proses *training* meliputi mengamati perubahan harga saham, mengambil tindakan dan perhitungan *reward*. Dengan berinteraksi dengan lingkungan pasar, agen pada akhirnya akan memperoleh strategi perdagangan yang dapat memaksimalkan imbalan.

*Environment* pasar dibangun  menggunakan OpenAI Gym yang mensimulasikan pasar saham dengan data historis pasar.

<a id='4.1'></a>
## 5.1. Memisahkan Data
Data dibagi menjadi dua bagian, yaitu bagian pelatihan dan bagian pengujian dengan keterangan sebagai berikut:

Periode data pelatihan: 2009-01-01 hingga 2017-12-31

Periode data perdagangan: 2018-01-01 hingga 2022-08-15

In [176]:
train = data_split(processed_full_lot, TRAIN_START_DATE,TRAIN_END_DATE)
trade = data_split(processed_full_lot, TRADE_START_DATE,TRADE_END_DATE)
print(len(train))
print(len(trade))

8628
1976

In [177]:
train.tail()

,date,tic,open,high,low,close,volume,day,macd,rsi_30,cci_30,vix,turbulence
2155,2017-12-28,UNTR.JK,3457500.0,3460000.0,3422500.0,2.839685e+06,2636700.0,3.0,297.519264,55.675876,163.784615,10.18,5.337347
2156,2017-12-29,INCO.JK,285000.0,291000.0,285000.0,2.863197e+05,9727700.0,4.0,-6.167929,51.919947,61.612511,11.04,3.007378
2156,2017-12-29,INDF.JK,770000.0,777500.0,760000.0,6.258996e+05,12848100.0,4.0,-15.327242,44.909603,53.529980,11.04,3.007378
2156,2017-12-29,INTP.JK,2150000.0,2195000.0,2150000.0,1.754518e+06,1534000.0,4.0,288.716901,58.947136,197.982394,11.04,3.007378
2156,2017-12-29,UNTR.JK,3460000.0,3540000.0,3457500.0,2.905342e+06,4163100.0,4.0,377.481925,58.036903,202.252693,11.04,3.007378

In [178]:
trade.head()

,date,tic,open,high,low,close,volume,day,macd,rsi_30,cci_30,vix,turbulence
0,2018-01-02,INCO.JK,292000.0,304000.0,292000.0,3.001898e+05,14717300.0,1.0,14.154749,56.639747,165.346926,9.77,13.799046
0,2018-01-02,INDF.JK,765000.0,770000.0,755000.0,6.197431e+05,6875700.0,1.0,-14.552957,43.053745,30.342604,9.77,13.799046
0,2018-01-02,INTP.JK,2195000.0,2300000.0,2135000.0,1.838447e+06,1017900.0,1.0,471.241792,62.624332,199.526837,9.77,13.799046
0,2018-01-02,UNTR.JK,3540000.0,3540000.0,3410000.0,2.802752e+06,3701100.0,1.0,394.737815,53.290365,114.551288,9.77,13.799046
1,2018-01-03,INCO.JK,305000.0,311000.0,304000.0,3.021713e+05,19792900.0,2.0,27.434247,57.259786,215.036026,9.15,4.300823

In [179]:
stock_dimension = len(train.tic.unique())
state_space = 1 + 2*stock_dimension + len(INDICATORS)*stock_dimension
print(f"Stock Dimension: {stock_dimension}, State Space: {state_space}")

Stock Dimension: 4, State Space: 21

In [180]:
buy_cost_list = [0.0023] * stock_dimension
sell_cost_list = [0.0054] * stock_dimension
num_stock_shares = [0] * stock_dimension

env_kwargs = {
    "hmax": 100,
    "initial_amount": 100000000,
    "num_stock_shares": num_stock_shares,
    "buy_cost_pct": buy_cost_list,
    "sell_cost_pct": sell_cost_list,
    "state_space": state_space,
    "stock_dim": stock_dimension,
    "tech_indicator_list": INDICATORS,
    "action_space": stock_dimension,
    "reward_scaling": 1e-4
}


e_train_gym = StockTradingEnv(df = train, **env_kwargs)

<a id='4.2'></a>
## 5.2. Lingkungan untuk Pelatihan *(Training)*

In [181]:
env_train, _ = e_train_gym.get_sb_env()
print(type(env_train))

<class 'stable_baselines3.common.vec_env.dummy_vec_env.DummyVecEnv'>

<a id='5'></a>
# Bagian 6: Melatih Agen DRL
* Algoritma DRL dibangun dengan menggunakan **Stable Baselines 3**. 

* FinRL mencakup algoritma DRL standar yang disempurnakan, seperti DQN, DDPG, DDPG Multi-Agen, PPO, SAC, A2C, dan TD3. FinRL juga mengizinkan pengguna untuk merancang algoritma DRL sendiri dengan mengadaptasi algoritma DRL yang telah disebutkan.

In [182]:
agent = DRLAgent(env = env_train)

**Agent Training: 5 algorithms (A2C, PPO, TD3, SAC, DDPG)**

<a id='5.1'></a>
##6.1. Agen 1: A2C

In [183]:
A2C_PARAMS = {
    "n_steps": 150, 
    "ent_coef": 0.0001, 
    "learning_rate": 0.0014,
}
model_a2c = agent.get_model("a2c",model_kwargs = A2C_PARAMS)

{'n_steps': 150, 'ent_coef': 0.0001, 'learning_rate': 0.0014}
Using cuda device

In [184]:
trained_a2c = agent.train_model(model=model_a2c, 
                             tb_log_name='a2c',
                             total_timesteps=50000)

--------------------------------------
| time/                 |            |
|    fps                | 377        |
|    iterations         | 100        |
|    time_elapsed       | 39         |
|    total_timesteps    | 15000      |
| train/                |            |
|    entropy_loss       | -5.71      |
|    explained_variance | 0.00668    |
|    learning_rate      | 0.0014     |
|    n_updates          | 99         |
|    policy_loss        | -2.32e+03  |
|    reward             | -112.27089 |
|    std                | 1.01       |
|    value_loss         | 2.68e+05   |
--------------------------------------
day: 2156, episode: 10
begin_total_asset: 100000000.00
end_total_asset: 84507574.80
total_reward: -15492425.20
total_cost: 19022643.22
total_trades: 3165
Sharpe: 0.325
=================================
--------------------------------------
| time/                 |            |
|    fps                | 378        |
|    iterations         | 200        |
|    time_elapsed       | 79         |
|    total_timesteps    | 30000      |
| train/                |            |
|    entropy_loss       | -5.74      |
|    explained_variance | 0.000832   |
|    learning_rate      | 0.0014     |
|    n_updates          | 199        |
|    policy_loss        | -513       |
|    reward             | -25.320501 |
|    std                | 1.02       |
|    value_loss         | 1.13e+05   |
--------------------------------------
day: 2156, episode: 20
begin_total_asset: 100000000.00
end_total_asset: 54763616.41
total_reward: -45236383.59
total_cost: 34796586.23
total_trades: 4980
Sharpe: 0.214
=================================
--------------------------------------
| time/                 |            |
|    fps                | 378        |
|    iterations         | 300        |
|    time_elapsed       | 118        |
|    total_timesteps    | 45000      |
| train/                |            |
|    entropy_loss       | -5.74      |
|    explained_variance | 0.00114    |
|    learning_rate      | 0.0014     |
|    n_updates          | 299        |
|    policy_loss        | 1.62e+03   |
|    reward             | -23.363194 |
|    std                | 1.02       |
|    value_loss         | 2.7e+06    |
--------------------------------------

<a id='5.2'></a>
##6.2. Agen 2: PPO

In [185]:
PPO_PARAMS = {
    "n_steps": 50000,
    "ent_coef": 0.7,
    "learning_rate": 0.0016,
    "batch_size": 1750,
}
model_ppo = agent.get_model("ppo",model_kwargs = PPO_PARAMS)

{'n_steps': 50000, 'ent_coef': 0.7, 'learning_rate': 0.0016, 'batch_size': 1750}
Using cuda device

/usr/local/lib/python3.7/dist-packages/stable_baselines3/ppo/ppo.py:147: UserWarning: You have specified a mini-batch size of 1750, but because the `RolloutBuffer` is of size `n_steps * n_envs = 50000`, after every 28 untruncated mini-batches, there will be a truncated mini-batch of size 1000
We recommend using a `batch_size` that is a factor of `n_steps * n_envs`.
Info: (n_steps=50000 and n_envs=1)
  f"You have specified a mini-batch size of {batch_size},"

In [186]:
trained_ppo = agent.train_model(model=model_ppo, 
                             tb_log_name='ppo',
                             total_timesteps=50000)

day: 2156, episode: 30
begin_total_asset: 100000000.00
end_total_asset: 1562788.77
total_reward: -98437211.23
total_cost: 338066907.25
total_trades: 6311
Sharpe: -1.307
=================================
day: 2156, episode: 40
begin_total_asset: 100000000.00
end_total_asset: 193978.99
total_reward: -99806021.01
total_cost: 16589882.59
total_trades: 4994
Sharpe: -1.210
=================================
---------------------------------
| time/              |          |
|    fps             | 382      |
|    iterations      | 1        |
|    time_elapsed    | 130      |
|    total_timesteps | 50000    |
| train/             |          |
|    reward          | 8.093589 |
---------------------------------

<a id='5.3'></a>
##6.3. Agen 3: TD3

In [187]:
TD3_PARAMS = {
    "batch_size": 7000, 
    "buffer_size": 10000, 
    "learning_rate": 0.9  
}
model_td3 = agent.get_model("td3",model_kwargs = TD3_PARAMS)

{'batch_size': 7000, 'buffer_size': 10000, 'learning_rate': 0.9}
Using cuda device

In [188]:
trained_td3 = agent.train_model(model=model_td3, 
                             tb_log_name='td3',
                             total_timesteps=50000)

day: 2156, episode: 50
begin_total_asset: 100000000.00
end_total_asset: 250640694.70
total_reward: 150640694.70
total_cost: 7398972.99
total_trades: 6490
Sharpe: 0.503
=================================
----------------------------------
| time/              |           |
|    episodes        | 4         |
|    fps             | 97        |
|    time_elapsed    | 88        |
|    total_timesteps | 8628      |
| train/             |           |
|    actor_loss      | -5.93     |
|    critic_loss     | 1.48e+05  |
|    learning_rate   | 0.9       |
|    n_updates       | 6471      |
|    reward          | 236.36601 |
----------------------------------
----------------------------------
| time/              |           |
|    episodes        | 8         |
|    fps             | 86        |
|    time_elapsed    | 199       |
|    total_timesteps | 17256     |
| train/             |           |
|    actor_loss      | -3.92     |
|    critic_loss     | 9.7e+04   |
|    learning_rate   | 0.9       |
|    n_updates       | 15099     |
|    reward          | 236.36601 |
----------------------------------
day: 2156, episode: 60
begin_total_asset: 100000000.00
end_total_asset: 104628785.48
total_reward: 4628785.48
total_cost: 233383.87
total_trades: 6322
Sharpe: 0.475
=================================
----------------------------------
| time/              |           |
|    episodes        | 12        |
|    fps             | 83        |
|    time_elapsed    | 309       |
|    total_timesteps | 25884     |
| train/             |           |
|    actor_loss      | -3.91     |
|    critic_loss     | 9.74e+04  |
|    learning_rate   | 0.9       |
|    n_updates       | 23727     |
|    reward          | 236.36601 |
----------------------------------
----------------------------------
| time/              |           |
|    episodes        | 16        |
|    fps             | 82        |
|    time_elapsed    | 420       |
|    total_timesteps | 34512     |
| train/             |           |
|    actor_loss      | 45.1      |
|    critic_loss     | 9.64e+04  |
|    learning_rate   | 0.9       |
|    n_updates       | 32355     |
|    reward          | 236.36601 |
----------------------------------
----------------------------------
| time/              |           |
|    episodes        | 20        |
|    fps             | 81        |
|    time_elapsed    | 531       |
|    total_timesteps | 43140     |
| train/             |           |
|    actor_loss      | 32.9      |
|    critic_loss     | 9.7e+04   |
|    learning_rate   | 0.9       |
|    n_updates       | 40983     |
|    reward          | 236.36601 |
----------------------------------
day: 2156, episode: 70
begin_total_asset: 100000000.00
end_total_asset: 104628785.48
total_reward: 4628785.48
total_cost: 233383.87
total_trades: 6322
Sharpe: 0.475
=================================
----------------------------------
| time/              |           |
|    episodes        | 24        |
|    fps             | 80        |
|    time_elapsed    | 642       |
|    total_timesteps | 51768     |
| train/             |           |
|    actor_loss      | 14.7      |
|    critic_loss     | 9.59e+04  |
|    learning_rate   | 0.9       |
|    n_updates       | 49611     |
|    reward          | 236.36601 |
----------------------------------

<a id='5.4'></a>
##6.4. Agen 4: SAC

In [189]:
SAC_PARAMS = {
    "ent_coef": 1.25,
    "learning_rate": 0.0001,
    "batch_size": 4000,
    "buffer_size": 5000,
    "learning_starts": 14,
    
}
model_sac = agent.get_model("sac",model_kwargs = SAC_PARAMS)

{'ent_coef': 1.25, 'learning_rate': 0.0001, 'batch_size': 4000, 'buffer_size': 5000, 'learning_starts': 14}
Using cuda device

In [190]:
trained_sac = agent.train_model(model=model_sac, 
                             tb_log_name='sac',
                             total_timesteps=30000)

----------------------------------
| time/              |           |
|    episodes        | 4         |
|    fps             | 68        |
|    time_elapsed    | 125       |
|    total_timesteps | 8628      |
| train/             |           |
|    actor_loss      | 2.59e+04  |
|    critic_loss     | 4.82e+05  |
|    ent_coef        | 1.25      |
|    learning_rate   | 0.0001    |
|    n_updates       | 8613      |
|    reward          | 105.21518 |
----------------------------------
day: 2156, episode: 80
begin_total_asset: 100000000.00
end_total_asset: 50728367.76
total_reward: -49271632.24
total_cost: 331971.37
total_trades: 2160
Sharpe: 0.170
=================================
----------------------------------
| time/              |           |
|    episodes        | 8         |
|    fps             | 68        |
|    time_elapsed    | 252       |
|    total_timesteps | 17256     |
| train/             |           |
|    actor_loss      | 2.25e+04  |
|    critic_loss     | 2.92e+05  |
|    ent_coef        | 1.25      |
|    learning_rate   | 0.0001    |
|    n_updates       | 17241     |
|    reward          | 105.21518 |
----------------------------------
----------------------------------
| time/              |           |
|    episodes        | 12        |
|    fps             | 68        |
|    time_elapsed    | 380       |
|    total_timesteps | 25884     |
| train/             |           |
|    actor_loss      | 1.94e+04  |
|    critic_loss     | 2.41e+05  |
|    ent_coef        | 1.25      |
|    learning_rate   | 0.0001    |
|    n_updates       | 25869     |
|    reward          | 105.21518 |
----------------------------------

<a id='5.5'></a>
##6.5. Agen 5: DDPG

In [191]:
DDPG_PARAMS = {
    "batch_size": 1250, 
    "buffer_size": 50000, 
    "learning_rate": 0.0003
}
model_ddpg = agent.get_model("ddpg",model_kwargs = DDPG_PARAMS)

{'batch_size': 1250, 'buffer_size': 50000, 'learning_rate': 0.0003}
Using cuda device

In [192]:
trained_ddpg = agent.train_model(model=model_ddpg, 
                             tb_log_name='ddpg',
                             total_timesteps=60000)

day: 2156, episode: 90
begin_total_asset: 100000000.00
end_total_asset: 99927062.79
total_reward: -72937.21
total_cost: 229471.84
total_trades: 6468
Sharpe: 0.464
=================================
----------------------------------
| time/              |           |
|    episodes        | 4         |
|    fps             | 128       |
|    time_elapsed    | 67        |
|    total_timesteps | 8628      |
| train/             |           |
|    actor_loss      | -2.31e+03 |
|    critic_loss     | 2.18e+07  |
|    learning_rate   | 0.0003    |
|    n_updates       | 6471      |
|    reward          | 225.61232 |
----------------------------------
----------------------------------
| time/              |           |
|    episodes        | 8         |
|    fps             | 114       |
|    time_elapsed    | 150       |
|    total_timesteps | 17256     |
| train/             |           |
|    actor_loss      | -881      |
|    critic_loss     | 1.91e+06  |
|    learning_rate   | 0.0003    |
|    n_updates       | 15099     |
|    reward          | 225.61232 |
----------------------------------
day: 2156, episode: 100
begin_total_asset: 100000000.00
end_total_asset: 99927062.79
total_reward: -72937.21
total_cost: 229471.84
total_trades: 6468
Sharpe: 0.464
=================================
----------------------------------
| time/              |           |
|    episodes        | 12        |
|    fps             | 110       |
|    time_elapsed    | 234       |
|    total_timesteps | 25884     |
| train/             |           |
|    actor_loss      | -553      |
|    critic_loss     | 4.04e+04  |
|    learning_rate   | 0.0003    |
|    n_updates       | 23727     |
|    reward          | 225.61232 |
----------------------------------
----------------------------------
| time/              |           |
|    episodes        | 16        |
|    fps             | 108       |
|    time_elapsed    | 319       |
|    total_timesteps | 34512     |
| train/             |           |
|    actor_loss      | -475      |
|    critic_loss     | 4.92e+04  |
|    learning_rate   | 0.0003    |
|    n_updates       | 32355     |
|    reward          | 225.61232 |
----------------------------------
----------------------------------
| time/              |           |
|    episodes        | 20        |
|    fps             | 106       |
|    time_elapsed    | 403       |
|    total_timesteps | 43140     |
| train/             |           |
|    actor_loss      | -430      |
|    critic_loss     | 5.43e+04  |
|    learning_rate   | 0.0003    |
|    n_updates       | 40983     |
|    reward          | 225.61232 |
----------------------------------
day: 2156, episode: 110
begin_total_asset: 100000000.00
end_total_asset: 99927062.79
total_reward: -72937.21
total_cost: 229471.84
total_trades: 6468
Sharpe: 0.464
=================================
----------------------------------
| time/              |           |
|    episodes        | 24        |
|    fps             | 106       |
|    time_elapsed    | 488       |
|    total_timesteps | 51768     |
| train/             |           |
|    actor_loss      | -410      |
|    critic_loss     | 3.78e+04  |
|    learning_rate   | 0.0003    |
|    n_updates       | 49611     |
|    reward          | 225.61232 |
----------------------------------
----------------------------------
| time/              |           |
|    episodes        | 28        |
|    fps             | 105       |
|    time_elapsed    | 573       |
|    total_timesteps | 60396     |
| train/             |           |
|    actor_loss      | -478      |
|    critic_loss     | 3.6e+03   |
|    learning_rate   | 0.0003    |
|    n_updates       | 58239     |
|    reward          | 225.61232 |
----------------------------------

<a id='6'></a>
# Bagian 7: Melakukan Jual-Beli

<a id='6.1'></a>
## 7.1. Performa di Dalam Sampel

Asumsikan modal awal adalah Rp100.000.000.

In [193]:
data_risk_indicator = processed_full_lot[(processed_full_lot.date<TRAIN_END_DATE) & (processed_full_lot.date>=TRAIN_START_DATE)]
insample_risk_indicator = data_risk_indicator.drop_duplicates(subset=['date'])

In [194]:
insample_risk_indicator.vix.describe()

count    2157.000000
mean       18.666583
std         7.813415
min         9.140000
25%        13.370000
50%        16.299999
75%        21.540001
max        56.650002
Name: vix, dtype: float64

In [195]:
insample_risk_indicator.vix.quantile(0.996)

48.84047967529307

In [196]:
insample_risk_indicator.turbulence.describe()

count    2157.000000
mean        3.740825
std         5.794681
min         0.000000
25%         0.684350
50%         2.070527
75%         4.635470
max        86.424818
Name: turbulence, dtype: float64

In [197]:
insample_risk_indicator.turbulence.quantile(0.996)

39.04870998547862

<a id='6.2'></a>
##7.2. Performa di Luar Sampel

FinRL dapat diatur dengan cara melakukan pelatihan ulang secara berkala, misalnya, pelatihan ulang setiap tiga bulan, bulanan, atau mingguan. 

Pada notebook ini, *hyperparameter* hanya diatur satu kali dengan menggunakan data sampel selama periode yang telah ditetapkan. Sehingga, terjadi beberapa peluruhan alfa seiring dengan perpanjangan tanggal perdagangan.

Banyak *hyperparameter* – mis. learning rate, mempengaruhi proses pembelajaran dan biasanya ditentukan dengan menguji beberapa variasi.

In [198]:
e_trade_gym = StockTradingEnv(df = trade, turbulence_threshold = 70, risk_indicator_col='vix', **env_kwargs)
# env_trade, obs_trade = e_trade_gym.get_sb_env()

<a id='6.3'></a>
##7.3. Hasil Jual-Beli Untuk Setiap Agen Berupa Rangkuman Aksi

<a id='6.3.1'></a>
###7.3.1. Agen 1: A2C

In [199]:
df_account_value_a2c, df_actions_a2c = DRLAgent.DRL_prediction(
    model=trained_a2c, 
    environment = e_trade_gym)

hit end!

<a id='6.3.2'></a>
###7.3.2. Agen 2: PPO

In [200]:
df_account_value_ppo, df_actions_ppo = DRLAgent.DRL_prediction(
    model=trained_ppo, 
    environment = e_trade_gym)

hit end!

<a id='6.3.3'></a>
###7.3.3. Agen 3: TD3

In [201]:
df_account_value_td3, df_actions_td3 = DRLAgent.DRL_prediction(
    model=trained_td3, 
    environment = e_trade_gym)

hit end!

<a id='6.3.4'></a>
###7.3.4. Agen 4: SAC

In [202]:
df_account_value_sac, df_actions_sac = DRLAgent.DRL_prediction(
    model=trained_sac, 
    environment = e_trade_gym)

hit end!

<a id='6.3.5'></a>
###7.3.5. Agen 5: DDPG

In [203]:
df_account_value_ddpg, df_actions_ddpg = DRLAgent.DRL_prediction(
    model=trained_ddpg, 
    environment = e_trade_gym)

hit end!

<a id='7'></a>
# Bagian 8: Performa Backtesting
Backtesting memiliki peran kunci dalam mengevaluasi kinerja strategi perdagangan. Alat backtesting otomatis lebih disukai karena dapat meminimalisir kesalahan manusia. Backtesting dapat dilakukan dengan menggunakan paket Quantopian pyfolio untuk menguji strategi perdagangan pada notebook ini. Backtesting tersebut mudah digunakan dan terdiri dari berbagai plot yang memberikan gambaran komprehensif tentang kinerja strategi perdagangan.

<a id='7.1'></a>
## 8.1 Status BackTesting

###8.1.1 Agen A2C

In [204]:
print("===========Get Backtest Results of A2C Model===========")
now = datetime.datetime.now().strftime('%Y%m%d-%Hh%M')

perf_stats_all = backtest_stats(account_value=df_account_value_a2c)
perf_stats_all = pd.DataFrame(perf_stats_all)
perf_stats_all.to_csv("./"+RESULTS_DIR+"/perf_stats_all_a2c_"+now+'.csv')

===========Get Backtest Results of A2C Model===========
Annual return         -0.157625
Cumulative returns    -0.285558
Annual volatility      0.338659
Sharpe ratio          -0.338225
Calmar ratio          -0.342739
Stability              0.829705
Max drawdown          -0.459899
Omega ratio            0.943737
Sortino ratio         -0.473588
Skew                        NaN
Kurtosis                    NaN
Tail ratio             1.082655
Daily value at risk   -0.043122
dtype: float64

###8.1.2 Agen ppo

In [205]:
print("===========Get Backtest Results of PPO Model===========")
now = datetime.datetime.now().strftime('%Y%m%d-%Hh%M')

perf_stats_all = backtest_stats(account_value=df_account_value_ppo)
perf_stats_all = pd.DataFrame(perf_stats_all)
perf_stats_all.to_csv("./"+RESULTS_DIR+"/perf_stats_all_ppo_"+now+'.csv')

===========Get Backtest Results of PPO Model===========
Annual return         -0.171497
Cumulative returns    -0.308439
Annual volatility      0.294853
Sharpe ratio          -0.492375
Calmar ratio          -0.418747
Stability              0.750317
Max drawdown          -0.409548
Omega ratio            0.918725
Sortino ratio         -0.703886
Skew                        NaN
Kurtosis                    NaN
Tail ratio             1.072564
Daily value at risk   -0.037724
dtype: float64

###8.1.3 Agen TD3

In [206]:
print("===========Get Backtest Results of TD3 Model===========")
now = datetime.datetime.now().strftime('%Y%m%d-%Hh%M')

perf_stats_all = backtest_stats(account_value=df_account_value_td3)
perf_stats_all = pd.DataFrame(perf_stats_all)
perf_stats_all.to_csv("./"+RESULTS_DIR+"/perf_stats_all_td3_"+now+'.csv')

===========Get Backtest Results of TD3 Model===========
Annual return         -0.169061
Cumulative returns    -0.304448
Annual volatility      0.343439
Sharpe ratio          -0.368645
Calmar ratio          -0.360414
Stability              0.834328
Max drawdown          -0.469076
Omega ratio            0.938825
Sortino ratio         -0.515893
Skew                        NaN
Kurtosis                    NaN
Tail ratio             1.074912
Daily value at risk   -0.043772
dtype: float64

###8.1.4 Agen SAC

In [207]:
print("===========Get Backtest Results of SAC Model===========")
now = datetime.datetime.now().strftime('%Y%m%d-%Hh%M')

perf_stats_all = backtest_stats(account_value=df_account_value_sac)
perf_stats_all = pd.DataFrame(perf_stats_all)
perf_stats_all.to_csv("./"+RESULTS_DIR+"/perf_stats_all_sac_"+now+'.csv')

===========Get Backtest Results of SAC Model===========
Annual return          0.060798
Cumulative returns     0.122660
Annual volatility      0.441534
Sharpe ratio           0.353088
Calmar ratio           0.129502
Stability              0.039276
Max drawdown          -0.469475
Omega ratio            1.060440
Sortino ratio          0.536916
Skew                        NaN
Kurtosis                    NaN
Tail ratio             1.157085
Daily value at risk   -0.055009
dtype: float64

###8.1.5 Agen DDPG

In [208]:
print("===========Get Backtest Results of DDPG Model===========")
now = datetime.datetime.now().strftime('%Y%m%d-%Hh%M')

perf_stats_all = backtest_stats(account_value=df_account_value_ddpg)
perf_stats_all = pd.DataFrame(perf_stats_all)
perf_stats_all.to_csv("./"+RESULTS_DIR+"/perf_stats_all_ddpg_"+now+'.csv')

===========Get Backtest Results of DDPG Model===========
Annual return         -0.168665
Cumulative returns    -0.303797
Annual volatility      0.344341
Sharpe ratio          -0.365378
Calmar ratio          -0.359739
Stability              0.834444
Max drawdown          -0.468853
Omega ratio            0.939391
Sortino ratio         -0.511188
Skew                        NaN
Kurtosis                    NaN
Tail ratio             1.076120
Daily value at risk   -0.043882
dtype: float64

###8.1.6. Baseline Stats

In [209]:
#baseline stats
print("===========Get Baseline Stats===========")
baseline_df = get_baseline(
        ticker="^JKII", 
        start = df_account_value_a2c.loc[0,'date'],
        end = df_account_value_a2c.loc[len(df_account_value_a2c)-1,'date'])

stats = backtest_stats(baseline_df, value_col_name = 'close')

===========Get Baseline Stats===========
[*********************100%***********************]  1 of 1 completed
Shape of DataFrame:  (478, 8)
Annual return         -0.041972
Cumulative returns    -0.078113
Annual volatility      0.185511
Sharpe ratio          -0.138819
Calmar ratio          -0.175216
Stability              0.093175
Max drawdown          -0.239543
Omega ratio            0.977818
Sortino ratio         -0.189296
Skew                        NaN
Kurtosis                    NaN
Tail ratio             0.900451
Daily value at risk   -0.023474
dtype: float64